using System;using System.Linq;using System.Drawing;using System.Reflection;using System.Windows.Forms;
class BattleResizeChecks {
 static BindingFlags F=BindingFlags.Instance|BindingFlags.NonPublic;
 static object Call(Game g,string name,params object[] args){return typeof(Game).GetMethod(name,F).Invoke(g,args);}
 static void Pump(){Application.DoEvents();}
 static void Check(bool ok,string text){if(!ok)throw new Exception(text);}
 static void Exercise(PartyBattleCanvas canvas){canvas.Dock=DockStyle.None;foreach(var size in new[]{Size.Empty,new Size(1,1),new Size(20,20),new Size(319,239),new Size(320,240),new Size(800,420),new Size(1280,720)}){canvas.Size=size;Pump();if(size.Width>0&&size.Height>0)using(var image=new Bitmap(size.Width,size.Height))canvas.DrawToBitmap(image,new Rectangle(Point.Empty,size));}}
 [STAThread]static void Main(){Application.SetUnhandledExceptionMode(UnhandledExceptionMode.ThrowException);Application.EnableVisualStyles();try{using(var game=new Game()){game.Opacity=1;game.Show();Pump();var save=new Save();typeof(Game).GetField("save",F).SetValue(game,save);save.toxicWoodland=ToxicWoodland.Create(0,save);var woodland=save.toxicWoodland;woodland.current=woodland.nodes.First(n=>n.kind=="battle").id;woodland.steps=2;woodland.mode="node-combat";var run=ToxicWoodland.StartBattle(woodland,save,(System.Collections.Generic.List<RogueEntry>)Call(game,"RogueBank"));Call(game,"RenderPartyBattle",run);Call(game,"StopAudio");var battle=run.partyBattle;var canvas=(PartyBattleCanvas)typeof(Game).GetField("partyCanvas",F).GetValue(game);var snapshot=Engine.Json.Serialize(battle);Exercise(canvas);Check(snapshot==Engine.Json.Serialize(battle),"Resize changed battle state");canvas.Dock=DockStyle.Fill;
 Check(PartyCombat.BeginSkill(battle,battle.selectedHero,"bolt",battle.enemies[0].id),"Start question");Call(game,"NextPartyQuestion",run);Call(game,"RenderPartyBattle",run);Exercise(canvas);canvas.Dock=DockStyle.Fill;game.WindowState=FormWindowState.Minimized;Pump();game.WindowState=FormWindowState.Normal;Pump();Check(canvas.Controls.OfType<BattleGlassPanel>().Any(p=>p.Visible),"Question missing after restore");Call(game,"AnswerPartyQuestion",run.question.answer);game.WindowState=FormWindowState.Minimized;Pump();var wait=System.Diagnostics.Stopwatch.StartNew();while(wait.ElapsedMilliseconds<2400){Application.DoEvents();System.Threading.Thread.Sleep(10);}game.WindowState=FormWindowState.Normal;Pump();Check(!canvas.IsCasting,"Animation did not complete after restore");Check(run.question.answered,"Question not resolved");game.Size=new Size(800,500);Pump();game.WindowState=FormWindowState.Maximized;Pump();game.WindowState=FormWindowState.Minimized;Pump();game.WindowState=FormWindowState.Normal;Pump();game.Close();}Console.WriteLine("PASS: zero/tiny/normal battle viewport, question overlay, minimize and restore, animation resolves, battle state preserved.");}catch(Exception ex){Console.WriteLine(ex);Environment.ExitCode=1;}}
}
