using System;using System.IO;using System.Linq;using System.Drawing;using System.Reflection;using System.Windows.Forms;using System.Collections.Generic;
class ChapterOneChecks {
 static BindingFlags flags=BindingFlags.Instance|BindingFlags.NonPublic;
 static object Get(Game g,string n){return typeof(Game).GetField(n,flags).GetValue(g);}
 static void Set(Game g,string n,object v){typeof(Game).GetField(n,flags).SetValue(g,v);}
 static object Call(Game g,string n){return typeof(Game).GetMethod(n,flags).Invoke(g,null);}
 static void Check(bool v,string m){if(!v)throw new Exception(m);}
 static void Pump(int ms){var end=DateTime.UtcNow.AddMilliseconds(ms);while(DateTime.UtcNow<end){Application.DoEvents();System.Threading.Thread.Sleep(10);}}
 static IEnumerable<Control> All(Control c){yield return c;foreach(Control child in c.Controls)foreach(var nested in All(child))yield return nested;}
 [STAThread]static void Main(){Application.EnableVisualStyles();using(var g=new Game()){g.Opacity=0;g.Show();var list=(List<Chapter>)Get(g,"chapters");var c=list.Single(x=>x.id==WaystationChapterOne.Id);var chooser=new Timer{Interval=100};chooser.Tick+=(sender,args)=>{foreach(var dialog in Application.OpenForms.Cast<Form>().ToList()){if(dialog.Text=="主线任务")All(dialog).OfType<Button>().First(b=>b.Text.StartsWith("第一章第一节")).PerformClick();else if(dialog.Text=="本节字幕与挑战模式")All(dialog).OfType<Button>().First(b=>b.Text.StartsWith("中英文字幕")).PerformClick();}};chooser.Start();Engine.Validate(c,Path.Combine(AppDomain.CurrentDomain.BaseDirectory,"chapters"));Check(c.lines.Count==30&&c.questions.Count==4,"chapter structure");var s=new Save();s.hasGame=true;Check(!SectionRules.Unlocked(c,list,s),"locked before prologue");s.completed.Add(TavernStory.Id);Check(SectionRules.Unlocked(c,list,s),"unlocks after prologue");Set(g,"save",s);Call(g,"ShowWaystationWorldMap");Pump(100);var map=All(g).OfType<WaystationWorldMap>().Single();Check(map.ChapterOneOpen&&!map.ChapterOneCompleted,"map first chapter unlocked");using(var frame=new Bitmap(g.Width,g.Height)){g.DrawToBitmap(frame,new Rectangle(Point.Empty,frame.Size));frame.Save(Path.Combine(AppDomain.CurrentDomain.BaseDirectory,"chapter-one-map.png"));}var bounds=(Rectangle)typeof(WaystationWorldMap).GetMethod("ChapterBounds",flags).Invoke(map,new object[]{1});typeof(WaystationWorldMap).GetMethod("OnMouseClick",flags).Invoke(map,new object[]{new MouseEventArgs(MouseButtons.Left,1,bounds.Left+bounds.Width/2,bounds.Top+bounds.Height/2,0)});Pump(2200);Check((string)Get(g,"page")=="waystation-chapter-cg","intro shown");Pump(1800);var cg=All(g).OfType<OpeningCgCanvas>().Single();Check(cg.AudioStarted&&cg.FramesShown>10,"intro video and voice playback");All(g).OfType<VNButton>().Single(b=>b.Text=="跳过 CG").PerformClick();Call(g,"StopAudio");Check((string)Get(g,"page")=="story"&&s.sectionAttempts[c.id].introShown,"skip proceeds and saves");foreach(int i in new[]{0,10,22,28}){Set(g,"index",i);Call(g,"UpdateLine");Pump(600);var stage=(ArtPanel)Get(g,"stage");Check(stage.WaystationPortraits,"large portraits");Check(stage.Actors.Single(a=>a.Id=="aelia").Visible==(i<28),"departure hides Aelia");using(var frame=new Bitmap(g.Width,g.Height)){g.DrawToBitmap(frame,new Rectangle(Point.Empty,frame.Size));frame.Save(Path.Combine(AppDomain.CurrentDomain.BaseDirectory,"chapter-one-"+i+".png"));}}
 s.lastChapter=c.id;s.positions[c.id]=10;Call(g,"ContinueGame");Call(g,"StopAudio");Check((string)Get(g,"page")=="story"&&(int)Get(g,"index")==10,"continue resumes chapter not prologue");foreach(var q in c.questions)s.quizAnswers[c.id+"/q/"+q.afterLine]=q.answer;Set(g,"index",29);Call(g,"Complete");Check((string)Get(g,"page")=="waystation-chapter-cg","outro shown");Pump(1500);cg=All(g).OfType<OpeningCgCanvas>().Single();Check(cg.AudioStarted&&cg.FramesShown>10,"outro playback");All(g).OfType<VNButton>().Single(b=>b.Text=="跳过 CG").PerformClick();Check((string)Get(g,"page")=="waystation-section-ending"&&s.completed.Contains(c.id),"completion");int xp=s.xp;Call(g,"CompleteChapterOne");Check(s.xp==xp&&xp==60,"reward only once");Pump(100);using(var frame=new Bitmap(g.Width,g.Height)){g.DrawToBitmap(frame,new Rectangle(Point.Empty,frame.Size));frame.Save(Path.Combine(AppDomain.CurrentDomain.BaseDirectory,"chapter-one-ending.png"));}Call(g,"ContinueGame");Check((string)Get(g,"page")=="tavern-hub","completed continue returns hub");Console.WriteLine("PASS: unlock, 30 lines, four questions, both CG video/voice, portraits, scene transitions, resume, completion and unique reward");chooser.Stop();chooser.Dispose();g.Close();}}
}
