using System;using System.IO;using System.Linq;using System.Drawing;using System.Reflection;using System.Windows.Forms;using System.Collections.Generic;
class ChapterTwoChecks {
 static BindingFlags flags=BindingFlags.Instance|BindingFlags.NonPublic;
 static object Get(Game g,string n){return typeof(Game).GetField(n,flags).GetValue(g);}static void Set(Game g,string n,object v){typeof(Game).GetField(n,flags).SetValue(g,v);}static object Call(Game g,string n){return typeof(Game).GetMethod(n,flags).Invoke(g,null);}static void Check(bool v,string m){if(!v)throw new Exception(m);}
 static IEnumerable<Control> All(Control c){yield return c;foreach(Control child in c.Controls)foreach(var x in All(child))yield return x;}
 static void Pump(int ms){var end=DateTime.UtcNow.AddMilliseconds(ms);while(DateTime.UtcNow<end){Application.DoEvents();System.Threading.Thread.Sleep(10);}}
 static void Frame(Game g,string n){using(var b=new Bitmap(g.Width,g.Height)){g.DrawToBitmap(b,new Rectangle(Point.Empty,b.Size));b.Save(Path.Combine(AppDomain.CurrentDomain.BaseDirectory,n+".png"));}}
 static void Choose(Game g){using(var timer=new Timer{Interval=100}){timer.Tick+=(s,e)=>{var f=Application.OpenForms.Cast<Form>().FirstOrDefault(x=>x.Text=="本节字幕与挑战模式");if(f==null)return;timer.Stop();All(f).OfType<Button>().First(x=>x.Text.StartsWith("中英文字幕")).PerformClick();};timer.Start();Call(g,"EnterChapterOneSecond");}}
 [STAThread]static void Main(){Application.EnableVisualStyles();using(var g=new Game()){g.Opacity=0;g.Show();Pump(100);var list=(List<Chapter>)Get(g,"chapters");var c=list.Single(WaystationChapterOne.Second);Engine.Validate(c,Path.Combine(AppDomain.CurrentDomain.BaseDirectory,"chapters"));Check(c.lines.Count==36&&c.questions.Count==4,"chapter structure");var save=new Save{hasGame=true};save.completed.Add(TavernStory.Id);Check(!SectionRules.Unlocked(c,list,save),"locked until first section complete");save.completed.Add(WaystationChapterOne.Id);Check(SectionRules.Unlocked(c,list,save),"unlocks after first section");Set(g,"save",save);
 using(var timer=new Timer{Interval=100}){timer.Tick+=(s,e)=>{var f=Application.OpenForms.Cast<Form>().FirstOrDefault(x=>x.Text=="主线任务");if(f==null)return;timer.Stop();var b=All(f).OfType<Button>().Single(x=>x.Text.StartsWith("第一章第二节"));Check(b.Enabled,"second entry enabled");f.Close();};timer.Start();Call(g,"ShowTavernMainQuest");}
 Choose(g);Check((string)Get(g,"page")=="waystation-chapter-cg","chooser leads to intro");Pump(1800);var cg=All(g).OfType<OpeningCgCanvas>().Single();Check(cg.AudioStarted&&cg.FramesShown>10,"intro voice and frames");All(g).OfType<VNButton>().Single(x=>x.Text=="跳过 CG").PerformClick();Pump(350);Call(g,"StopAudio");Check((string)Get(g,"page")=="story"&&save.sectionAttempts[c.id].introShown,"CG to dialogue");
 foreach(int i in new[]{0,7,22,29,34}){Set(g,"index",i);Call(g,"UpdateLine");Pump(400);var stage=(ArtPanel)Get(g,"stage");Check(stage.WaystationPortraits,"dialogue portrait mode");var lyse=stage.Actors.Single(a=>a.Id=="lyse");Check(lyse.Visible==(i>=6&&i<34)&&lyse.Mirror,"princess visibility and facing");Frame(g,"chapter-two-"+i);}
 save.lastChapter=c.id;save.positions[c.id]=22;Call(g,"ContinueGame");Call(g,"StopAudio");Check((string)Get(g,"page")=="story"&&(int)Get(g,"index")==22,"resume second section");
 foreach(var q in c.questions)save.quizAnswers[c.id+"/q/"+q.afterLine]=q.answer;Set(g,"index",35);Call(g,"Complete");Check((string)Get(g,"page")=="waystation-chapter-cg","outro before completion");Pump(1600);cg=All(g).OfType<OpeningCgCanvas>().Single();Check(cg.AudioStarted&&cg.FramesShown>10,"outro voice and frames");All(g).OfType<VNButton>().Single(x=>x.Text=="跳过 CG").PerformClick();Check(save.completed.Contains(c.id)&&save.sectionStars[c.id]==1&&save.xp==60,"stars and first reward");Check(save.storyFlags.Contains("lyse-met")&&save.storyFlags.Contains("rune-lantern-north-clue"),"future plot flags");Frame(g,"chapter-two-ending");Call(g,"CompleteChapterOne");Check(save.xp==60,"reward not repeated");Call(g,"ContinueGame");Check((string)Get(g,"page")=="tavern-hub","completed continue goes to hub");Choose(g);Check((string)Get(g,"page")=="waystation-chapter-cg"&&!save.sectionAttempts[c.id].review&&save.xp==60,"rechallenge chooser and CG preserve reward");g.Close();}
 Console.WriteLine("PASS: section unlock and menu, subtitle choice, two voiced CGs, 36 lines and portrait transitions, resume, grading, plot flags, reward deduplication and rechallenge.");}
}
