using System;using System.IO;using System.Linq;using System.Reflection;using System.Windows.Forms;using System.Collections.Generic;using System.Drawing;
class ChapterContinuationChecks {
 static BindingFlags flags=BindingFlags.Instance|BindingFlags.NonPublic;
 static object Get(Game g,string n){return typeof(Game).GetField(n,flags).GetValue(g);}static void Set(Game g,string n,object v){typeof(Game).GetField(n,flags).SetValue(g,v);}static object Call(Game g,string n,params object[] args){return typeof(Game).GetMethod(n,flags).Invoke(g,args);}static void Check(bool ok,string message){if(!ok)throw new Exception(message);}
 static IEnumerable<Control> All(Control c){yield return c;foreach(Control child in c.Controls)foreach(var x in All(child))yield return x;}
 static void Pump(int ms){var end=DateTime.UtcNow.AddMilliseconds(ms);while(DateTime.UtcNow<end){Application.DoEvents();System.Threading.Thread.Sleep(10);}}
 [STAThread]static void Main(){Application.EnableVisualStyles();using(var g=new Game()){g.Opacity=0;g.Show();Pump(100);var chapters=(List<Chapter>)Get(g,"chapters");var save=new Save{hasGame=true};save.completed.Add(TavernStory.Id);Set(g,"save",save);
  for(int n=0;n<6;n++){var c=chapters.Single(x=>x.id==WaystationChapterOne.Ids[n]);Engine.Validate(c,Path.Combine(AppDomain.CurrentDomain.BaseDirectory,"chapters"));Check(c.questions.Count==4,"four questions per section");Check(SectionRules.Unlocked(c,chapters,save),"previous completion unlocks section");if(n<5)Check(!SectionRules.Unlocked(chapters.Single(x=>x.id==WaystationChapterOne.Ids[n+1]),chapters,save),"next section still locked");if(n<2){save.completed.Add(c.id);continue;}
   using(var timer=new Timer{Interval=100}){timer.Tick+=(s,e)=>{var dialog=Application.OpenForms.Cast<Form>().FirstOrDefault(f=>f.Text=="本节字幕与挑战模式");if(dialog==null)return;timer.Stop();All(dialog).OfType<Button>().First(b=>b.Text.StartsWith("中英文字幕")).PerformClick();};timer.Start();Call(g,"EnterWaystationSection",c.id);}
   Check((string)Get(g,"page")=="waystation-chapter-cg","intro shown");Pump(1100);var cg=All(g).OfType<OpeningCgCanvas>().Single();Check(cg.AudioStarted&&cg.FramesShown>5,"intro video and voice");All(g).OfType<VNButton>().Single(b=>b.Text=="跳过 CG").PerformClick();Pump(100);Call(g,"StopAudio");Check((string)Get(g,"page")=="story","intro enters dialogue");
   Set(g,"index",12);Call(g,"UpdateLine");save.lastChapter=c.id;save.positions[c.id]=12;Call(g,"ContinueGame");Call(g,"StopAudio");Check((string)Get(g,"page")=="story"&&(int)Get(g,"index")==12,"continue resumes each section");
   using(var b=new Bitmap(g.Width,g.Height)){g.DrawToBitmap(b,new Rectangle(Point.Empty,b.Size));b.Save(Path.Combine(AppDomain.CurrentDomain.BaseDirectory,"section-"+(n+1)+".png"));}
   foreach(var q in c.questions)save.quizAnswers[c.id+"/q/"+q.afterLine]=q.answer;Set(g,"index",c.lines.Count-1);Call(g,"Complete");Check((string)Get(g,"page")=="waystation-chapter-cg","outro shown");Pump(1000);cg=All(g).OfType<OpeningCgCanvas>().Single();Check(cg.AudioStarted&&cg.FramesShown>5,"outro video and voice");All(g).OfType<VNButton>().Single(b=>b.Text=="跳过 CG").PerformClick();Check(save.completed.Contains(c.id)&&save.sectionStars[c.id]==1,"completion and bilingual grade");int xp=save.xp;Call(g,"CompleteChapterOne");Check(save.xp==xp,"completion reward deduplicated");Console.WriteLine("PASS section "+(n+1)+": unlock, media, resume, four answers, score and reward");
  }
  Check(save.xp==240&&save.storyFlags.Contains("first-seal-fragment")&&save.storyFlags.Contains("waystation-chapter-one-complete")&&save.storyFlags.Contains("lyse-royal-identity"),"chapter ending flags and XP");Call(g,"ShowWaystationWorldMap");Check(All(g).OfType<WaystationWorldMap>().Single().ChapterOneCompleted,"map marks whole chapter complete");g.Close();}Console.WriteLine("PASS: complete chapter one continuation");}
}
