using System;using System.IO;using System.Drawing;using System.Linq;using System.Windows.Forms;
class CompletionLayoutChecks {
 static void Check(bool valid,string message){if(!valid)throw new Exception(message);}
 static void Fits(Graphics g,string text,RectangleF box,float size,bool bold){float fitted=PrologueCompletion.FittedTextSize(g,text,box,size,bold);using(var f=new Font("Microsoft YaHei",fitted,bold?FontStyle.Bold:FontStyle.Regular,GraphicsUnit.Pixel))using(var format=new StringFormat()){int chars,lines;g.MeasureString(text,f,box.Size,format,out chars,out lines);Check(chars==text.Length,"Text clipped: "+text);}}
 [STAThread]static void Main(){Application.EnableVisualStyles();string root=AppDomain.CurrentDomain.BaseDirectory;using(var bitmap=new Bitmap(1672,941))using(var g=Graphics.FromImage(bitmap)){
 foreach(string file in Directory.GetFiles(Path.Combine(root,"chapters"),"*-tavern-01-*.json")){var chapter=Engine.Json.Deserialize<Chapter>(File.ReadAllText(file));int number=WaystationChapterOne.Number(chapter);string title="第"+(number+1)+"节完成 · "+WaystationChapterOne.Names[number],ending=chapter.ending+"\n"+(number<5?"下一节“"+WaystationChapterOne.Names[number+1]+"”已解锁。":"第一章完成 · 今天，驿站终于迎来了客人。");Fits(g,title,new RectangleF(220,113,1232,92),44,true);Fits(g,ending,new RectangleF(250,218,1172,84),21,false);
 for(int i=0;i<chapter.questions.Count;i++){var card=PrologueCompletion.QuestionBounds(i,chapter.questions.Count);Check(card.Height>136&&card.Bottom<=782,"Card content outside available area");for(int j=0;j<i;j++)Check(!card.IntersectsWith(PrologueCompletion.QuestionBounds(j,chapter.questions.Count)),"Overlapping cards");Fits(g,chapter.questions[i].prompt,new RectangleF(0,0,card.Width-100,62),24,true);Fits(g,chapter.questions[i].explanation,new RectangleF(0,0,card.Width-56,card.Height-136),18,false);}
 if(WaystationChapterOne.Second(chapter)){using(var art=Image.FromFile(Path.Combine(root,"chapters",chapter.lines.Last().scene)))foreach(var size in new[]{new Size(1920,1080),new Size(1280,720),new Size(800,500)})using(var control=new PrologueCompletion{Size=size,Chapter=chapter,Save=new Save(),BackgroundArt=art,Correct=2,Stars=1,FirstCompletion=true,CompletionTitle=title,CompletionText=ending})using(var preview=new Bitmap(size.Width,size.Height)){control.CreateControl();control.DrawToBitmap(preview,new Rectangle(Point.Empty,size));preview.Save(Path.Combine(root,"completion-"+size.Width+".png"));foreach(Control button in control.Controls)Check(control.ClientRectangle.Contains(button.Bounds),"Button outside window");}}
 }
 }Console.WriteLine("PASS: all six completion titles, descriptions and question texts fit; four cards do not overlap; previews at 1920, 1280 and 800 pixels.");}
}
