using System;using System.Linq;using System.IO;using System.Collections.Generic;
class ExpeditionLearningChecks {
 static void Check(bool value,string label){if(!value)throw new Exception(label);}
 static void Main(){var today=new DateTime(2026,10,8);var p=new RogueProfile();var bank=Engine.Json.Deserialize<List<RogueEntry>>(File.ReadAllText("assets/cet4-words.json")).Concat(Engine.Json.Deserialize<List<RogueEntry>>(File.ReadAllText("assets/cet6-words.json"))).GroupBy(w=>w.word,StringComparer.OrdinalIgnoreCase).Select(g=>g.First()).ToList();int spellingCount=0;var last=new Dictionary<string,int>();var retired=new HashSet<string>();
 for(int i=0;i<500;i++){var q=ExpeditionVocabulary.Next(p,bank,today);Check(q.kind>=0,"unexpected exhausted pool");if(q.kind==3)spellingCount++;Check(!retired.Contains(q.entry.word),"learned word returned same day");if(q.kind!=3){Check(q.options.Count==4&&q.options.Distinct().Count()==4,"unique choices");Check(q.options[q.answer]==(q.kind==0?ExpeditionVocabulary.Meaning(q.entry):q.entry.word),"correct option");}else{Check(ExpeditionVocabulary.Correct(q,-1,"  "+q.entry.word.ToUpperInvariant()+"  "),"spelling case and trim");Check(!ExpeditionVocabulary.Correct(q,-1,q.entry.word+"x"),"wrong spelling");Check(!ExpeditionVocabulary.Correct(q,-1,""),"empty spelling");}int prior;if(last.TryGetValue(q.entry.word,out prior))Check(i-prior>=9,"repeat spacing");last[q.entry.word]=i;ExpeditionVocabulary.Answer(p,q,true,today);if(p.expeditionLearning.words[q.entry.word].stage>0)retired.Add(q.entry.word);if(i==250)p=Engine.Json.Deserialize<RogueProfile>(Engine.Json.Serialize(p));}
 Check(spellingCount>80&&spellingCount<200,"moderate spelling frequency");Check(retired.Count>80,"learning progress");var word=retired.First();var memory=p.expeditionLearning.words[word];Check(memory.stage==1&&memory.due=="2026-10-09","initial due");var probe=new RogueQuestion{entry=bank.First(w=>w.word==word),kind=0};int[] gaps={3,7,14,30};var date=today.AddDays(1);foreach(int gap in gaps){Check(ExpeditionVocabulary.Due(memory,date),"due review");ExpeditionVocabulary.Answer(p,probe,true,date);Check(memory.due==date.AddDays(gap).ToString("yyyy-MM-dd"),"review interval");date=date.AddDays(gap);}ExpeditionVocabulary.Answer(p,probe,true,date);Check(memory.stage==6&&!ExpeditionVocabulary.Due(memory,date.AddYears(1)),"long term retirement");
 ExpeditionVocabulary.Answer(p,probe,false,date);Check(memory.stage==0&&memory.streak==0&&memory.failed,"wrong resets learning");
 var old=new RogueProfile();old.memory["abandon"]=new RogueMemory{correct=8};var migrated=ExpeditionVocabulary.Progress(old,"abandon",today);Check(migrated.stage==1&&ExpeditionVocabulary.Due(migrated,today),"legacy migration");Check(old.memory["abandon"].correct==8,"legacy stats preserved");
 var retryProfile=new RogueProfile();var first=ExpeditionVocabulary.Next(retryProfile,bank,today);ExpeditionVocabulary.Answer(retryProfile,first,false,today);for(int i=0;i<5;i++){var other=ExpeditionVocabulary.Next(retryProfile,bank,today);Check(other.entry.word!=first.entry.word,"wrong repeated too early");ExpeditionVocabulary.Answer(retryProfile,other,true,today);}Check(ExpeditionVocabulary.Next(retryProfile,bank,today).entry.word==first.entry.word,"wrong word not retried promptly");
 var reviewProfile=new RogueProfile();foreach(var e in bank)reviewProfile.memory[e.word]=new RogueMemory{correct=3};var counts=new int[4];for(int i=0;i<30;i++){var review=ExpeditionVocabulary.Next(reviewProfile,bank,today);counts[review.kind]++;ExpeditionVocabulary.Answer(reviewProfile,review,true,today);}Check(counts[0]==10&&counts[1]==10&&counts[3]==10,"legacy review question balance");
 var mixed=new RogueProfile();foreach(var e in bank.Take(100))mixed.memory[e.word]=new RogueMemory{correct=3};int newQuestions=0;for(int i=0;i<30;i++){var q=ExpeditionVocabulary.Next(mixed,bank,today);if(ExpeditionVocabulary.Progress(mixed,q.entry.word,today).stage==0)newQuestions++;ExpeditionVocabulary.Answer(mixed,q,true,today);}Check(newQuestions>=10,"reviews starved new learning");Check(mixed.expeditionLearning.words.Count<bank.Count/2,"unused bank inflated progress save");
 var save=new Save();var woodland=ToxicWoodland.Create(19,save);woodland.mode="node-combat";var combat=ToxicWoodland.StartBattle(woodland,save,bank);Check(combat.pool==null,"full bank stored in combat save");combat.pool=bank;Check(ToxicWoodland.StartBattle(woodland,save,bank).pool==null,"legacy combat bank not removed");
 Console.WriteLine("PASS: actual CET banks, 500 answers, spacing, retirement, unique options, save roundtrip, all review stages, wrong reset and legacy migration.");
 }
}
