using System;using System.IO;using System.Linq;using System.Reflection;using System.Windows.Forms;using System.Drawing;using System.Collections.Generic;
class InGameSettingsChecks {
 static BindingFlags flags=BindingFlags.Instance|BindingFlags.NonPublic;
 static object Get(Game g,string n){return typeof(Game).GetField(n,flags).GetValue(g);}static void Set(Game g,string n,object v){typeof(Game).GetField(n,flags).SetValue(g,v);}static object Call(Game g,string n,params object[] args){return typeof(Game).GetMethod(n,flags).Invoke(g,args);}static void Check(bool v,string s){if(!v)throw new Exception(s);}
 static IEnumerable<Control> All(Control c){yield return c;foreach(Control child in c.Controls)foreach(var x in All(child))yield return x;}
 static void Pump(int ms){var until=DateTime.UtcNow.AddMilliseconds(ms);while(DateTime.UtcNow<until){Application.DoEvents();System.Threading.Thread.Sleep(10);}}
 static bool Escape(Form form){var key=Message.Create(form.Handle,0x100,new IntPtr((int)Keys.Escape),IntPtr.Zero);return Application.FilterMessage(ref key);}
 static void Menu(Game g,Form owner,Action<Form> verify){using(var timer=new Timer{Interval=120}){timer.Tick+=(s,e)=>{var f=Application.OpenForms.Cast<Form>().FirstOrDefault(x=>x.Text=="游戏设置");if(f==null)return;timer.Stop();verify(f);Check(Escape(f),"ESC closes settings");};timer.Start();Check(Escape(owner),"ESC consumed globally");}}
 [STAThread]static void Main(){using(var g=new Game()){g.Opacity=0;g.Show();Pump(100);var save=new Save{hasGame=true,fullscreen=true};save.completed.Add(TavernStory.Id);Set(g,"save",save);Call(g,"ApplyFullscreen");var size=g.Size;Menu(g,g,f=>{Check((string)Get(g,"page")=="home"&&g.Size==size&&save.fullscreen,"ESC must preserve fullscreen and page");Check(!All(f).Any(x=>x is TabControl||x is ComboBox),"no native white borders");Check(All(f).OfType<SettingsVolumeSlider>().Count()==5,"five sound controls");All(f).OfType<SettingsVolumeSlider>().Single(x=>x.AccessibleName=="总音量").Value=37;Check(All(f).OfType<Button>().Any(x=>x.Text=="保存并退出游戏"),"exit entry");using(var frame=new Bitmap(f.Width,f.Height)){f.DrawToBitmap(frame,new Rectangle(Point.Empty,frame.Size));frame.Save(Path.Combine(AppDomain.CurrentDomain.BaseDirectory,"in-game-settings.png"));}});Check(save.masterVolume==37&&(string)Get(g,"page")=="home","saved volume and preserved page");
 var chapter=((List<Chapter>)Get(g,"chapters")).Single(x=>x.id==WaystationChapterOne.Id);save.sectionAttempts[chapter.id]=new SectionAttempt{subtitlesChosen=true,chineseSubtitles=true,englishSubtitles=true};Call(g,"EnterChapterOne");Pump(1500);var cg=All(g).OfType<OpeningCgCanvas>().Single();int shown=0;using(var timer=new Timer{Interval=250}){int ticks=0;timer.Tick+=(s,e)=>{var f=Application.OpenForms.Cast<Form>().FirstOrDefault(x=>x.Text=="游戏设置");if(f==null)return;if(ticks++==0){shown=cg.FramesShown;Check((bool)typeof(OpeningCgCanvas).GetField("paused",flags).GetValue(cg),"CG paused");return;}Check(cg.FramesShown==shown,"CG freezes while settings open");timer.Stop();Escape(f);};timer.Start();Escape(g);}Pump(300);Check(cg.FramesShown>shown,"CG resumes");All(g).OfType<VNButton>().Single(x=>x.Text=="跳过 CG").PerformClick();Pump(300);int index=(int)Get(g,"index");Menu(g,g,f=>{Check((bool)Get(g,"pausedAudio"),"dialogue voice paused");All(f).OfType<Button>().Single(x=>x.Text=="画面与字幕").PerformClick();var chinese=All(f).OfType<CheckBox>().Single(x=>x.Text=="显示中文字幕");chinese.Checked=true;using(var frame=new Bitmap(f.Width,f.Height)){f.DrawToBitmap(frame,new Rectangle(Point.Empty,frame.Size));frame.Save(Path.Combine(AppDomain.CurrentDomain.BaseDirectory,"in-game-settings-picture.png"));}});Check((string)Get(g,"page")=="story"&&(int)Get(g,"index")==index&&save.fullscreen,"dialogue stays at same line");Call(g,"StopAudio");
 Call(g,"AddWord","flour",chapter.lines[0].text);var word=Application.OpenForms.Cast<Form>().OfType<WordDefinitionPopup>().Single();Menu(g,word,f=>Check(word.Visible,"ESC opens settings over word popup"));Check(word.Visible,"word popup preserved");word.Close();Call(g,"ShowWaystationWorldMap");Menu(g,g,f=>Check((string)Get(g,"page")=="waystation-map","map does not return on ESC"));Check((string)Get(g,"page")=="waystation-map","map remains after settings");g.Close();}
 using(var exitGame=new Game()){exitGame.Opacity=0;exitGame.Show();Pump(100);using(var timer=new Timer{Interval=120}){timer.Tick+=(s,e)=>{var f=Application.OpenForms.Cast<Form>().FirstOrDefault(x=>x.Text=="游戏设置");if(f==null)return;timer.Stop();All(f).OfType<Button>().Single(x=>x.Text=="保存并退出游戏").PerformClick();};timer.Start();Escape(exitGame);}Check(exitGame.IsDisposed,"exit closes game");}Console.WriteLine("PASS: global ESC in fullscreen, map, dialogue, CG and word popup; audio controls, save, exit entry, pause/resume and preserved progress.");}
}
