using System;using System.Linq;using System.Drawing;using System.Reflection;using System.Windows.Forms;using System.Collections.Generic;
class PartyWordFeedbackChecks {
 static BindingFlags F=BindingFlags.Instance|BindingFlags.NonPublic;
 static object Call(Game g,string name,params object[] args){return typeof(Game).GetMethod(name,F).Invoke(g,args);}
 static void Check(bool ok,string message){if(!ok)throw new Exception(message);}
 static IEnumerable<Control> All(Control c){yield return c;foreach(Control child in c.Controls)foreach(var x in All(child))yield return x;}
 static BattleGlassPanel Panel(PartyBattleCanvas c){return c.Controls.OfType<BattleGlassPanel>().Single();}
 static void Shot(Control c,string name){using(var image=new Bitmap(c.Width,c.Height)){c.DrawToBitmap(image,c.ClientRectangle);image.Save(System.IO.Path.Combine(AppDomain.CurrentDomain.BaseDirectory,name+".png"));}}
 [STAThread]static void Main(){Application.SetUnhandledExceptionMode(UnhandledExceptionMode.ThrowException);Application.EnableVisualStyles();using(var game=new Game()){game.Opacity=0;game.Show();Application.DoEvents();foreach(bool defense in new[]{false,true})foreach(bool correct in new[]{false,true}){var save=new Save();typeof(Game).GetField("save",F).SetValue(game,save);save.toxicWoodland=ToxicWoodland.Create(0,save);var w=save.toxicWoodland;w.current=w.nodes.First(n=>n.kind=="battle").id;w.steps=2;w.mode="node-combat";var run=ToxicWoodland.StartBattle(w,save,(List<RogueEntry>)Call(game,"RogueBank"));var b=run.partyBattle;
 if(defense){b.active=b.enemies[0].id;b.enemySkill="bite";b.enemyDamage=10;b.defenseTargets=new List<string>{b.heroes[0].id};b.phase="defense-question";}else Check(PartyCombat.BeginSkill(b,b.selectedHero,"bolt",b.enemies[0].id),"Begin skill");Call(game,"NextPartyQuestion",run);Call(game,"RenderPartyBattle",run);var canvas=(PartyBattleCanvas)typeof(Game).GetField("partyCanvas",F).GetValue(game);var panel=Panel(canvas);Check(All(panel).OfType<RogueIcon>().Count()==2,"Question missing word icons");var star=All(panel).OfType<RogueIcon>().Single(x=>x.Kind=="star");star.PerformClick();Check(save.words.Any(x=>x.text==run.question.entry.word)&&star.Selected,"Favorite add");star.PerformClick();Check(!save.words.Any(x=>x.text==run.question.entry.word)&&!star.Selected,"Favorite remove");All(panel).OfType<RogueIcon>().Single(x=>x.Kind=="speaker").PerformClick();Call(game,"StopAudio");if(!defense&&correct)Shot(panel,"battle-question-icons");int selected=correct?run.question.answer:(run.question.answer+1)%4;Call(game,"FinishPartyQuestion",selected);typeof(PartyBattleCanvas).GetMethod("StopCast",F).Invoke(canvas,null);panel=Panel(canvas);Check(All(panel).Any(x=>x.Text==(correct?"回答正确":"回答错误")),"Verdict missing");Check(All(panel).OfType<RogueIcon>().Count()==2,"Result missing icons");Check(b.lastAnswerCorrect==correct,"Result state mismatch");var restored=Engine.Json.Deserialize<PartyCombatState>(Engine.Json.Serialize(b));Check(restored.lastAnswerCorrect==correct,"Result lost on save/reload");var selectedStar=All(panel).OfType<RogueIcon>().Single(x=>x.Kind=="star");Check(selectedStar.Selected==save.words.Any(x=>x.text==run.question.entry.word),"Result favorite out of sync");if(!defense&&correct)Shot(panel,"battle-result-correct-icons");if(defense&&!correct)Shot(panel,"battle-result-wrong-icons");b.lastAnswerCorrect=null;b.phase="enemy-feedback";Call(game,"RenderPartyBattle",run);panel=Panel(canvas);Check(!All(panel).Any(x=>x.Visible&&(x.Text=="回答正确"||x.Text=="回答错误")),"Stale verdict on non-question action");Check(!All(panel).OfType<RogueIcon>().Any(),"Stale word icons on non-question action");}game.Close();}Console.WriteLine("PASS: attack/defense correct/wrong verdicts, question/result icons, reading action, favorite add/remove/state, saved results, no stale result on automatic actions.");}
}
