using System;using System.Linq;using System.Collections.Generic;using System.Drawing;using System.Windows.Forms;
public static class PartyCombatChecks {
 static void Check(bool yes,string message){if(!yes)throw new Exception(message);}
 static PartyCombatState New(int seed=1){return PartyCombat.Create(new RogueRun{id="tavern-tutorial",seed=seed,enemyHp=110,enemyMax=110},new Save());}
 static PartyUnit Select(PartyCombatState b,string id,string skill,int rank){var h=b.heroes.First(u=>u.id==id);h.rank=rank;h.acted=false;h.cooldowns.Clear();h.skills=HeroSkills.Normalize(id,new[]{skill});b.phase="heroes";b.active=id;b.selectedHero=b.heroes.IndexOf(h);return h;}
 static void Use(PartyCombatState b,string id,string skill,string target,int rank=1,bool correct=true){Select(b,id,skill,rank);Check(PartyCombat.BeginSkill(b,b.selectedHero,skill,target),"begin "+skill);PartyCombat.AttackAnswer(b,correct);}
 [STAThread]public static void Main(){
  Check(HeroSkills.Knight.Length==10&&HeroSkills.Mage.Length==10,"ten skills");var b=New();Check(b.active=="luchuan"&&b.heroes[1].rank==3,"speed and default legal mage rank");Check(!PartyCombat.CanUse(b,b.heroes[0],HeroSkills.Get("aelia","slash")),"cannot play out of turn");
  var h=Select(b,"luchuan","wave",3);Check(!PartyCombat.CanUse(b,h,HeroSkills.Get(h.id,"wave")),"wave locked to rank4");h.rank=4;Check(!PartyCombat.CanUse(b,h,HeroSkills.Get(h.id,"inscribe")),"inscribe disallowed4");
  b=New();Use(b,"aelia","bleed","enemy-0",1,false);Check(b.enemies[0].hp==105&&b.enemies[0].dots.Count==0,"wrong half and no status");int hp=b.enemies[0].hp;PartyCombat.AttackAnswer(b,true);Check(b.enemies[0].hp==hp,"single answer resolution");
  b=New();Use(b,"aelia","bleed","enemy-0");Check(b.enemies[0].dots.Single().damage==3&&b.enemies[0].bleed==3,"bleed application");PartyCombat.Dot(b.enemies[0],"bleed","aelia:bleed",3,3);Check(b.enemies[0].dots.Single().damage==6&&b.enemies[0].dots.Single().turns==4,"same source stacks damage and adds one tick");PartyCombat.Dot(b.enemies[0],"bleed","other",2,2);PartyCombat.Dot(b.enemies[0],"bleed","third",2,2);Check(b.enemies[0].dots.Single().damage==10&&b.enemies[0].dots.Single().turns==6,"different sources stack without cap");
  foreach(var kind in new[]{"bleed","blight","burn"}){b=New();var enemy=b.enemies[0];PartyCombat.Dot(enemy,kind,"one",3,3);enemy.dots[0].turns=1;PartyCombat.Dot(enemy,kind,"two",2,5);Check(enemy.dots.Single().damage==5&&enemy.dots.Single().turns==2,"adds one instead of refreshing "+kind);b=Engine.Json.Deserialize<PartyCombatState>(Engine.Json.Serialize(b));enemy=b.enemies[0];enemy.shield=40;b.queue=new List<string>{enemy.id};b.cursor=0;int before=enemy.hp;typeof(PartyCombat).GetMethod("StartNext",System.Reflection.BindingFlags.NonPublic|System.Reflection.BindingFlags.Static).Invoke(null,new object[]{b});Check(enemy.hp==before-5&&enemy.shield==40&&enemy.dots.Single().turns==1,"saved stacked damage ticks once and bypasses shield "+kind);}
  b=New();PartyCombat.Dot(b.enemies[0],"bleed","one",3,2);PartyCombat.Dot(b.enemies[0],"blight","two",2,3);PartyCombat.Dot(b.enemies[0],"bleed","three",4,3);Check(b.enemies[0].dots.Count==2&&b.enemies[0].dots.Single(d=>d.kind=="blight").damage==2&&b.enemies[0].dots.Single(d=>d.kind=="blight").turns==3,"different status kinds remain independent");
  b=New();b.enemies.Add(PartyCombat.Monster("crab",1,1));b.enemies[1].rank=2;Use(b,"aelia","sweep","enemy-0");Check(b.questions==1&&b.enemies.All(u=>u.hp<u.maxHp),"fixed front group one answer");
  b=New();b.enemies[0].marks=3;Use(b,"luchuan","detonate","enemy-0",3,false);Check(b.enemies[0].marks==3,"wrong preserves resource");
  b=New();b.enemies[0].marks=2;b.enemies[0].dodge=1;Use(b,"luchuan","detonate","enemy-0",3);Check(b.enemies[0].marks==0&&b.enemies[0].dodge==1,"precise does not consume dodge");
  b=New();b.heroes[0].block=1;b.heroes[0].guard="luchuan";b.enemies[0].strength=1;b.active="enemy-0";b.phase="defense-question";b.enemyGroup=true;b.enemyDamage=20;b.enemySkill="spore";b.defenseTargets=new List<string>{"aelia","luchuan"};PartyCombat.DefenseAnswer(b,true);Check(b.questions==1&&b.heroes[0].hp==95&&b.heroes[1].hp==65,"one enemy AoE quiz halves all, consumes block");Check(b.heroes.All(u=>u.dots.Any(d=>d.kind=="blight")),"group dots");
  b=New();b.enemies[0].preparation="physical";b.enemies[0].rank=3;Use(b,"aelia","bash","enemy-0");Check(b.enemies[0].preparation==null,"bash interrupts physical");
  b=New();b.enemies[0].marks=1;b.enemies[0].rank=3;b.enemies[0].preparation="physical";Use(b,"luchuan","silence","enemy-0",3);Check(b.enemies[0].preparation=="physical","silence does not interrupt physical");
  b=New();b.enemies[0].marks=1;b.enemies[0].rank=3;b.enemies[0].preparation="spell";Use(b,"luchuan","silence","enemy-0",3);Check(b.enemies[0].preparation==null,"silence interrupts spell");
  b=New();b.enemies[0].rank=3;b.enemies[0].preparation="physical";Use(b,"luchuan","pull","enemy-0",3);Check(b.enemies[0].rank==2&&b.enemies[0].preparation==null,"pull invalidates preparation");
  b=New();Select(b,"luchuan","retreat",2);Check(PartyCombat.MoveAction(b,1)&&b.heroes[1].rank==3,"empty-grid move does not compact");
  b=New();b.heroes[0].hp=30;PartyCombat.Dot(b.heroes[0],"bleed","test",3,2);Use(b,"aelia","recover","aelia");Check(b.heroes[0].hp==50&&b.heroes[0].dots.Count==0,"recovery clears dots");
  b=New();b.heroes[0].resolve=1;Use(b,"aelia","inspire","luchuan");Check(b.heroes[1].strength==1&&b.heroes[0].resolve==0,"inspiration resource");
  b=New();Use(b,"aelia","bash","enemy-0");Check(b.heroes[0].cooldowns["bash"]==2,"one action interval");b=Engine.Json.Deserialize<PartyCombatState>(Engine.Json.Serialize(b));Check(b.phase=="feedback"&&b.enemies[0].hp<110,"save pending feedback");
  var old=new PartyCombatState();old.heroes.Add(new PartyUnit{id="luchuan",hp=60,maxHp=75,rank=2,skills=new List<string>{"collapse","spread","bolt"}});old.enemies.Add(new PartyUnit{id="enemy-0",hp=50,maxHp=100,rank=1});PartyCombat.Ensure(old);Check(old.heroes[0].hp==60&&old.heroes[0].skills.Count==5&&old.version==4,"legacy preserves health and repairs loadout");
  for(int seed=0;seed<9;seed++){var run=new RogueRun{id="expedition",seed=seed};b=PartyCombat.Create(run,new Save());Check(b.enemies.Select(u=>u.rank).Distinct().Count()==b.enemies.Count,"unique enemy grid positions");int steps=0;while(String.IsNullOrEmpty(b.outcome)&&steps++<250){if(b.phase=="heroes"){h=b.heroes.First(u=>u.id==b.active);var skill=HeroSkills.For(h.id).Where(s=>PartyCombat.CanUse(b,h,s)).FirstOrDefault(s=>s.Damage>0);if(skill!=null)PartyCombat.BeginSkill(b,b.selectedHero,skill.Id,PartyCombat.Targets(b,h,skill)[0].id);else PartyCombat.EndHeroes(b);}else if(b.phase=="attack-question")PartyCombat.AttackAnswer(b,true);else if(b.phase=="defense-question")PartyCombat.DefenseAnswer(b,true);else PartyCombat.Continue(b);}Check(steps<250&&!String.IsNullOrEmpty(b.outcome),"encounter terminates "+seed);}
  b=New();foreach(var k in new[]{"crab","moth","bard","cannon"})Check(PartyMonsterArt.Get(Environment.CurrentDirectory,k,null)!=null,"monster art "+k);
  b.heroes[0].block=2;b.heroes[0].resolve=2;b.heroes[0].weak=1;b.heroes[0].vulnerable=1;PartyCombat.Dot(b.heroes[0],"bleed","test",3,3);PartyCombat.Dot(b.heroes[1],"blight","test",2,2);b.heroes[1].dodge=1;b.enemies[0].preparation="physical";b.enemies[0].marks=2;
  using(var scene=new Bitmap("chapters/art/tavern/chapter-one-road.png"))using(var male=Image.FromFile("assets/characters/animations/luchuan-idle.gif"))using(var female=Image.FromFile("assets/characters/animations/aelia-idle.gif"))using(var canvas=new PartyBattleCanvas{Width=1280,Height=800,ArtRoot=Environment.CurrentDirectory,Battle=b,Scene=scene,Male=male,Female=female,Skill=HeroSkills.Get("luchuan","bolt")})using(var shot=new Bitmap(1280,800)){canvas.DrawToBitmap(shot,new Rectangle(0,0,1280,800));shot.Save(".validation/combat-v4-preview.png");}
  Console.WriteLine("PASS combat-v4: ranks, initiative, answers, dots, resource, interrupt, group quiz, migration, encounters, art, rendered status preview");
 }
}
