using System;using System.Linq;using System.Reflection;using System.Drawing;using System.Windows.Forms;
class SkillInspectionChecks {
 static BindingFlags Flags=BindingFlags.Instance|BindingFlags.NonPublic;
 static object Get(Game g,string name){return typeof(Game).GetField(name,Flags).GetValue(g);}
 static object Call(Game g,string name,params object[] args){return typeof(Game).GetMethod(name,Flags).Invoke(g,args);}
 static void Check(bool value,string message){if(!value)throw new Exception(message);}
 [STAThread]static void Main(){try{Application.EnableVisualStyles();using(var game=new Game()){game.Opacity=0;game.Show();Application.DoEvents();var save=new Save();typeof(Game).GetField("save",Flags).SetValue(game,save);var run=new RogueRun{id="expedition",seed=1,state="combat"};run.partyBattle=PartyCombat.Create(run,save);Call(game,"RenderPartyBattle",run);Call(game,"StopAudio");var b=run.partyBattle;var canvas=(PartyBattleCanvas)Get(game,"partyCanvas");var h=b.heroes[b.selectedHero];h.cooldowns["pull"]=2;Call(game,"RefreshPartySelection",run);
 foreach(var id in new[]{"pull","bandage"}){var button=canvas.Controls.OfType<HeroSkillButton>().Single(x=>x.Skill.Id==id);Check(button.Enabled&&!button.CanRelease,"gray yet clickable: "+id);int questions=b.questions;int hp=h.hp;button.PerformClick();Check(Object.ReferenceEquals(canvas,Get(game,"partyCanvas")),"no canvas replacement");Check(b.selectedSkill==id&&canvas.Skill.Id==id&&button.Active,"selected description");Check(canvas.Controls.OfType<VNButton>().Single(x=>x.Text=="施放技能").Enabled==false,"cast remains disabled");Check(b.phase=="heroes"&&b.questions==questions&&h.hp==hp,"inspection consumes no action");Check(canvas.Controls.OfType<OutlinedLabel>().Any(l=>l.Text.Contains(PartyCombat.Unavailable(b,h,button.Skill))),"unavailable reason shown");}
 using(var image=new Bitmap(canvas.Width,canvas.Height)){canvas.DrawToBitmap(image,canvas.ClientRectangle);image.Save("D:/WORK/Cet6Story/.validation/gray-skill-inspection.png");}game.Close();Console.WriteLine("PASS: cooldown/healing restriction skills stay dim and clickable, descriptions/reasons update, casting blocked, canvas and action unchanged");}}catch(Exception ex){while(ex!=null){Console.WriteLine(ex.GetType().Name+": "+ex.Message);ex=ex.InnerException;}Environment.ExitCode=1;}}
}
