using System;using System.Linq;using System.Reflection;using System.Windows.Forms;using System.Collections.Generic;using System.Text;using System.Runtime.InteropServices;
class StoryAmbienceChecks {
 [DllImport("winmm.dll",CharSet=CharSet.Auto)]static extern int mciSendString(string command,StringBuilder result,int size,IntPtr window);
 static BindingFlags flags=BindingFlags.Instance|BindingFlags.NonPublic;
 static object Get(Game g,string n){return typeof(Game).GetField(n,flags).GetValue(g);}static void Set(Game g,string n,object value){typeof(Game).GetField(n,flags).SetValue(g,value);}static object Call(Game g,string n,params object[] args){return typeof(Game).GetMethod(n,flags).Invoke(g,args);}
 static string Status(string name){var result=new StringBuilder(100);mciSendString("status sceneambience "+name,result,100,IntPtr.Zero);return result.ToString().Trim();}
 static void Check(bool value,string message){if(!value)throw new Exception(message);}
 [STAThread]static void Main(){Application.SetUnhandledExceptionMode(UnhandledExceptionMode.ThrowException);Application.EnableVisualStyles();using(var g=new Game()){g.Opacity=0;g.Show();Application.DoEvents();var chapter=((List<Chapter>)Get(g,"chapters")).First(c=>c.id=="tavern-01-01");var save=new Save();save.completed.Add(TavernStory.Id);save.sectionStars[TavernStory.Id]=3;Set(g,"save",save);Set(g,"current",chapter);Set(g,"index",0);var attempt=(SectionAttempt)Call(g,"Attempt");attempt.subtitlesChosen=true;attempt.introShown=true;Call(g,"ShowStory");Call(g,"UpdateStoryAmbience");Check(Status("mode")=="","first scene has no noise");Set(g,"index",10);Call(g,"UpdateLine");Call(g,"UpdateStoryAmbience");Check(Status("mode")=="","kitchen has no noise");Set(g,"index",22);Call(g,"UpdateLine");Call(g,"UpdateStoryAmbience");Check(Status("mode")=="playing","road ambience starts");Call(g,"PlayCurrent");Call(g,"TogglePlay");int before=int.Parse(Status("position"));System.Threading.Thread.Sleep(160);int after=int.Parse(Status("position"));Check(Status("mode")=="playing"&&after>before,"ambient keeps advancing while dialogue paused");Call(g,"StopAudio");Check(Status("mode")=="playing","dialogue stop leaves ambient playing");Set(g,"index",10);Call(g,"UpdateLine");Call(g,"UpdateStoryAmbience");Check((string)Get(g,"storyAmbienceScene")=="kitchen"&&Status("mode")=="","returning indoors closes road ambience");Call(g,"ShowWaystationWorldMap");Check((string)Get(g,"storyAmbienceScene")==""&&Status("mode")=="","leaving story closes ambience");g.Close();}Console.WriteLine("PASS: independent ambience, dialogue pause/stop, scene change, exit cleanup.");}
}
