using System;using System.Linq;using System.Reflection;using System.Windows.Forms;using System.Collections.Generic;
class SubtitleScoringChecks {
 static BindingFlags flags=BindingFlags.Instance|BindingFlags.NonPublic;
 static object Get(Game g,string n){return typeof(Game).GetField(n,flags).GetValue(g);}static void Set(Game g,string n,object v){typeof(Game).GetField(n,flags).SetValue(g,v);}static object Call(Game g,string n,params object[] a){return typeof(Game).GetMethod(n,flags).Invoke(g,a);}static void Check(bool v,string message){if(!v)throw new Exception(message);}
 static IEnumerable<Control> Children(Control c){foreach(Control child in c.Controls){yield return child;foreach(var x in Children(child))yield return x;}}
 [STAThread]static void Main(){try{Run();}catch(Exception e){System.IO.File.WriteAllText(System.IO.Path.Combine(AppDomain.CurrentDomain.BaseDirectory,"subtitle-error.txt"),e.GetType().FullName+" "+e.Message+(e.InnerException==null?"":" / "+e.InnerException.GetType().FullName+" "+e.InnerException.Message));throw;}}static void Run(){Check(SectionRules.Stars(2,2,true,true)==1,"bilingual one star");Check(SectionRules.Stars(2,2,true,false)==1,"Chinese one star");Check(SectionRules.Stars(2,2,false,true)==2,"English two stars");Check(SectionRules.Stars(2,2,false,false)==3,"no subtitles three stars");Check(SectionRules.Stars(1,2,false,false)==0,"wrong answer zero stars");Check(SectionRules.Stars(0,0,false,false)==0,"empty quiz zero stars");
 using(var g=new Game()){g.Opacity=0;g.Show();Application.DoEvents();var save=new Save();Set(g,"save",save);var chapter=((List<Chapter>)Get(g,"chapters")).First(WaystationChapterOne.Is);Set(g,"current",chapter);
 Console.WriteLine("Opening chooser");using(var timer=new Timer{Interval=100}){timer.Tick+=(s,e)=>{var form=Application.OpenForms.Cast<Form>().FirstOrDefault(x=>x.Text=="本节字幕与挑战模式");if(form==null)return;timer.Stop();var button=Children(form).OfType<Button>().First(x=>x.Text.StartsWith("关闭中英文字幕"));button.PerformClick();};timer.Start();Check((bool)Call(g,"ChooseSectionSubtitles"),"mode selection");}
 Console.WriteLine("Chooser selected");var attempt=save.sectionAttempts[chapter.id];Check(attempt.subtitlesChosen&&!save.chinese&&!save.english,"choice applies settings");Check((int)Call(g,"SectionStars",2,2)==3,"no subtitles grade");Set(g,"englishVisible",true);Call(g,"RecordSectionSubtitles");Set(g,"englishVisible",false);Check((int)Call(g,"SectionStars",2,2)==2,"English usage sticks after disabling");Set(g,"translating",true);Call(g,"RecordSectionSubtitles");Set(g,"translating",false);Check((int)Call(g,"SectionStars",2,2)==1,"Chinese usage sticks");var restored=Engine.Json.Deserialize<Save>(Engine.Json.Serialize(save));Check(restored.sectionAttempts[chapter.id].usedChineseSubtitles&&restored.sectionAttempts[chapter.id].usedEnglishSubtitles,"save roundtrip");attempt.review=true;Set(g,"translating",true);attempt.usedChineseSubtitles=false;Call(g,"RecordSectionSubtitles");Check(!attempt.usedChineseSubtitles,"review does not alter usage");Call(g,"ResetSection");Check(!save.sectionAttempts[chapter.id].subtitlesChosen&&!save.sectionAttempts[chapter.id].usedEnglishSubtitles,"restart resets mode and usage");save.completed.Add(TavernStory.Id);save.completed.Add(chapter.id);save.sectionStars[chapter.id]=3;save.xp=120;save.sectionAttempts[chapter.id].review=true;save.sectionAttempts[chapter.id].introShown=true;save.sectionAttempts[chapter.id].endingShown=true;using(var timer=new Timer{Interval=100}){timer.Tick+=(s,e)=>{var form=Application.OpenForms.Cast<Form>().FirstOrDefault(x=>x.Text=="本节字幕与挑战模式");if(form==null)return;timer.Stop();Children(form).OfType<Button>().First(x=>x.Text.StartsWith("关闭中英文字幕")).PerformClick();};timer.Start();Call(g,"EnterChapterOne");}Check((string)Get(g,"page")=="waystation-chapter-cg","completed chapter replays CG after chooser");Check(!save.sectionAttempts[chapter.id].review&&save.sectionAttempts[chapter.id].subtitlesChosen,"completed chapter starts fresh challenge");Check(save.xp==120&&save.sectionStars[chapter.id]==3&&save.completed.Contains(chapter.id),"restart preserves rewards and best stars");g.Close();}
 Console.WriteLine("PASS: subtitle mode selection, all star combinations, sticky usage, save persistence, review and restart.");}
}
