using System;using System.Linq;using System.Collections.Generic;
class ToxicWoodlandChecks {
 static void Check(bool b,string s){if(!b)throw new Exception(s);}
 static Save Prepared(){return new Save{heroLoadouts=new Dictionary<string,List<string>>{{"aelia",new List<string>{"slash","bleed","bash","advance","recover"}},{"luchuan",new List<string>{"bolt","inscribe","detonate","silence","bandage"}}}};}
 static int Fight(PartyCombatState b){int ticks=0;while(String.IsNullOrEmpty(b.outcome)&&ticks++<1500){if(b.phase=="heroes"){
 var h=b.heroes.First(u=>u.id==b.active);var enemy=b.enemies.Where(u=>u.hp>0).OrderBy(u=>u.maxHp).First();HeroSkill skill=null;PartyUnit target=null;
 var heal=HeroSkills.Get(h.id,h.id=="aelia"?"recover":"bandage");if(PartyCombat.CanUse(b,h,heal)){skill=heal;target=PartyCombat.Targets(b,h,heal).OrderBy(u=>u.hp/(double)u.maxHp).First();}
 if(skill==null&&b.enemies.Any(u=>u.hp>0&&u.preparation!=null)){var interrupt=HeroSkills.Get(h.id,h.id=="aelia"?"bash":"silence");if(PartyCombat.CanUse(b,h,interrupt)){target=PartyCombat.Targets(b,h,interrupt).FirstOrDefault(u=>u.preparation!=null);if(target!=null)skill=interrupt;}}
 if(skill==null&&h.id=="luchuan"){var det=HeroSkills.Get(h.id,"detonate");if(PartyCombat.CanUse(b,h,det)){skill=det;target=PartyCombat.Targets(b,h,det).OrderBy(u=>u.hp).First();}else {var mark=HeroSkills.Get(h.id,"inscribe");if(enemy.hp>35&&enemy.marks<2&&PartyCombat.CanUse(b,h,mark)){skill=mark;target=PartyCombat.Targets(b,h,mark).FirstOrDefault(u=>u.id==enemy.id);if(target==null)skill=null;}}}
 if(skill==null){skill=HeroSkills.For(h.id).Where(s=>s.Damage>0&&PartyCombat.CanUse(b,h,s)).OrderByDescending(s=>s.Id=="advance"&&h.rank>2?200:s.Id=="bleed"&&!enemy.dots.Any(d=>d.kind=="bleed")?110:s.Damage).FirstOrDefault();if(skill!=null)target=PartyCombat.Targets(b,h,skill).OrderBy(u=>u.hp).First();}
 if(skill!=null)Check(PartyCombat.BeginSkill(b,b.selectedHero,skill.Id,target.id),"tactical skill");else if(h.rank>1)PartyCombat.MoveAction(b,-1);else PartyCombat.EndHeroes(b);
 }else if(b.phase=="attack-question")PartyCombat.AttackAnswer(b,true);else if(b.phase=="defense-question")PartyCombat.DefenseAnswer(b,true);else PartyCombat.Continue(b);}
 Check(ticks<1500,"battle terminates");return ticks;}
 static void Main(){try{Run();}catch(Exception ex){Console.WriteLine(ex.Message);Environment.ExitCode=1;}}
 static void Run(){var signatures=new HashSet<string>();var species=new HashSet<string>();bool repeated=false;int wins=0;
 for(int seed=0;seed<200;seed++){var save=Prepared();var r=ToxicWoodland.Create(seed,save);Check(r.nodes.Max(n=>n.row)==9&&r.nodes.Count(n=>n.kind=="camp")==1,"ten rows and camp");foreach(var n in r.nodes.Where(n=>n.row<9))Check(r.roads.Any(e=>e.from==n.id),"no dead-end");foreach(var e in r.roads)Check(r.nodes.First(n=>n.id==e.to).row==r.nodes.First(n=>n.id==e.from).row+1,"forward-only");signatures.Add(Engine.Json.Serialize(r.roads));var json=Engine.Json.Serialize(r);Check(Engine.Json.Serialize(Engine.Json.Deserialize<ToxicWoodlandRun>(json))==json,"stable save");
 foreach(var n in r.nodes){r.current=n.id;foreach(var k in ToxicWoodland.Encounter(r,false))species.Add(k);var kinds=ToxicWoodland.Encounter(r,false);Check(kinds.Length<=3,"enemy cap");if(kinds.Distinct().Count()<kinds.Length)repeated=true;var b=PartyCombat.CreateEncounter(new RogueRun{seed=seed,partyRoster=r.party},save,kinds,1,0);Check(b.enemies.Select(u=>u.rank).Distinct().Count()==b.enemies.Count,"unique occupied cells");}
 }
 Check(signatures.Count>100&&repeated&&species.Count==6,"random roads, duplicates and five species plus boss");
 for(int seed=0;seed<10;seed++){var save=Prepared();var r=ToxicWoodland.Create(seed,save);int iterations=0;while(r.mode!="won"&&r.mode!="failed"&&iterations++<100){if(r.mode=="map"){while(r.supplies>0&&r.party.Any(h=>h.hp>0&&h.hp*100<h.maxHp*75))ToxicWoodland.Provision(r);var choices=ToxicWoodland.Available(r).OrderBy(n=>n.kind=="spring"?0:n.kind=="cache"?1:n.kind=="merchant"?2:n.kind=="scout"?3:n.kind=="event"?4:n.kind=="elite"?9:5).ThenBy(n=>r.roads.First(e=>e.from==r.current&&e.to==n.id).hazard=="ambush"?1:0).ToList();Check(ToxicWoodland.Choose(r,choices[0].id),"choose");Check(!ToxicWoodland.Choose(r,choices[0].id),"no duplicate travel");}
 else if(r.mode=="road")Check(ToxicWoodland.ResolveRoad(r,r.supplies>0),"resolve road");
 else if(r.mode=="event"){var kind=r.nodes.First(n=>n.id==r.current).kind;Check(ToxicWoodland.Event(r,kind=="camp"?(r.campUsed?"leave":"rest"):kind=="merchant"&&r.loot>=12?"buy":kind=="altar"?"power":kind=="event"&&r.supplies>0?"help":"resolve"),"event");}
 else {var combat=ToxicWoodland.StartBattle(r,save,new List<RogueEntry>());Check(Object.ReferenceEquals(combat,ToxicWoodland.StartBattle(r,save,new List<RogueEntry>())),"no refresh reroll");var snapshot=Engine.Json.Serialize(r);var restored=Engine.Json.Deserialize<ToxicWoodlandRun>(snapshot);Check(restored.combat.partyBattle.active==combat.partyBattle.active&&restored.combat.partyBattle.cursor==combat.partyBattle.cursor,"resume active action");Fight(combat.partyBattle);ToxicWoodland.FinishBattle(r);}}
 Check(iterations<100,"run terminates");if(r.mode=="won"){wins++;Check(r.path.Count==10&&r.path.Distinct().Count()==10&&r.bossReward,"exact ten visited nodes");}Console.WriteLine("seed "+seed+": "+r.mode+", nodes "+r.steps+", hp "+String.Join("/",r.party.Select(h=>h.hp)));int coins=save.rogue.coins;Check(ToxicWoodland.Claim(r,save),"claim");Check(!ToxicWoodland.Claim(r,save),"single claim");if(r.victory)Check(save.rogue.coins>coins&&save.storyFlags.Contains("toxic-woodland-purification-sample"),"boss reward");}
 Check(wins>=5,"reasonable tactical completion: "+wins+"/10");
 var bossBattle=PartyCombat.CreateEncounter(new RogueRun{seed=1},Prepared(),new[]{"boss"},1,0);var boss=bossBattle.enemies[0];Check(boss.maxHp==360&&boss.attack==28,"boss stats");boss.preparation="boss-spell";boss.marks=2;bossBattle.phase="heroes";bossBattle.active="luchuan";bossBattle.selectedHero=1;Check(PartyCombat.BeginSkill(bossBattle,1,"silence",boss.id),"silence available");PartyCombat.AttackAnswer(bossBattle,true);Check(boss.preparation==null&&boss.vulnerable==1,"interrupt exposes core");bossBattle.phase="heroes";bossBattle.active="aelia";bossBattle.selectedHero=0;bossBattle.heroes[0].skills=HeroSkills.Normalize("aelia",new[]{"bash"});boss.preparation="boss-spell";Check(PartyCombat.BeginSkill(bossBattle,0,"bash",boss.id),"boss bash");PartyCombat.AttackAnswer(bossBattle,true);Check(boss.rank==2&&boss.preparation==null,"rooted boss interrupt");
 
 var startBoss=typeof(PartyCombat).GetMethod("StartBoss",System.Reflection.BindingFlags.Static|System.Reflection.BindingFlags.NonPublic);boss.silence=0;boss.actions=2;startBoss.Invoke(null,new object[]{bossBattle,boss,bossBattle.heroes});Check(boss.preparation=="boss-spell"&&bossBattle.phase=="enemy-feedback","one-action telegraph");boss.actions=3;bossBattle.active=boss.id;startBoss.Invoke(null,new object[]{bossBattle,boss,bossBattle.heroes});Check(bossBattle.enemyGroup&&bossBattle.phase=="defense-question","charged group attack");int q=bossBattle.questions;PartyCombat.DefenseAnswer(bossBattle,true);Check(bossBattle.questions==q+1&&bossBattle.heroes.All(u=>u.dots.Any(d=>d.kind=="blight")),"one quiz and poison both");boss.hp=170;boss.actions=7;startBoss.Invoke(null,new object[]{bossBattle,boss,bossBattle.heroes});Check(boss.enraged&&boss.speed==5&&boss.attack==34&&bossBattle.enemySkill=="boss-leech","half-life rage and leech");var fresh=Prepared();fresh.toxicWoodland=ToxicWoodland.Create(-123,fresh);Check(fresh.toxicWoodland.seed>=0,"nonnegative question seed");Engine.StartNewStory(fresh,"tavern");Check(fresh.toxicWoodland==null,"new story clears expedition");
 Console.WriteLine("PASS: 200 seeded graphs, 10 complete simulations, encounter limits/duplicates, saves, interruption and idempotent rewards; wins "+wins+"/10");}
}
