using System;using System.Drawing;using System.Drawing.Drawing2D;using System.Collections.Generic;using System.Windows.Forms;
// All cards share one surface, so rotation, overlap and hit testing use the same geometry.
public sealed class BattleFanHand:Control {
 readonly List<Bitmap> cards=new List<Bitmap>();readonly List<string> descriptions=new List<string>();
 public int CardHeight=250;public int HoveredIndex{get;private set;}public int CardCount{get{return cards.Count;}}public Action<int> PlayCard;
 public BattleFanHand(){HoveredIndex=-1;SetStyle(ControlStyles.SupportsTransparentBackColor|ControlStyles.UserPaint|ControlStyles.AllPaintingInWmPaint|ControlStyles.OptimizedDoubleBuffer|ControlStyles.Selectable,true);BackColor=Color.Transparent;TabStop=true;AccessibleRole=AccessibleRole.List;ResizeRedraw=true;}
 public void AddCard(Bitmap art,string description){if(cards.Count>=8)throw new InvalidOperationException("手牌上限为 8 张。");cards.Add(art);descriptions.Add(description);Invalidate();}
 Matrix CardTransform(int index,bool raised,out float w,out float h){h=raised?Math.Min(Height-12,CardHeight*1.32f):CardHeight;w=h*2/3;float normalWidth=CardHeight*2/3f;float margin=CardHeight*.22f;float step=cards.Count<=1?0:Math.Max(0,Math.Min(normalWidth*.68f,(Width-normalWidth-margin*2)/Math.Max(1,cards.Count-1)));float offset=index-(cards.Count-1)/2f;float unit=cards.Count<=1?0:offset/Math.Max(1,(cards.Count-1)/2f);float cx=Width/2f+offset*step;float top=raised?Height-h-6:Height-CardHeight*.87f+unit*unit*Math.Min(30,CardHeight*.1f);if(raised)cx=Math.Max(w/2+4,Math.Min(Width-w/2-4,cx));var matrix=new Matrix();matrix.Translate(cx,top+h/2);matrix.Rotate(raised?0:unit*15);matrix.Translate(-w/2,-h/2);return matrix;}
 public RectangleF CardBounds(int index,bool raised){float w,h;using(var transform=CardTransform(index,raised,out w,out h)){var corners=new[]{new PointF(0,0),new PointF(w,0),new PointF(w,h),new PointF(0,h)};transform.TransformPoints(corners);float left=corners[0].X,right=left,top=corners[0].Y,bottom=top;foreach(var p in corners){left=Math.Min(left,p.X);right=Math.Max(right,p.X);top=Math.Min(top,p.Y);bottom=Math.Max(bottom,p.Y);}return RectangleF.FromLTRB(left,top,right,bottom);}}
 bool ContainsCard(int index,Point point,bool raised){float w,h;using(var transform=CardTransform(index,raised,out w,out h)){transform.Invert();var points=new[]{new PointF(point.X,point.Y)};transform.TransformPoints(points);var p=points[0];if(p.X<0||p.Y<0||p.X>=w||p.Y>=h)return false;return cards[index].GetPixel(Math.Min(511,(int)(p.X/w*512)),Math.Min(767,(int)(p.Y/h*768))).A>32;}}
 public int HitCard(Point point){if(HoveredIndex>=0&&ContainsCard(HoveredIndex,point,true))return HoveredIndex;for(int i=cards.Count-1;i>=0;i--)if(ContainsCard(i,point,false))return i;return -1;}
 void Hover(int index){if(HoveredIndex==index)return;HoveredIndex=index;Cursor=index>=0?Cursors.Hand:Cursors.Default;AccessibleName=index>=0?descriptions[index]:"手牌 · "+cards.Count+" 张";Invalidate();}
 protected override void OnMouseMove(MouseEventArgs e){base.OnMouseMove(e);Hover(HitCard(e.Location));}
 protected override void OnMouseLeave(EventArgs e){base.OnMouseLeave(e);Hover(-1);}
 protected override void OnMouseDown(MouseEventArgs e){base.OnMouseDown(e);if(e.Button!=MouseButtons.Left)return;int index=HitCard(e.Location);if(index>=0){Focus();if(PlayCard!=null)PlayCard(index);}}
 protected override bool IsInputKey(Keys keyData){return keyData==Keys.Left||keyData==Keys.Right||base.IsInputKey(keyData);}
 protected override void OnKeyDown(KeyEventArgs e){base.OnKeyDown(e);if(cards.Count==0)return;if(e.KeyCode==Keys.Left||e.KeyCode==Keys.Right){Hover(HoveredIndex<0?0:(HoveredIndex+(e.KeyCode==Keys.Right?1:cards.Count-1))%cards.Count);e.Handled=true;}else if(e.KeyCode==Keys.Enter||e.KeyCode==Keys.Space){if(HoveredIndex>=0&&PlayCard!=null)PlayCard(HoveredIndex);e.Handled=true;}}
 protected override void OnLostFocus(EventArgs e){base.OnLostFocus(e);Hover(-1);}
 protected override void OnPaint(PaintEventArgs e){base.OnPaint(e);var g=e.Graphics;g.InterpolationMode=InterpolationMode.HighQualityBicubic;g.PixelOffsetMode=PixelOffsetMode.HighQuality;g.SmoothingMode=SmoothingMode.AntiAlias;for(int i=0;i<cards.Count;i++)if(i!=HoveredIndex)Draw(g,i,false);if(HoveredIndex>=0)Draw(g,HoveredIndex,true);}
 void Draw(Graphics g,int index,bool raised){float w,h;var state=g.Save();using(var transform=CardTransform(index,raised,out w,out h)){g.MultiplyTransform(transform);using(var shadow=new SolidBrush(Color.FromArgb(raised?85:45,0,0,0)))g.FillEllipse(shadow,w*.10f,h*.85f,w*.8f,h*.11f);g.DrawImage(cards[index],new RectangleF(0,0,w,h));}g.Restore(state);}
 protected override void Dispose(bool disposing){if(disposing)foreach(var card in cards)card.Dispose();base.Dispose(disposing);}
}
