using System;
using System.Collections.Generic;
using System.Drawing;
using System.Linq;
using System.Windows.Forms;

// Scroll only our logical offset, never native child-window pixels. Every frame
// clears and redraws one buffered surface from immutable cached card images.
public sealed class CardCollectionCanvas:Control {
 readonly List<Bitmap> cards=new List<Bitmap>();readonly VScrollBar scroll=new VScrollBar();
 readonly ToolTip tips=new ToolTip();readonly List<SupportCard> definitions=new List<SupportCard>();
 readonly Font titleFont=GameTheme.Body(22,FontStyle.Bold);const int CardWidth=190,CardHeight=285,Gap=12,CardsTop=124;
 public string Description;int offset,columns=1,hover=-1,selected=-1,unlockedCount; Image atlas,frames; HashSet<string> ownedCards; Bitmap enlarged;
 public int ScrollOffset{get{return offset;}}
 public CardCollectionCanvas(){SetStyle(ControlStyles.UserPaint|ControlStyles.AllPaintingInWmPaint|ControlStyles.OptimizedDoubleBuffer|ControlStyles.ResizeRedraw|ControlStyles.Selectable,true);BackColor=GameTheme.Navy;Font=GameTheme.Body(11);TabStop=true;scroll.Visible=false;scroll.ValueChanged+=(s,e)=>{offset=scroll.Value;Invalidate();};AccessibleName="卡牌图鉴";}
 public void LoadCards(IEnumerable<SupportCard> source,IEnumerable<string> unlocked,Image atlas,Image frames){foreach(var image in cards)image.Dispose();cards.Clear();definitions.Clear();var owned=new HashSet<string>(unlocked);ownedCards=owned;this.atlas=atlas;this.frames=frames;unlockedCount=source.Count(c=>owned.Contains(c.id));foreach(var card in source.OrderBy(c=>owned.Contains(c.id)?0:1)){definitions.Add(card);using(var view=new SupportCardView{Card=card,Atlas=atlas,FrameAtlas=frames,Large=true,Playable=owned.Contains(card.id),Locked=!owned.Contains(card.id)}){var bitmap=new Bitmap(CardWidth,CardHeight);using(var g=Graphics.FromImage(bitmap)){g.Clear(GameTheme.Navy);view.DrawCard(g,CardWidth,CardHeight);}cards.Add(bitmap);}}LayoutScroll();Invalidate();}
 void LayoutScroll(){int width=Math.Max(1,ClientSize.Width);columns=Math.Max(1,(width-32+Gap)/(CardWidth+Gap));int total=CardsTop+((unlockedCount+columns-1)/columns+(cards.Count-unlockedCount+columns-1)/columns)*(CardHeight+Gap)+24;scroll.Bounds=new Rectangle(Math.Max(0,Width),0,scroll.Width,Height);scroll.Minimum=0;scroll.LargeChange=Math.Max(1,Height);scroll.SmallChange=48;scroll.Maximum=Math.Max(0,total-1);scroll.Enabled=total>Height;SetOffset(offset);}
 public void SetOffset(int value){int maximum=Math.Max(0,scroll.Maximum-scroll.LargeChange+1);offset=Math.Max(0,Math.Min(maximum,value));scroll.Value=offset;Invalidate();}
 protected override void OnResize(EventArgs e){base.OnResize(e);LayoutScroll();}
 protected override void OnMouseWheel(MouseEventArgs e){if(selected<0)SetOffset(offset-e.Delta*48/120);base.OnMouseWheel(e);}
 protected override void OnMouseDown(MouseEventArgs e){Focus();if(e.Button==MouseButtons.Left){if(selected>=0){selected=-1;enlarged.Dispose();enlarged=null;Invalidate();}else for(int i=0;i<cards.Count;i++)if(CardBounds(i).Contains(e.Location)){selected=i;using(var view=new SupportCardView{Card=definitions[i],Atlas=atlas,FrameAtlas=frames,Large=true,Playable=ownedCards.Contains(definitions[i].id),Locked=!ownedCards.Contains(definitions[i].id)}){enlarged=new Bitmap(512,768);using(var g=Graphics.FromImage(enlarged)){g.Clear(Color.Transparent);view.DrawCard(g,512,768);}}tips.SetToolTip(this,null);Invalidate();break;}}base.OnMouseDown(e);}
 protected override void OnKeyDown(KeyEventArgs e){if(e.KeyCode==Keys.Down)SetOffset(offset+48);else if(e.KeyCode==Keys.Up)SetOffset(offset-48);else if(e.KeyCode==Keys.PageDown)SetOffset(offset+Height-48);else if(e.KeyCode==Keys.PageUp)SetOffset(offset-Height+48);else if(e.KeyCode==Keys.Home)SetOffset(0);else if(e.KeyCode==Keys.End)SetOffset(int.MaxValue);else{base.OnKeyDown(e);return;}e.Handled=true;}
 Rectangle CardBounds(int index){int local=index<unlockedCount?index:index-unlockedCount;int row=index<unlockedCount?local/columns:(unlockedCount+columns-1)/columns+local/columns;return new Rectangle(16+local%columns*(CardWidth+Gap),CardsTop+row*(CardHeight+Gap)-offset,CardWidth,CardHeight);}
 protected override void OnMouseMove(MouseEventArgs e){base.OnMouseMove(e);if(selected>=0)return;int index=Enumerable.Range(0,cards.Count).FirstOrDefault(i=>CardBounds(i).Contains(e.Location));if(cards.Count==0||!CardBounds(index).Contains(e.Location))index=-1;if(index!=hover){hover=index;tips.SetToolTip(this,index<0?null:definitions[index].name+" · "+definitions[index].text);}}
 protected override void OnPaint(PaintEventArgs e){var g=e.Graphics;g.Clear(GameTheme.Navy);g.SetClip(new Rectangle(0,0,Math.Max(1,Width),Height));GameTheme.DrawText(g,"卡牌图鉴",titleFont,new Rectangle(18,16-offset,Width-50,44),GameTheme.Gold);GameTheme.DrawText(g,Description,Font,new Rectangle(18,65-offset,Width-50,52),GameTheme.Muted,TextFormatFlags.WordBreak);for(int i=0;i<cards.Count;i++){var box=CardBounds(i);if(box.Bottom>=0&&box.Top<Height)g.DrawImageUnscaled(cards[i],box.Location);}if(enlarged!=null){using(var shade=new SolidBrush(Color.FromArgb(215,0,0,0)))g.FillRectangle(shade,ClientRectangle);int h=Math.Max(1,Math.Min(768,Math.Min(Height-60,(Width-40)*3/2))),w=h*2/3;g.DrawImage(enlarged,new Rectangle((Width-w)/2,(Height-h-30)/2,w,h));GameTheme.DrawText(g,"再次点击收起",Font,new Rectangle(0,(Height+h-30)/2+8,Width,28),GameTheme.Muted,TextFormatFlags.HorizontalCenter);}}
 protected override void Dispose(bool disposing){if(disposing){scroll.Dispose();if(enlarged!=null)enlarged.Dispose();foreach(var image in cards)image.Dispose();tips.Dispose();titleFont.Dispose();}base.Dispose(disposing);}
}
