using System;using System.Collections.Generic;using System.Drawing;using System.Drawing.Drawing2D;using System.Linq;using System.Windows.Forms;
public sealed class HeroLoadoutView:Panel {
 public Save SaveData;public bool Editable;public Func<string,string,Image> SkillArt;public Func<string,Image> Portrait;public Dictionary<string,List<string>> Loadouts=new Dictionary<string,List<string>>();
 public string Hero="aelia",SkillId="slash";public string Notice="";int hover=-1;const int W=1040,H=690;
 static readonly Color Ground=Color.FromArgb(6,29,29),Card=Color.FromArgb(17,38,40),Gold=Color.FromArgb(213,177,106),Ivory=Color.FromArgb(221,219,197),Muted=Color.FromArgb(127,151,148),Blue=Color.FromArgb(71,172,197);
 public HeroLoadoutView(){DoubleBuffered=true;TabStop=true;Cursor=Cursors.Default;BackColor=Ground;AccessibleName="角色技能配置：方向键选择技能，回车装配，PageUp 或 PageDown 切换角色";}
 public void Initialize(){foreach(var id in new[]{"aelia","luchuan"}){List<string> ids=null;if(SaveData.heroLoadouts!=null)SaveData.heroLoadouts.TryGetValue(id,out ids);Loadouts[id]=HeroSkills.Normalize(id,ids);}}
 public bool Complete{get{return Loadouts.Count==2&&Loadouts.Values.All(x=>x.Count==5);}}
 public void SwitchHero(){Hero=Hero=="aelia"?"luchuan":"aelia";SkillId=HeroSkills.For(Hero)[0].Id;Notice="";Invalidate();}
 public void Choose(string id){if(HeroSkills.Get(Hero,id)!=null){SkillId=id;Notice="";Invalidate();}}
 public void Toggle(){var skill=HeroSkills.Get(Hero,SkillId);if(!Editable){Notice="战斗中仅可查看，请回到驿站调整。";}else if(!HeroSkills.Unlocked(SaveData,Hero,skill.Index)){Notice=HeroSkills.UnlockText(skill.Index);}else if(Loadouts[Hero].Contains(SkillId)){Loadouts[Hero].Remove(SkillId);Notice="已卸下，请选择一个技能补入空位。";}else if(Loadouts[Hero].Count==5){Notice="携带栏已满，点击上方携带技能先卸下一个。";}else{Loadouts[Hero].Add(SkillId);Notice="已携带 · "+Loadouts[Hero].Count+" / 5";}Invalidate();}
 float ViewScale{get{return Math.Min(Width/(float)W,Height/(float)H);}}
 Point Logical(Point p){float s=ViewScale;return new Point((int)((p.X-(Width-W*s)/2)/s),(int)((p.Y-(Height-H*s)/2)/s));}
 Rectangle SkillBox(int i){return new Rectangle(111+(i%5)*168,455+(i/5)*104,86,70);}
 Rectangle Slot(int i){return new Rectangle(511+i*88,308,70,70);}
 static Rectangle Equip=new Rectangle(511,245,420,43);
 protected override void OnMouseMove(MouseEventArgs e){base.OnMouseMove(e);var p=Logical(e.Location);int next=-1;for(int i=0;i<10;i++)if(SkillBox(i).Contains(p))next=i;bool clickable=next>=0||new Rectangle(28,159,50,75).Contains(p)||new Rectangle(414,159,50,75).Contains(p);if(Editable){clickable|=Equip.Contains(p)&&HeroSkills.Unlocked(SaveData,Hero,HeroSkills.Get(Hero,SkillId).Index);for(int i=0;i<Loadouts[Hero].Count;i++)clickable|=Slot(i).Contains(p);}Cursor=clickable?Cursors.Hand:Cursors.Default;if(next!=hover){hover=next;Invalidate();}}
 protected override void OnMouseLeave(EventArgs e){hover=-1;Cursor=Cursors.Default;Invalidate();base.OnMouseLeave(e);}
 protected override void OnMouseDown(MouseEventArgs e){base.OnMouseDown(e);Focus();var p=Logical(e.Location);if(new Rectangle(28,159,50,75).Contains(p)||new Rectangle(414,159,50,75).Contains(p)){SwitchHero();return;}for(int i=0;i<10;i++)if(SkillBox(i).Contains(p)){Choose(HeroSkills.For(Hero)[i].Id);return;}if(Equip.Contains(p)){Toggle();return;}for(int i=0;i<Loadouts[Hero].Count;i++)if(Slot(i).Contains(p)){Choose(Loadouts[Hero][i]);if(Editable)Toggle();return;}}
 protected override bool IsInputKey(Keys keyData){return keyData==Keys.Left||keyData==Keys.Right||keyData==Keys.Up||keyData==Keys.Down||base.IsInputKey(keyData);}
 protected override void OnKeyDown(KeyEventArgs e){base.OnKeyDown(e);var list=HeroSkills.For(Hero);int index=Array.FindIndex(list,s=>s.Id==SkillId);if(e.KeyCode==Keys.PageUp||e.KeyCode==Keys.PageDown)SwitchHero();else if(e.KeyCode==Keys.Enter||e.KeyCode==Keys.Space)Toggle();else if(e.KeyCode==Keys.Left||e.KeyCode==Keys.Right||e.KeyCode==Keys.Up||e.KeyCode==Keys.Down){int delta=e.KeyCode==Keys.Left?-1:e.KeyCode==Keys.Right?1:e.KeyCode==Keys.Up?-5:5;Choose(list[(index+delta+10)%10].Id);}else return;e.Handled=true;}
 void LabelText(Graphics g,string text,float size,Color color,Rectangle r,bool center=false){using(var f=GameTheme.Body(size))GameTheme.DrawText(g,text,f,r,color,TextFormatFlags.WordBreak|TextFormatFlags.NoPadding|(center?TextFormatFlags.HorizontalCenter:0));}
 void Frame(Graphics g,Rectangle r,Color color){QuestChrome.Draw(g,r,color==Gold,false,false);}
 void Icon(Graphics g,string id,Rectangle r,bool dim){var art=SkillArt==null?null:SkillArt(Hero,id);if(art!=null)g.DrawImage(art,r);if(dim)using(var b=new SolidBrush(Color.FromArgb(155,Ground)))g.FillRectangle(b,r);}
 void Ranks(Graphics g,string label,int[] ranks,int x,int y,bool own,Color colour){LabelText(g,label,10,Muted,new Rectangle(x,y,195,22));for(int i=0;i<4;i++){int rank=own?4-i:i+1;var r=new Rectangle(x+i*35,y+28,18,18);bool enabled=ranks.Contains(rank);using(var b=new SolidBrush(enabled?colour:Ground))g.FillEllipse(b,r);using(var p=new Pen(enabled?colour:Muted,2))g.DrawEllipse(p,r);LabelText(g,rank.ToString(),9,Muted,new Rectangle(x+i*35-2,y+51,23,18),true);}}
 protected override void OnPaint(PaintEventArgs e){base.OnPaint(e);if(Loadouts.Count==0)return;var g=e.Graphics;float scale=ViewScale;if(scale<=0)return;var state=g.Save();g.TranslateTransform((Width-W*scale)/2,(Height-H*scale)/2);g.ScaleTransform(scale,scale);g.InterpolationMode=InterpolationMode.NearestNeighbor;g.PixelOffsetMode=PixelOffsetMode.Half;
  LabelText(g,Hero=="aelia"?"艾莉娅":"陆川",25,Gold,new Rectangle(80,13,330,42),true);LabelText(g,Hero=="aelia"?"剑盾骑士 · 前排守护":"言契术士 · 符印共鸣",11,Muted,new Rectangle(80,57,330,25),true);
  using(var p=new Pen(Color.FromArgb(43,71,72),2)){g.DrawEllipse(p,91,94,310,270);g.DrawEllipse(p,109,110,274,239);g.DrawLine(p,481,17,481,390);}var portrait=Portrait==null?null:Portrait(Hero);if(portrait!=null){float h=296,w=h*portrait.Width/portrait.Height;g.DrawImage(portrait,new Rectangle((int)(246-w/2),87,(int)w,(int)h));}
  LabelText(g,"‹",40,Gold,new Rectangle(28,155,50,70),true);LabelText(g,"›",40,Gold,new Rectangle(414,155,50,70),true);LabelText(g,Hero=="aelia"?"被动 · 防御答对2次获得1决意":"被动 · 攻击答对2次获得1咒印",9,Gold,new Rectangle(70,391,350,35),true);
  var skill=HeroSkills.Get(Hero,SkillId);bool carried=Loadouts[Hero].Contains(SkillId),unlocked=HeroSkills.Unlocked(SaveData,Hero,skill.Index);
  Icon(g,SkillId,new Rectangle(511,20,66,66),!unlocked);LabelText(g,skill.Name,21,Gold,new Rectangle(594,25,360,38));LabelText(g,!unlocked?HeroSkills.UnlockText(skill.Index):carried?"已携带":"可装配",10,carried?Gold:Muted,new Rectangle(594,65,350,24));
  Ranks(g,"施法站位",skill.CastRanks,511,99,true,Gold);Ranks(g,skill.Target=="enemy"?"敌方目标":skill.Target=="self"?"自身位置":"友方目标",skill.TargetRanks,756,99,false,skill.Target=="enemy"?Blue:Color.FromArgb(112,178,151));
  LabelText(g,skill.Description,12,Ivory,new Rectangle(511,179,465,53));Frame(g,Equip,Editable?Gold:Muted);LabelText(g,!Editable?"战斗中仅可查看":!unlocked?"尚未解锁":carried?"卸下此技能":"携带此技能",12,Editable?Gold:Muted,new Rectangle(517,255,408,26),true);
  for(int i=0;i<5;i++){var r=Slot(i);Frame(g,r,i<Loadouts[Hero].Count?Gold:Muted);if(i<Loadouts[Hero].Count){Icon(g,Loadouts[Hero][i],Rectangle.Inflate(r,-8,-8),false);}else LabelText(g,"+",21,Muted,new Rectangle(r.X,r.Y+16,r.Width,38),true);LabelText(g,(i+1).ToString(),9,Muted,new Rectangle(r.X,r.Bottom+4,r.Width,17),true);}LabelText(g,"携带技能  "+Loadouts[Hero].Count+" / 5"+(Editable?"   ·   点击携带栏卸下":""),10,Gold,new Rectangle(511,400,465,23));
  using(var p=new Pen(Color.FromArgb(68,92,87),1))g.DrawLine(p,62,437,978,437);var skills=HeroSkills.For(Hero);for(int i=0;i<skills.Length;i++){var s=skills[i];var r=SkillBox(i);bool equipped=Loadouts[Hero].Contains(s.Id),locked=!HeroSkills.Unlocked(SaveData,Hero,s.Index);Frame(g,r,equipped?Gold:Color.FromArgb(70,97,94));Icon(g,s.Id,Rectangle.Inflate(r,-8,-8),locked);if(s.Id==SkillId||i==hover)using(var p=new Pen(Color.FromArgb(255,235,136),2))g.DrawRectangle(p,Rectangle.Inflate(r,4,4));if(equipped){using(var b=new SolidBrush(Gold))g.FillRectangle(b,r.Right-17,r.Y,17,17);LabelText(g,"✓",9,Ground,new Rectangle(r.Right-17,r.Y,17,18),true);}LabelText(g,s.Name,10,equipped?Gold:Ivory,new Rectangle(r.X-32,r.Bottom+5,150,23),true);}
  LabelText(g,Notice.Length>0?Notice:Editable?"点击图标查看技能 · 每位角色携带五个 · 关闭时保存":"点击图标查看技能 · 返回驿站后可调整配置",10,Notice.Length>0?Gold:Muted,new Rectangle(75,668,890,21),true);g.Restore(state);
 }
}
