using System;
using System.Linq;
using System.Drawing;
using System.Windows.Forms;

// New-world section support; existing chapter ids and progress remain intact.
public partial class Game {
 OutlinedLabel neonHud;
 bool questionOpen=false;
 void EnterNeon(){var chapter=chapters.FirstOrDefault(c=>c.id=="neon-01-01");if(chapter==null)return;current=chapter;index=save.positions.ContainsKey(chapter.id)?Math.Max(0,Math.Min(chapter.lines.Count-1,save.positions[chapter.id])):0;ShowStory();}
 void BuildNeonHud(){ResumeSectionTiming();if(!current.pixelArt)return;neonHud=new OutlinedLabel{PixelText=true,Text="",Font=GameTheme.Body(11),ForeColor=Color.FromArgb(216,210,255),Location=new Point(22,18),Size=new Size(700,92),BackColor=Color.Transparent};stage.Controls.Add(neonHud);stage.Resize+=(s,e)=>{if(!neonHud.IsDisposed)neonHud.Width=Math.Max(240,Math.Min(550,stage.Width-40));};}
 void UpdateNeonHud(){if(current.pixelArt&&neonHud!=null&&!neonHud.IsDisposed){int answered=current.questions.Count(q=>save.quizAnswers.ContainsKey(InlineKey(q)));neonHud.Text=current.title+"\n剧情 "+(index+1)+" / "+current.lines.Count+" · 听力 "+answered+" / "+current.questions.Count+" · "+(Attempt().review?"结束后重听 · 可开中英":Attempt().replayAfterLine>=0?"题目重听 · 可开英文":"首次听力 · 可开英文")+"\n"+TimingText();}}
 string InlineKey(QuizQuestion q){return current.id+"/q/"+q.afterLine;}
 QuizQuestion PendingInline(){return current.inlineQuestions&&!Attempt().review&&current.questions!=null?current.questions.FirstOrDefault(q=>q.afterLine==index&&!save.quizAnswers.ContainsKey(InlineKey(q))):null;}
 bool ResolveInlineQuestion(){var q=PendingInline();if(q==null)return true;if(!SegmentHeard(q)){index=SegmentFirst(q);UpdateLine();allPlaying=true;StartLine(true);SetStatus("请先完整听完这一段，可按需打开英文字幕。");return false;}if(questionOpen)return false;questionOpen=true;try{return AskInline(q);}finally{questionOpen=false;if(requestedReplay>=0){int replay=requestedReplay;requestedReplay=-1;ReplayQuestion(current.questions.First(x=>x.afterLine==replay));}}}
 Form PixelDialog(string title,int width,int height){return new PixelFrame{Text=title,Size=new Size(width,height),MinimumSize=new Size(640,480),StartPosition=FormStartPosition.CenterParent,BackColor=Color.FromArgb(14,17,33),ForeColor=TextColor,Font=Font,MinimizeBox=false,MaximizeBox=false};}
 bool AskInline(QuizQuestion q){using(var f=PixelDialog(current.title+" · 听力检查",920,650)){
  Attempt().replayAfterLine=-1;UpdateLine();string key=InlineKey(q);int number=current.questions.IndexOf(q)+1;var footer=new FlowLayoutPanel{Dock=DockStyle.Bottom,Height=62,Padding=new Padding(14,7,0,0),BackColor=Color.FromArgb(26,27,49),WrapContents=false};f.Controls.Add(footer);
  var body=new FlowLayoutPanel{Dock=DockStyle.Fill,FlowDirection=FlowDirection.TopDown,WrapContents=false,AutoScroll=true,Padding=new Padding(24,20,24,12)};f.Controls.Add(body);body.BringToFront();
  var title=Lab("听力检查  "+number+" / "+current.questions.Count+"   ·   "+q.skill,18,Accent);body.Controls.Add(title);
  var hint=Lab("全部答对且整节用时不超过 5 分钟得三星，重听也计入总用时；答案与解析在节末显示。",10,Muted);body.Controls.Add(hint);
  var prompt=Lab(q.prompt,15,TextColor);prompt.Margin=new Padding(6,18,6,16);body.Controls.Add(prompt);
  var choices=new RadioButton[4];var group=new Panel{Height=260,Margin=new Padding(6,0,6,10)};body.Controls.Add(group);
  for(int k=0;k<4;k++){choices[k]=new PixelChoice{Text=((char)('A'+k))+". "+q.options[k],ForeColor=TextColor,Font=GameTheme.Body(13),Location=new Point(8,k*64),Height=60,AutoCheck=true};group.Controls.Add(choices[k]);}
  var result=Lab("",12,Gold);body.Controls.Add(result);bool submitted=false;
  var continueButton=Btn("继续剧情",()=>{if(!submitted){result.Text="请先选择并提交答案。";return;}f.DialogResult=DialogResult.OK;f.Close();},true);
  var submit=Btn("提交答案",()=>{int selected=Array.FindIndex(choices,r=>r.Checked);if(selected<0){result.Text="请选择一个答案。";return;}if(submitted)return;save.quizAnswers[key]=selected;if(q.afterLine==current.lines.Count-1&&Attempt().finished==0)FinishSectionTiming();Persist();submitted=true;foreach(var r in choices)r.AutoCheck=false;result.Text="答案已提交。完成整节后统一查看评分、正确答案与解析。";UpdateNeonHud();},true);footer.Controls.Add(submit);footer.Controls.Add(continueButton);
  var replayButton=Btn("返回剧情重听 · 英文",()=>{requestedReplay=q.afterLine;f.DialogResult=DialogResult.Retry;f.Close();});footer.Controls.Add(replayButton);
  var countdown=Lab("",11,Gold);body.Controls.Add(countdown);var deadline=new System.Windows.Forms.Timer{Interval=200};Action updateTime=()=>{countdown.Text=TimingText();replayButton.Enabled=true;};deadline.Tick+=(s,e)=>updateTime();deadline.Start();updateTime();f.FormClosed+=(s,e)=>{deadline.Stop();deadline.Dispose();};
  Action layout=()=>{int width=Math.Max(650,body.ClientSize.Width-65);foreach(Control c in body.Controls){c.MaximumSize=new Size(width,c==group?260:0);if(c==group){c.Width=width;c.Height=260;foreach(Control option in group.Controls)option.Width=width-15;}}};body.Resize+=(s,e)=>layout();layout();f.FormClosing+=(s,e)=>{mciSendString("stop storyaudio",null,0,IntPtr.Zero);};return f.ShowDialog(this)==DialogResult.OK;
 }}
 void CompleteNeonScore(){int total=current.questions.Count;int correct=current.questions.Count(q=>save.quizAnswers.ContainsKey(InlineKey(q))&&save.quizAnswers[InlineKey(q)]==q.answer);var attempt=Attempt();if(attempt.finished==0){FinishSectionTiming();Persist();}bool timely=attempt.started>0&&SectionSeconds()<=SectionLimit();int stars=SectionRules.Stars(correct,total,timely);int best=save.sectionStars.ContainsKey(current.id)?save.sectionStars[current.id]:0;save.sectionStars[current.id]=Math.Max(best,stars);bool fresh=stars>=2&&!save.completed.Contains(current.id);if(fresh){save.completed.Add(current.id);save.xp+=60;}Persist();UpdateStats();using(var f=PixelDialog("本节评分",860,610)){var body=new FlowLayoutPanel{Dock=DockStyle.Fill,FlowDirection=FlowDirection.TopDown,WrapContents=false,Padding=new Padding(32),AutoScroll=true};f.Controls.Add(body);body.Controls.Add(Lab("本节完成",22,Accent));body.Controls.Add(Lab(new string('★',stars)+new string('☆',3-stars),32,Gold));body.Controls.Add(Lab("本次答对 "+correct+" / "+total+"   ·   最高 "+save.sectionStars[current.id]+" 星",13,Gold));body.Controls.Add(Lab(stars==1?"未全部答对：本次一星，请重玩争取两星。":stars==2?"全部答对：两星达标，可进入下一节。":"全部答对且整节限时内完成：三星！",12));body.Controls.Add(Lab(fresh?"首次两星通关 +60 XP":"重玩保留最高星级，通关经验不重复领取。",11,Muted));body.Controls.Add(Lab(TimingText(),11,Gold));var text=Lab(current.ending,12);text.MaximumSize=new Size(730,0);body.Controls.Add(text);var sequence=chapters.Where(c=>c.inlineQuestions&&!StoryRoutes.Hidden(c.id)).ToList();int pos=sequence.IndexOf(current);var next=pos>=0&&pos+1<sequence.Count?sequence[pos+1]:null;if(next!=null){var button=Btn("进入下一节",()=>{current=next;index=save.positions.ContainsKey(next.id)?save.positions[next.id]:0;f.DialogResult=DialogResult.Yes;f.Close();},true);button.Enabled=SectionRules.Unlocked(next,chapters,save);body.Controls.Add(button);}else body.Controls.Add(Lab(StoryRoutes.Hidden(current.id)?"支线行动结束，返回地图继续主线或尝试另一结局。":"本卷已完成，可返回地图复习与探索支线。",10,Muted));body.Controls.Add(Btn("返回主线地图",()=>{f.DialogResult=DialogResult.OK;f.Close();},true));body.Controls.Add(Btn("重新闯关",()=>{ResetSection();f.DialogResult=DialogResult.Retry;f.Close();}));body.Controls.Add(Btn("整节重听 · 可开中英",()=>{f.DialogResult=DialogResult.Ignore;f.Close();}));for(int i=0;i<current.questions.Count;i++){var q=current.questions[i];string key=InlineKey(q);string selected=save.quizAnswers.ContainsKey(key)?((char)('A'+save.quizAnswers[key])).ToString():"未作答";var explanation=Lab("第 "+(i+1)+" 题 · 你的答案 "+selected+" · 正确答案 "+(char)('A'+q.answer)+"\n"+q.prompt+"\n"+q.explanation,12);explanation.MaximumSize=new Size(730,0);body.Controls.Add(explanation);}var result=f.ShowDialog(this);if(result==DialogResult.OK)ShowStoryMap();else if(result==DialogResult.Yes)ShowStory();else if(result==DialogResult.Ignore){Attempt().review=true;index=0;ShowStory();ReviewSection();}else if(result==DialogResult.Retry)ShowStory();else ShowStoryMap();}}

}

public class PixelFrame:Form {
 readonly WindowGlyph close;
 public PixelFrame(){DoubleBuffered=true;FormBorderStyle=FormBorderStyle.None;BackColor=GameTheme.Navy;ForeColor=GameTheme.Ink;Font=GameTheme.Body(12);Padding=new Padding(14,58,14,14);ShowInTaskbar=false;StartPosition=FormStartPosition.CenterParent;
  close=new WindowGlyph{AccessibleName="关闭窗口"};close.Click+=(sender,e)=>Close();Controls.Add(close);Resize+=(sender,e)=>PlaceClose();PlaceClose();}
 void PlaceClose(){if(close==null)return;close.Location=new Point(Math.Max(0,ClientSize.Width-48),15);close.BringToFront();Invalidate();}
 protected override void OnShown(EventArgs e){base.OnShown(e);var area=Screen.FromControl(Owner??this).WorkingArea;MinimumSize=new Size(Math.Min(MinimumSize.Width,area.Width-24),Math.Min(MinimumSize.Height,area.Height-24));Size=new Size(Math.Min(Width,area.Width-24),Math.Min(Height,area.Height-24));PlaceClose();}
 protected override void OnPaint(PaintEventArgs e){base.OnPaint(e);GameTheme.Frame(e.Graphics,new Rectangle(3,3,ClientSize.Width-7,ClientSize.Height-7),GameTheme.Navy,GameTheme.Cyan);using(var p=new Pen(GameTheme.Violet))e.Graphics.DrawLine(p,22,49,ClientSize.Width-22,49);using(var f=GameTheme.Body(12,FontStyle.Bold))GameTheme.DrawText(e.Graphics,Text,f,new Rectangle(24,15,Math.Max(1,Width-88),30),GameTheme.Gold,TextFormatFlags.VerticalCenter|TextFormatFlags.EndEllipsis);}
 protected override void WndProc(ref Message m){if(GameTheme.HitTest(this,ref m,true,true))return;base.WndProc(ref m);}
}

public class PixelChoice:RadioButton {
 bool over;
 public PixelChoice(){SetStyle(ControlStyles.UserPaint|ControlStyles.AllPaintingInWmPaint|ControlStyles.OptimizedDoubleBuffer,true);Cursor=Cursors.Hand;BackColor=GameTheme.Navy;Font=GameTheme.Body(13);}
 protected override void OnMouseEnter(EventArgs e){over=true;Invalidate();base.OnMouseEnter(e);}
 protected override void OnMouseLeave(EventArgs e){over=false;Invalidate();base.OnMouseLeave(e);}
 protected override void OnPaint(PaintEventArgs e){e.Graphics.Clear(BackColor);GameTheme.Frame(e.Graphics,new Rectangle(2,3,Width-5,Height-7),Checked?Color.FromArgb(40,42,57):GameTheme.Card,Checked?GameTheme.Gold:over||Focused?GameTheme.Cyan:GameTheme.Violet,false);var badge=new Rectangle(14,Height/2-13,28,26);using(var b=new SolidBrush(Checked?GameTheme.Gold:GameTheme.Violet))e.Graphics.FillRectangle(b,badge);string letter=Text.Length>1?Text.Substring(0,1):"";GameTheme.DrawText(e.Graphics,letter,Font,badge,Checked?GameTheme.Navy:GameTheme.Ink,TextFormatFlags.HorizontalCenter|TextFormatFlags.VerticalCenter|TextFormatFlags.NoPadding);GameTheme.DrawText(e.Graphics,Text.Length>3?Text.Substring(3):Text,Font,new Rectangle(57,7,Math.Max(1,Width-73),Height-14),GameTheme.Ink,TextFormatFlags.WordBreak|TextFormatFlags.VerticalCenter|TextFormatFlags.NoPadding);}
 protected override void OnCheckedChanged(EventArgs e){base.OnCheckedChanged(e);Invalidate();}
}
