using System;using System.Linq;using System.Collections.Generic;
public class CombatDot {public string kind{get;set;}public string source{get;set;}public int damage{get;set;}public int turns{get;set;}}
public class PartyUnit {
 public string id{get;set;}public string name{get;set;}public string kind{get;set;}public int hp{get;set;}public int maxHp{get;set;}public int attack{get;set;}public int shield{get;set;}public int rank{get;set;}public int speed{get;set;}
 public int resolve{get;set;}public int riposte{get;set;}public int runeBoost{get;set;}public int marks{get;set;}public int markTurns{get;set;}public int bleed{get;set;}public int burn{get;set;}public int broken{get;set;}public int silence{get;set;}public int anchored{get;set;}public string guard{get;set;}public bool acted{get;set;}
 public int block{get;set;}public int dodge{get;set;}public int strength{get;set;}public int weak{get;set;}public int vulnerable{get;set;}public int slow{get;set;}public int actions{get;set;}public int specialExpiry{get;set;}public string preparation{get;set;}public string lockedTarget{get;set;}public int preparationRound{get;set;}public bool cooling{get;set;}public bool enraged{get;set;}
 public List<CombatDot> dots{get;set;}public Dictionary<string,int> expires{get;set;}public List<string> skills{get;set;}public Dictionary<string,int> cooldowns{get;set;}public Dictionary<string,int> used{get;set;}
 public PartyUnit(){dots=new List<CombatDot>();expires=new Dictionary<string,int>();skills=new List<string>();cooldowns=new Dictionary<string,int>();used=new Dictionary<string,int>();}
}
public class PartyCombatState {
 public int version{get;set;}public List<PartyUnit> heroes{get;set;}public List<PartyUnit> enemies{get;set;}public int round{get;set;}public string phase{get;set;}public int selectedHero{get;set;}public string selectedSkill{get;set;}public string target{get;set;}
 public string pendingSkill{get;set;}public string pendingHero{get;set;}public string pendingTarget{get;set;}public int enemyCursor{get;set;}public List<string> defenseTargets{get;set;}public int defenseCursor{get;set;}public int enemyDamage{get;set;}public bool enemyGroup{get;set;}public string log{get;set;}public string outcome{get;set;}public int questions{get;set;}
 public List<string> queue{get;set;}public int cursor{get;set;}public string active{get;set;}public string enemySkill{get;set;}public int randomState{get;set;}
 public PartyCombatState(){heroes=new List<PartyUnit>();enemies=new List<PartyUnit>();defenseTargets=new List<string>();queue=new List<string>();round=1;phase="heroes";log="按速度交错行动，黄色为施法站位，蓝色为目标。";}
}
public static class PartyCombat {
 public static IEnumerable<PartyUnit> All(PartyCombatState b){return b.heroes.Concat(b.enemies);}
 static PartyUnit Unit(PartyCombatState b,string id){return All(b).FirstOrDefault(u=>u.id==id);}
 public static PartyCombatState Create(RogueRun r,Save save){var b=new PartyCombatState{version=4,randomState=Math.Max(1,r.seed&0x7fffffff)};int level=Engine.Level(save.xp);b.heroes.Add(Hero("aelia","艾莉娅",100,22,1,level,save));b.heroes.Add(Hero("luchuan","陆川",75,24,3,level,save));
  if(r.partyRoster!=null)foreach(var h in b.heroes){var old=r.partyRoster.FirstOrDefault(x=>x.id==h.id);if(old!=null){h.hp=Math.Max(0,Math.Min(h.maxHp,old.hp+Math.Max(0,h.maxHp-old.maxHp)));h.rank=Math.Max(1,Math.Min(4,old.rank));}}
  if(r.partyRoster!=null&&r.partyRoster.Count>0){int recovery=Math.Max(0,r.hp-r.partyRoster.Sum(x=>x.hp));foreach(var h in b.heroes.Where(x=>x.hp>0)){int heal=Math.Min(recovery,h.maxHp-h.hp);h.hp+=heal;recovery-=heal;}}
  string monster=r.cardBattle==null?"":r.cardBattle.monster;bool tutorial=r.id=="tavern-tutorial";var kinds=tutorial?new[]{"beast"}:r.depth>=3&&r.seed%3==0?new[]{"crab","bard","cannon"}:r.seed%3==0?new[]{"crab","moth"}:r.seed%3==1?new[]{"beast","bard"}:new[]{"beast","cannon"};foreach(var k in kinds){var enemy=Monster(k,b.enemies.Count,level);if(b.enemies.Any(u=>u.rank==enemy.rank))enemy.rank=new[]{3,2,1,4}.First(rank=>!b.enemies.Any(u=>u.rank==rank));b.enemies.Add(enemy);}if(tutorial){b.enemies[0].maxHp=Math.Max(110,r.enemyMax);b.enemies[0].hp=Math.Max(1,r.enemyHp==r.enemyMax?b.enemies[0].maxHp:r.enemyHp);}BuildQueue(b);StartNext(b);return b;}
 public static PartyCombatState CreateEncounter(RogueRun run,Save save,string[] kinds,int level,int spores){var b=new PartyCombatState{version=4,randomState=Math.Max(1,run.seed&0x7fffffff)};foreach(var id in new[]{"aelia","luchuan"}){var h=Hero(id,id=="aelia"?"艾莉娅":"陆川",id=="aelia"?100:75,id=="aelia"?22:24,id=="aelia"?1:3,level,save);var old=(run.partyRoster??new List<PartyUnit>()).FirstOrDefault(u=>u.id==id);if(old!=null){h.hp=Math.Min(h.maxHp,old.hp);h.rank=Math.Max(1,Math.Min(4,old.rank));h.attack=old.attack;h.dots=old.dots.Select(d=>new CombatDot{kind=d.kind,source=d.source,damage=d.damage,turns=d.turns}).ToList();SyncDots(h);}b.heroes.Add(h);}foreach(var kind in kinds.Take(3)){var e=kind=="boss"?new PartyUnit{id="enemy-0",name="腐冠母株",kind="boss",rank=2,hp=360+(level-1)*30+spores*8,maxHp=360+(level-1)*30+spores*8,attack=28+(level-1)*2,speed=3}:Monster(kind,b.enemies.Count,level);if(kind!="boss"){e.hp=e.maxHp=e.maxHp+e.maxHp*spores*3/100;e.attack+=spores/2;if(b.enemies.Any(u=>u.rank==e.rank))e.rank=new[]{2,3,1,4}.First(rank=>!b.enemies.Any(u=>u.rank==rank));}b.enemies.Add(e);}BuildQueue(b);StartNext(b);return b;}
 static PartyUnit Hero(string id,string name,int hp,int atk,int rank,int level,Save save){List<string> load=null;if(save.heroLoadouts!=null)save.heroLoadouts.TryGetValue(id,out load);return new PartyUnit{id=id,name=name,hp=hp+(level-1)*8,maxHp=hp+(level-1)*8,attack=atk+(level-1)*2,rank=rank,speed=id=="aelia"?4:6,skills=HeroSkills.Normalize(id,load)};}
 public static PartyUnit Monster(string k,int i,int level){int hp=k=="crab"?140:k=="moth"?50:k=="bard"?60:k=="cannon"?90:110;return new PartyUnit{id="enemy-"+i,kind=k,name=k=="crab"?"苔壳搬运蟹":k=="moth"?"灯笼菌蛾":k=="bard"?"合唱伞灵":k=="cannon"?"鼓腹炮菇蟾":"荆棘孢子兽",hp=hp+(level-1)*8,maxHp=hp+(level-1)*8,attack=17+(level-1)*2,rank=k=="moth"||k=="bard"||k=="cannon"?4:1,speed=k=="moth"?7:k=="bard"?5:k=="cannon"?1:2};}
 public static void Ensure(PartyCombatState b){if(b.version==4)return;foreach(var u in All(b)){if(u.dots==null)u.dots=new List<CombatDot>();if(u.expires==null)u.expires=new Dictionary<string,int>();if(u.cooldowns==null)u.cooldowns=new Dictionary<string,int>();if(u.used==null)u.used=new Dictionary<string,int>();if(b.heroes.Contains(u)){u.skills=HeroSkills.Normalize(u.id,u.skills);u.speed=u.id=="aelia"?4:6;}else{u.kind="beast";u.name="荆棘孢子兽";u.speed=2;}if(u.bleed>0)Dot(u,"bleed","legacy",4,u.bleed);if(u.burn>0)Dot(u,"burn","legacy",4,u.burn);u.acted=false;}
  b.version=4;b.randomState=Math.Max(1,b.randomState);b.queue=new List<string>();b.defenseTargets=new List<string>();b.outcome=null;BuildQueue(b);b.log="战斗已升级：保留生命、护盾与状态，按速度重新排定当前回合。";StartNext(b);}
 static void BuildQueue(PartyCombatState b){b.queue=All(b).Where(u=>u.hp>0).OrderByDescending(u=>u.speed-(u.slow>0?2:0)).ThenBy(u=>(b.heroes.Contains(u)==(b.round%2==1))?0:1).ThenBy(u=>u.rank).Select(u=>u.id).ToList();b.cursor=0;foreach(var u in All(b)){u.acted=false;u.slow=0;}}
 public static List<PartyUnit> ActionOrder(PartyCombatState b){return (b.queue??new List<string>()).Skip(b.cursor).Select(id=>Unit(b,id)).Where(u=>u!=null&&u.hp>0).ToList();}
 public static List<PartyUnit> EnemyOrder(PartyCombatState b){return ActionOrder(b).Where(u=>b.enemies.Contains(u)).ToList();}
 static void StartNext(PartyCombatState b){Outcome(b);if(!String.IsNullOrEmpty(b.outcome)){b.phase="feedback";return;}while(b.cursor<b.queue.Count&&Unit(b,b.queue[b.cursor]).hp<=0)b.cursor++;if(b.cursor>=b.queue.Count){b.round++;BuildQueue(b);}var u=Unit(b,b.queue[b.cursor]);b.active=u.id;u.actions++;foreach(var k in u.cooldowns.Keys.ToList())u.cooldowns[k]=Math.Max(0,u.cooldowns[k]-1);int dot=u.dots.Sum(d=>d.damage);u.hp=Math.Max(0,u.hp-dot);foreach(var d in u.dots)d.turns--;u.dots.RemoveAll(d=>d.turns<=0);SyncDots(u);if(u.hp<=0){u.acted=true;b.log=u.name+"因持续伤害倒下（"+dot+"）。";Outcome(b);b.phase="enemy-feedback";return;}if(b.heroes.Contains(u)){b.selectedHero=b.heroes.IndexOf(u);b.selectedSkill=null;b.phase="heroes";b.log=u.name+"行动 · 速度"+u.speed+(dot>0?" · 持续伤害"+dot:"");}else StartEnemy(b,u);}
 static void EndAction(PartyUnit u){u.acted=true;foreach(var key in u.expires.Keys.ToList())if(u.expires[key]<=u.actions){SetToken(u,key,0);u.expires.Remove(key);}if(u.specialExpiry<=u.actions){u.guard=null;u.riposte=0;u.anchored=0;}u.markTurns=Math.Max(0,u.markTurns-1);if(u.markTurns==0)u.marks=0;u.silence=0;}
 public static void Continue(PartyCombatState b){if(!String.IsNullOrEmpty(b.outcome)||!(b.phase=="feedback"||b.phase=="enemy-feedback"))return;var u=Unit(b,b.active);if(u!=null)EndAction(u);b.defenseTargets.Clear();b.cursor++;StartNext(b);}
 public static void EndHeroes(PartyCombatState b){if(b.phase!="heroes")return;var u=Unit(b,b.active);b.log=u.name+"等待，结束本次行动。";b.phase="feedback";}
 public static bool MoveAction(PartyCombatState b,int direction){if(b.phase!="heroes")return false;var u=Unit(b,b.active);if(!Move(b.heroes,u,direction,false))return false;b.log=u.name+"移动至"+u.rank+"号位。";b.phase="feedback";return true;}
 public static string Unavailable(PartyCombatState b,PartyUnit h,HeroSkill s){if(s==null)return "技能不存在";if(b.phase!="heroes"||h.id!=b.active||h.acted||h.hp<=0)return "尚未轮到该角色";if(!h.skills.Contains(s.Id))return "未装配";if(!s.CastRanks.Contains(h.rank))return "施法位置："+String.Join("/",s.CastRanks);if(h.cooldowns.ContainsKey(s.Id)&&h.cooldowns[s.Id]>0)return "间隔剩余"+h.cooldowns[s.Id]+"次自身行动";if(s.Uses>0&&h.used.ContainsKey(s.Id)&&h.used[s.Id]>=s.Uses)return "次数已用尽";if(h.silence>0&&((h.id=="luchuan"&&s.Id!="bolt"&&s.Id!="retreat")||s.Damage==0&&s.Id!="retreat"))return "封咒：只能攻击或移动";if(s.Id=="execute"&&h.resolve<2)return "需要2决意";if(s.Id=="inspire"&&h.resolve<1)return "需要1决意";if(s.Id=="recover"&&h.hp*100>h.maxHp*40)return "生命需≤40%";if((s.Id=="advance"&&h.rank<=1)||(s.Id=="retreat"&&h.rank>=4))return "没有合法移动格";if(Targets(b,h,s).Count==0)return "没有合法目标";return "";}
 public static bool CanUse(PartyCombatState b,PartyUnit h,HeroSkill s){return Unavailable(b,h,s)=="";}
 public static List<PartyUnit> Targets(PartyCombatState b,PartyUnit h,HeroSkill s){if(s==null)return new List<PartyUnit>();var pool=s.Target=="enemy"?b.enemies:s.Target=="self"?new List<PartyUnit>{h}:b.heroes;return pool.Where(u=>u.hp>0&&s.TargetRanks.Contains(u.rank)&&(!(s.Id=="guard"||s.Id=="inspire")||u!=h)&&(s.Id!="inspire"||u.strength<2)&&(s.Id!="bandage"||u.hp*100<=u.maxHp*50)&&(s.Id!="detonate"||u.marks>=2)&&(s.Id!="silence"||u.marks>=1)).OrderBy(u=>u.rank).ToList();}
 public static bool BeginSkill(PartyCombatState b,int hero,string skill,string target){if(hero<0||hero>=b.heroes.Count)return false;var h=b.heroes[hero];var s=HeroSkills.Get(h.id,skill);if(!CanUse(b,h,s)||!Targets(b,h,s).Any(u=>u.id==target))return false;b.pendingHero=h.id;b.pendingSkill=skill;b.pendingTarget=target;b.phase="attack-question";return true;}
 public static int AddShield(PartyUnit u,int n){int old=u.shield;u.shield=Math.Min(u.maxHp*40/100,u.shield+Math.Max(0,n));return u.shield-old;}
 static void SetToken(PartyUnit u,string k,int n){switch(k){case "block":u.block=n;break;case "dodge":u.dodge=n;break;case "strength":u.strength=n;break;case "weak":u.weak=n;break;case "vulnerable":u.vulnerable=n;break;}}
 public static void Token(PartyUnit u,string k,int n){int old=k=="block"?u.block:k=="dodge"?u.dodge:k=="strength"?u.strength:k=="weak"?u.weak:u.vulnerable;SetToken(u,k,Math.Min(2,old+n));u.expires[k]=u.actions+2;}
 public static void Dot(PartyUnit u,string kind,string source,int damage,int turns){if(damage<=0||turns<=0)return;var existing=u.dots.Where(x=>x.kind==kind&&x.turns>0).ToList();int total=damage+existing.Sum(x=>x.damage);int remaining=existing.Count==0?turns:existing.Max(x=>x.turns)+1;u.dots.RemoveAll(x=>x.kind==kind);u.dots.Add(new CombatDot{kind=kind,source=source,damage=total,turns=remaining});SyncDots(u);}
 static void SyncDots(PartyUnit u){u.bleed=u.dots.Where(d=>d.kind=="bleed").Select(d=>d.turns).DefaultIfEmpty().Max();u.burn=u.dots.Where(d=>d.kind=="burn").Select(d=>d.turns).DefaultIfEmpty().Max();}
 static void Mark(PartyUnit u,int n){u.marks=Math.Min(3,u.marks+n);u.markTurns=3;}
 static bool Move(List<PartyUnit> units,PartyUnit u,int d,bool forced){int rank=u.rank+d;if(rank<1||rank>4||forced&&(u.anchored>0||u.kind=="boss"))return false;var v=units.FirstOrDefault(x=>x.hp>0&&x.rank==rank);if(forced&&v!=null&&v.anchored>0)return false;if(v!=null)v.rank=u.rank;u.rank=rank;foreach(var x in units)if(!String.IsNullOrEmpty(x.preparation)&&x.rank<3&&x.kind!="boss"){x.preparation=null;x.lockedTarget=null;}return true;}
 static bool Evade(PartyCombatState b,PartyUnit t,bool precise){if(precise||t.dodge==0)return false;t.dodge--;b.randomState=unchecked(b.randomState*1103515245+12345)&0x7fffffff;return b.randomState%100<50;}
 static PartyUnit Redirect(PartyCombatState b,PartyUnit target,bool group){if(group)return target;var side=b.heroes.Contains(target)?b.heroes:b.enemies;var guard=side.FirstOrDefault(x=>x.hp>0&&x.guard==target.id);if(guard!=null){guard.guard=null;return guard;}return target;}
 static double Power(PartyUnit actor){double m=(actor.strength>0?1.5:1)*(actor.weak>0?.5:1);if(actor.strength>0)actor.strength--;if(actor.weak>0)actor.weak--;return m;}
 static int Hit(PartyCombatState b,PartyUnit actor,PartyUnit target,int damage,List<string> log,bool reactive=false){if(target.vulnerable>0){damage=damage*3/2;target.vulnerable--;}bool blocked=target.block>0;if(blocked){damage/=2;target.block--;}int absorb=Math.Min(target.shield,damage);target.shield-=absorb;target.hp=Math.Max(0,target.hp-damage+absorb);if(target.id=="aelia"&&(blocked||absorb>0))target.resolve=Math.Min(3,target.resolve+1);log.Add(target.name+"受到"+(damage-absorb)+"伤害"+(absorb>0?"，护盾吸收"+absorb:""));if(!reactive&&target.hp>0&&target.riposte>0&&actor.hp>0){target.riposte--;if(!Evade(b,actor,false))Hit(b,target,actor,(int)(target.attack*.5*Power(target)),log,true);}return damage;}
 public static void AttackAnswer(PartyCombatState b,bool correct){if(b.phase!="attack-question")return;var h=Unit(b,b.pendingHero);var s=HeroSkills.Get(h.id,b.pendingSkill);var t=Unit(b,b.pendingTarget);var log=new List<string>{h.name+" · "+s.Name+" · "+(correct?"完整效果":"效果减半，无附加状态")};b.questions++;h.cooldowns[s.Id]=s.Cooldown==0?0:s.Cooldown+1;if(!h.used.ContainsKey(s.Id))h.used[s.Id]=0;h.used[s.Id]++;
  if(s.Damage>0){double power=Power(h);int resolve=h.resolve;var targets=s.Group?Targets(b,h,s):new List<PartyUnit>{t};foreach(var original in targets){var enemy=Redirect(b,original,s.Group);bool precise=correct&&(s.Id=="detonate"||((s.Id=="slash"||s.Id=="bolt")&&enemy.marks>0));if(correct&&s.Id=="bash")enemy.block=Math.Max(0,enemy.block-1);if(Evade(b,enemy,precise)){log.Add(enemy.name+"闪避");continue;}int percent=s.Damage;if(correct&&s.Id=="detonate"){percent+=30*enemy.marks;enemy.marks=0;}if(correct&&(s.Id=="slash"||s.Id=="bolt")&&enemy.marks>0)enemy.marks--;if(correct&&s.Id=="execute")percent+=25*resolve+(enemy.hp*100<=enemy.maxHp*30?25:0);Hit(b,h,enemy,(int)(h.attack*percent/100.0*power/(correct?1:2)),log);if(correct&&enemy.hp>0){switch(s.Id){case "bleed":Dot(enemy,"bleed",h.id+":"+s.Id,3,3);break;case "burn":Dot(enemy,"burn",h.id+":"+s.Id,3,3);break;case "wave":Mark(enemy,1);break;case "bash":if(enemy.kind=="boss"&&!String.IsNullOrEmpty(enemy.preparation))Token(enemy,"vulnerable",1);enemy.preparation=null;enemy.lockedTarget=null;if(enemy.marks>0){enemy.marks--;enemy.block=Math.Max(0,enemy.block-1);}break;case "pull":if(Move(b.enemies,enemy,-1,true)&&enemy.marks>0){enemy.marks--;Token(enemy,"vulnerable",1);}break;}}}
   if(correct){if(s.Id=="execute")h.resolve=0;if(s.Id=="advance"){Move(b.heroes,h,-1,false);if(h.resolve>0){h.resolve--;h.anchored=1;h.specialExpiry=h.actions+1;}}}
  }else if(s.Id=="recover"||s.Id=="bandage"){int heal=t.maxHp*20/100/(correct?1:2);int actual=Math.Min(t.maxHp-t.hp,heal);t.hp+=actual;log.Add(t.name+"恢复"+actual+"生命");if(correct){t.dots.RemoveAll(d=>d.kind=="bleed"||(s.Id=="recover"&&d.kind=="blight"));if(s.Id=="bandage"){var poison=t.dots.Where(d=>d.kind=="blight").OrderByDescending(d=>d.damage*d.turns).FirstOrDefault();if(poison!=null)t.dots.Remove(poison);}SyncDots(t);}}
  else if(correct){t= s.Target=="enemy"?Redirect(b,t,false):t;switch(s.Id){case "inscribe":Mark(t,2);break;case "silence":if(t.marks>0){t.marks--;t.silence=1;if(t.preparation=="spell"||t.preparation=="boss-spell"){if(t.kind=="boss")Token(t,"vulnerable",1);t.preparation=null;t.lockedTarget=null;}}break;case "guard":h.guard=t.id;Token(h,"block",1);h.specialExpiry=h.actions+1;break;case "counter":h.riposte=2;h.specialExpiry=h.actions+1;break;case "screen":Token(t,"block",1);t.weak=Math.Max(0,t.weak-1);break;case "retreat":Move(b.heroes,h,1,false);Token(h,"dodge",1);break;case "inspire":h.resolve--;Token(t,"strength",1);break;}}
  b.log=String.Join("\n",log);Outcome(b);b.phase="feedback";
 }
 static void StartEnemy(PartyCombatState b,PartyUnit e){b.enemyCursor=b.enemies.IndexOf(e);var allies=b.enemies.Where(u=>u.hp>0).ToList();var targets=b.heroes.Where(u=>u.hp>0).OrderBy(u=>u.rank).ToList();b.enemyGroup=false;b.enemySkill="";var log=new List<string>();
  if(e.kind=="boss"){StartBoss(b,e,targets);return;}
  if(e.kind=="cannon"&&e.cooling){e.cooling=false;Token(e,"vulnerable",1);b.log=e.name+"排气散热，获得易伤。";b.phase="enemy-feedback";return;}
  if(!String.IsNullOrEmpty(e.preparation)){var prep=e.preparation;e.preparation=null;if(e.rank<3||prep=="spell"&&e.silence>0){b.log=e.name+"准备被取消。";}else if(prep=="spell"){var locked=Unit(b,e.lockedTarget);if(locked==null||locked.hp<=0){b.log=e.name+"失去锁定目标，本次重新选择行动。";}else{b.enemySkill="ray";b.enemyDamage=(int)(e.attack*1.3*Power(e));targets=new List<PartyUnit>{locked};QueueDefense(b,e,targets,false);return;}}else{e.cooling=true;b.enemySkill="cannon";b.enemyDamage=(int)(e.attack*.6*Power(e));QueueDefense(b,e,targets,true);return;}}
  if(e.kind=="bard"&&e.silence==0){var target=allies.Where(u=>u!=e&&u.strength<1).OrderBy(u=>u.kind=="cannon"?0:1).FirstOrDefault();if(e.rank>=3&&target!=null&&Ready(e,"song")){Token(target,"strength",1);e.cooldowns["song"]=2;b.log=e.name+"振奋菌歌："+target.name+"获得强力。";b.phase="enemy-feedback";return;}target=allies.FirstOrDefault(u=>u.block<1);if(e.rank>=2&&target!=null&&Ready(e,"ward")){Token(target,"block",1);e.cooldowns["ward"]=2;b.log=e.name+"护根和声："+target.name+"获得格挡。";b.phase="enemy-feedback";return;}target=allies.FirstOrDefault(u=>u.weak>0||u.vulnerable>0);if(e.rank>=3&&target!=null&&Ready(e,"clean")){if(target.weak>0)target.weak--;else target.vulnerable--;e.cooldowns["clean"]=2;b.log=e.name+"清音回响：净化"+target.name; b.phase="enemy-feedback";return;}if(e.rank>2){Move(b.enemies,e,-1,false);b.log=e.name+"前移寻找攻击机会。";b.phase="enemy-feedback";return;}}
  if(e.kind=="crab"){var friend=allies.FirstOrDefault(u=>u!=e&&u.rank>=3);if(e.rank<=2&&friend!=null&&Ready(e,"guard")){e.guard=friend.id;e.specialExpiry=e.actions+1;e.cooldowns["guard"]=2;b.log=e.name+"横钳护送：守护"+friend.name; b.phase="enemy-feedback";return;}if(e.block==0&&Ready(e,"shell")){Token(e,"block",2);e.cooldowns["shell"]=3;b.log=e.name+"树桩护背：2格挡。";b.phase="enemy-feedback";return;}}
  if(e.kind=="beast"&&e.block==0&&e.actions%3==2&&e.silence==0){Token(e,"block",b.round==1?1:2);e.anchored=1;e.specialExpiry=e.actions+1;b.log=e.name+"扎根甲壳：格挡与不退。";b.phase="enemy-feedback";return;}
  if((e.kind=="moth"||e.kind=="cannon")&&e.rank>=3&&(e.kind=="cannon"||e.silence==0)&&(e.kind=="cannon"||e.actions%2==0)){e.preparation=e.kind=="moth"?"spell":"physical";e.lockedTarget=targets[0].id;e.preparationRound=b.round;b.log=e.name+(e.kind=="moth"?"灯囊聚光：锁定"+targets[0].name:"鼓腹装填：下一次行动群体炮击")+"；可打断或拉至前排。";b.phase="enemy-feedback";return;}
  if(e.kind=="moth"&&e.rank<3&&Ready(e,"retreat")){Move(b.enemies,e,1,false);Token(e,"dodge",1);e.cooldowns["retreat"]=3;b.log=e.name+"振翅后撤，获得闪避。";b.phase="enemy-feedback";return;}
  var front=targets.Where(u=>u.rank<=2).ToList();int pct=90;switch(e.kind){case "moth":b.enemySkill="brand";pct=30;break;case "cannon":b.enemySkill="spray";pct=25;targets=front;b.enemyGroup=true;break;case "crab":b.enemySkill="claw";pct=60;targets=front.Take(1).ToList();break;case "bard":b.enemySkill="root";pct=40;targets=front.Take(1).ToList();break;default:if(e.actions%3==0&&e.rank<=3){b.enemySkill="spore";pct=35;targets=front;b.enemyGroup=true;}else{b.enemySkill="bite";targets=front.Take(1).ToList();}break;}
  if(targets.Count==0||((e.kind=="crab"||e.kind=="beast"||e.kind=="bard")&&e.rank>2)){Move(b.enemies,e,-1,false);b.log=e.name+"调整站位。";b.phase="enemy-feedback";return;}if(!b.enemyGroup)targets=targets.Take(1).ToList();b.enemyDamage=(int)(e.attack*pct/100.0*Power(e));QueueDefense(b,e,targets,b.enemyGroup);
 }
 static void StartBoss(PartyCombatState b,PartyUnit e,List<PartyUnit> heroes){if(!e.enraged&&e.hp*2<=e.maxHp){e.enraged=true;e.attack+=6;e.speed=5;e.block=0;b.log="腐冠母株半血狂暴：攻击+6、下一回合速度5。破壳后不再获得格挡。";}
  if(e.preparation=="boss-spell"){e.preparation=null;if(e.silence>0){Token(e,"vulnerable",1);b.log="封咒瓦解孢潮，母株暴露核心。";b.phase="enemy-feedback";return;}b.enemySkill="boss-tide";b.enemyDamage=(int)(e.attack*(e.enraged?1.1:.9)*Power(e));QueueDefense(b,e,heroes,true);return;}
  if(e.actions%3==2&&e.silence==0){e.preparation="boss-spell";e.preparationRound=b.round;b.log="腐冠母株蓄积剧毒孢潮：下一次行动群攻并附菌毒；用盾击或符印封咒打断。巨根扎地，无法强制移动。";b.phase="enemy-feedback";return;}
  if(e.actions%3==0&&e.block==0&&!e.enraged){Token(e,"block",1);b.log="母株收拢菌冠获得1格挡，暂缓攻势。";b.phase="enemy-feedback";return;}
  b.enemySkill=e.enraged&&e.actions%2==1?"boss-leech":"boss-root";b.enemyDamage=(int)(e.attack*(b.enemySkill=="boss-leech"?.7:.85)*Power(e));var target=b.enemySkill=="boss-leech"?heroes.OrderBy(h=>h.hp).First():heroes.OrderBy(h=>h.rank).First();QueueDefense(b,e,new List<PartyUnit>{target},false);
 }
 static bool Ready(PartyUnit u,string k){return !u.cooldowns.ContainsKey(k)||u.cooldowns[k]==0;}
 public static string EnemyActionName(string key){switch(key){case "boss-tide":return "剧毒孢潮";case "boss-root":return "穿心根刺";case "boss-leech":return "腐根汲取";case "bite":return "棘牙撕咬";case "spore":return "孢囊破裂";case "brand":return "萤孢烙印";case "ray":return "腐光射线";case "cannon":return "孢弹齐射";case "spray":return "近身喷菌";case "claw":return "碎石钳击";case "root":return "根须抽击";default:return "行动";}}
 static void QueueDefense(PartyCombatState b,PartyUnit e,List<PartyUnit> targets,bool group){b.enemyGroup=group;b.defenseTargets=targets.Select(u=>Redirect(b,u,group).id).ToList();b.defenseCursor=0;b.phase="defense-question";b.log=e.name+" · "+EnemyActionName(b.enemySkill)+" · "+b.enemyDamage+"伤害";}
 public static void DefenseAnswer(PartyCombatState b,bool correct){if(b.phase!="defense-question")return;var e=Unit(b,b.active);var log=new List<string>{e.name+"攻击 · "+(correct?"答对，全部目标直伤减半":"答错，完整伤害")};b.questions++;bool resolveGained=false;var counters=new List<PartyUnit>();foreach(var id in b.defenseTargets){var t=Unit(b,id);if(t.hp<=0||e.hp<=0)continue;if(Evade(b,t,false)){log.Add(t.name+"闪避");continue;}int before=t.resolve;Hit(b,e,t,b.enemyDamage/(correct?2:1),log,b.enemyGroup);if(b.enemyGroup&&t.hp>0&&t.riposte>0)counters.Add(t);if(before<t.resolve&&resolveGained)t.resolve=before;if(t.resolve>before)resolveGained=true;if(t.hp>0){switch(b.enemySkill){case "boss-tide":Dot(t,"blight",e.id+":tide",e.enraged?3:2,2);break;case "boss-root":Move(b.heroes,t,1,true);Dot(t,"bleed",e.id+":root",2,2);break;case "boss-leech":e.hp=Math.Min(e.maxHp,e.hp+6);Token(t,"weak",1);break;case "bite":Dot(t,"bleed",e.id+":bite",2,2);break;case "spore":Dot(t,"blight",e.id+":spore",2,2);break;case "spray":Dot(t,"blight",e.id+":spray",1,2);break;case "ray":Dot(t,"burn",e.id+":ray",3,2);break;case "brand":Token(t,"vulnerable",1);break;case "claw":Token(t,"weak",1);break;}}}foreach(var counter in counters){if(e.hp<=0)break;counter.riposte--;if(!Evade(b,e,false))Hit(b,counter,e,(int)(counter.attack*.5*Power(counter)),log,true);}b.log=String.Join("\n",log);Outcome(b);b.phase="feedback";}
 static void Outcome(PartyCombatState b){if(b.enemies.All(u=>u.hp<=0))b.outcome="won";else if(b.heroes.All(u=>u.hp<=0))b.outcome="lost";}
 public static void Sync(RogueRun r){var b=r.partyBattle;r.hp=b.heroes.Sum(u=>u.hp);r.maxHp=b.heroes.Sum(u=>u.maxHp);r.enemyHp=b.enemies.Sum(u=>u.hp);r.enemyMax=b.enemies.Sum(u=>u.maxHp);r.feedback=b.log;r.state=String.IsNullOrEmpty(b.outcome)?"combat":b.outcome;r.won=b.outcome=="won";}
}
