using System;using System.Drawing;using System.Drawing.Drawing2D;using System.IO;using System.Windows.Forms;
public partial class Game {
 void AddPreparationHotspot(Control scene,string title,Action action,float x,float y){var button=ShowcaseButton(title,action,180,56);button.GuildStyle=true;button.LibraryStyle=true;AddWoodMenuHover(button);scene.Controls.Add(button);Action layout=()=>{int w=Math.Max(130,Math.Min(200,scene.Width/8)),h=Math.Max(42,Math.Min(62,scene.Height/12));button.Size=new Size(w,h);SetPreparationButtonFont(button,scene);button.Location=new Point(Math.Max(12,Math.Min(scene.Width-w-12,(int)(scene.Width*x)-w/2)),Math.Max(12,Math.Min(scene.Height-h-12,(int)(scene.Height*y)-h/2)));};scene.Resize+=(s,e)=>layout();layout();}
 void ShowPreparationKitchen(){ClearPage();page="tavern-preparation-kitchen";var scene=new CardRewardSurface{Dock=DockStyle.Fill,Art=CachedImage(Path.Combine(root,"assets/waystation/kitchen-ingredient-ledger.png")),PixelArt=true,CompositeChildren=true};content.Controls.Add(scene);AddPreparationHotspot(scene,"返回营业准备",ShowTavernPreparation,.10f,.07f);AddPreparationHotspot(scene,"查看食材",ShowPreparationIngredients,.48f,.43f);}
 void ShowPreparationIngredients(){ClearPage();page="tavern-ingredients";var view=new IngredientLedgerView{Dock=DockStyle.Fill};content.Controls.Add(view);var back=ShowcaseButton("返回厨房",ShowPreparationKitchen,170,48);back.GuildStyle=true;back.LibraryStyle=true;view.Controls.Add(back);Action layout=()=>{back.Location=new Point(Math.Max(16,view.Width-back.Width-26),20);};view.Resize+=(s,e)=>layout();layout();view.Focus();}
 void ShowPreparationMenu(){ClearPage();page="tavern-menu";if(save.todayRecipes==null)save.todayRecipes=new System.Collections.Generic.List<int>{0,1,2,3};var view=new RecipeMenuView(root,save.todayRecipes,()=>Persist()){Dock=DockStyle.Fill};content.Controls.Add(view);var back=ShowcaseButton("返回营业准备",ShowTavernPreparation,180,48);back.GuildStyle=true;back.LibraryStyle=true;view.Controls.Add(back);Action layout=()=>back.Location=new Point(Math.Max(16,view.Width-206),20);view.Resize+=(s,e)=>layout();layout();}

}
public sealed class IngredientLedgerView:Control {
 readonly string[] names=FoodCatalog.Names;
 sealed class HoverItem {public Rectangle Area;public string Title,Description;public HoverItem(Rectangle area,string title,string description){Area=area;Title=title;Description=description;}}
 readonly System.Collections.Generic.List<HoverItem> hoverItems=new System.Collections.Generic.List<HoverItem>();HoverItem hovered;Point hoverPoint;
 protected override void OnMouseMove(MouseEventArgs e){base.OnMouseMove(e);HoverItem next=null;foreach(var item in hoverItems)if(item.Area.Contains(e.Location)){next=item;break;}hovered=next;hoverPoint=e.Location;Cursor=next==null?Cursors.Default:Cursors.Help;Invalidate();}
 protected override void OnMouseLeave(EventArgs e){base.OnMouseLeave(e);hovered=null;Cursor=Cursors.Default;Invalidate();}
 void AddHover(Rectangle area,string title,string description){if(area.Width>0&&area.Height>0)hoverItems.Add(new HoverItem(area,title,description));}
 void DrawHover(Graphics g){if(hovered==null)return;int w=Math.Min(320,Width-32);int h=132;int x=Math.Max(12,Math.Min(Width-w-12,hoverPoint.X+18));int y=hoverPoint.Y-h-16;if(y<12)y=Math.Min(Height-h-12,hoverPoint.Y+20);var r=new Rectangle(x,y,w,h);Frame(g,r,Color.FromArgb(10,25,28));DrawLabel(g,hovered.Title,new Rectangle(x+14,y+12,w-28,32),14,GuildChrome.Gold);DrawLabel(g,hovered.Description,new Rectangle(x+14,y+49,w-28,h-60),11,GuildChrome.Ivory);}
 int selected,offset;Rectangle list;int cellW,cellH=100,columns=3;
 public int SelectedIndex{get{return selected;}}public int ScrollOffset{get{return offset;}}
 public IngredientLedgerView(){DoubleBuffered=true;ResizeRedraw=true;TabStop=true;BackColor=Color.FromArgb(13,29,32);MouseEnter+=(s,e)=>Focus();}
 int ContentHeight{get{return ((names.Length+columns-1)/columns)*cellH;}}
 void Geometry(){list=new Rectangle(28,102,Math.Max(220,(int)(Width*.43)-40),Math.Max(100,Height-134));columns=Width<900?2:3;cellW=list.Width/columns;cellH=Math.Max(90,Math.Min(120,Height/6));offset=Math.Max(0,Math.Min(offset,Math.Max(0,ContentHeight-list.Height)));}
 protected override void OnMouseWheel(MouseEventArgs e){base.OnMouseWheel(e);Geometry();if(list.Contains(e.Location)){offset=Math.Max(0,Math.Min(Math.Max(0,ContentHeight-list.Height),offset-e.Delta/120*cellH));Invalidate();}}
 protected override void OnKeyDown(KeyEventArgs e){base.OnKeyDown(e);Geometry();if(e.KeyCode==Keys.Down||e.KeyCode==Keys.Up||e.KeyCode==Keys.PageDown||e.KeyCode==Keys.PageUp){offset=Math.Max(0,Math.Min(Math.Max(0,ContentHeight-list.Height),offset+(e.KeyCode==Keys.Up||e.KeyCode==Keys.PageUp?-1:1)*(e.KeyCode==Keys.PageDown||e.KeyCode==Keys.PageUp?list.Height:cellH)));e.Handled=true;Invalidate();}}
 protected override void OnMouseDown(MouseEventArgs e){base.OnMouseDown(e);Focus();Geometry();if(list.Contains(e.Location)){int i=((e.Y-list.Y+offset)/cellH)*columns+(e.X-list.X)/cellW;if(i>=0&&i<names.Length){selected=i;hovered=null;Invalidate();}}}
 void DrawLabel(Graphics g,string text,Rectangle r,float size,Color color){using(var font=GameTheme.Body(size))GameTheme.DrawText(g,text,font,r,color,TextFormatFlags.WordBreak|TextFormatFlags.NoPadding|TextFormatFlags.PreserveGraphicsClipping);}
 void Frame(Graphics g,Rectangle r,Color fill){using(var brush=new SolidBrush(fill))g.FillRectangle(brush,r);using(var pen=new Pen(GuildChrome.Gold,2))g.DrawRectangle(pen,r);}
 public static void Egg(Graphics g,Rectangle area){string[] mask={"0000011100000","0000133310000","0001333331000","0013333333100","0013344333100","0133444433310","0133444333310","1333443333331","1333333333331","1333333333321","1333333333221","0133333332210","0013333322100","0001222210000","0000111100000"};int px=Math.Max(1,Math.Min(area.Width/13,area.Height/15));int x=area.X+(area.Width-13*px)/2,y=area.Y+(area.Height-15*px)/2;Color[] colors={Color.Transparent,Color.FromArgb(87,64,44),Color.FromArgb(186,153,103),Color.FromArgb(238,220,174),Color.FromArgb(255,246,216)};for(int row=0;row<mask.Length;row++)for(int col=0;col<13;col++){int v=mask[row][col]-'0';if(v>0)using(var b=new SolidBrush(colors[v]))g.FillRectangle(b,x+col*px,y+row*px,px,px);}}
 void DrawRelatedRecipes(Graphics g,Rectangle detail,int top,Color ink){
 var related=FoodCatalog.RelatedRecipes(selected);int remaining=detail.Bottom-top-16;
 DrawLabel(g,"可制作菜品",new Rectangle(detail.X+26,top,detail.Width-52,28),15,ink);
 if(related.Count==0){DrawLabel(g,"暂无使用该食材的已收录菜谱",new Rectangle(detail.X+26,top+34,detail.Width-52,48),11,ink);return;}
 int h=Math.Min(96,Math.Max(28,(remaining-34)/related.Count));int width=detail.Width-52;
 var state=g.Save();g.SetClip(new Rectangle(detail.X+18,top+32,detail.Width-36,Math.Max(1,detail.Bottom-top-44)));
 for(int n=0;n<related.Count;n++){
 int recipe=related[n];var r=new Rectangle(detail.X+26,top+34+n*h,width,h-6);
 int leftWidth=Math.Max(130,width*48/100);Frame(g,r,Color.FromArgb(18,38,40));var dishArea=new Rectangle(r.X,r.Y,leftWidth,r.Height);AddHover(dishArea,FoodCatalog.Recipes[recipe],FoodCatalog.Notes[recipe]);using(var pen=new Pen(Color.FromArgb(95,110,88)))g.DrawLine(pen,r.X+leftWidth,r.Y+10,r.X+leftWidth,r.Bottom-10);
 int icon=Math.Min(68,r.Height-8);FoodCatalog.Icon(g,24+recipe,new Rectangle(r.X+4,r.Y+4,icon,icon));DrawLabel(g,FoodCatalog.Recipes[recipe],new Rectangle(r.X+icon+10,r.Y+Math.Max(4,(r.Height-38)/2),leftWidth-icon-16,40),11,GuildChrome.Ivory);
 var materials=new System.Collections.Generic.List<int>();foreach(string part in FoodCatalog.Needs[recipe].Split('·')){int i=Array.IndexOf(FoodCatalog.Names,part.Trim());if(i>=0&&i!=selected)materials.Add(i);}
 int available=width-leftWidth-12;int step=materials.Count==0?available:available/materials.Count;int size=Math.Min(64,Math.Min(step-4,r.Height-8));
 for(int m=0;m<materials.Count;m++){int i=materials[m];var area=new Rectangle(r.X+leftWidth+12+m*step,r.Y+4,step-4,r.Height-8);FoodCatalog.Icon(g,i,new Rectangle(area.X+(area.Width-size)/2,r.Y+(r.Height-size)/2,size,size));AddHover(area,FoodCatalog.Names[i],FoodCatalog.Descriptions[i]);}
 }
 g.Restore(state);
 }
 protected override void OnPaint(PaintEventArgs e){base.OnPaint(e);Geometry();hoverItems.Clear();var g=e.Graphics;g.SmoothingMode=SmoothingMode.None;DrawLabel(g,"食材账本",new Rectangle(30,26,350,42),23,GuildChrome.Gold);DrawLabel(g,"库存列表 · 滚轮向下查看",new Rectangle(30,72,list.Width,24),11,GuildChrome.Ivory);var state=g.Save();g.SetClip(list);for(int i=0;i<names.Length;i++){var r=new Rectangle(list.X+i%columns*cellW+4,list.Y+i/columns*cellH-offset+4,cellW-8,cellH-8);AddHover(Rectangle.Intersect(r,list),names[i],FoodCatalog.Descriptions[i]);Frame(g,r,i==selected?Color.FromArgb(61,85,68):Color.FromArgb(28,52,53));FoodCatalog.Icon(g,i,new Rectangle(r.X+8,r.Y+10,Math.Min(64,r.Width/3),r.Height-20));DrawLabel(g,names[i],new Rectangle(r.X+r.Width/3+9,r.Y+15,r.Width*2/3-14,26),12,GuildChrome.Ivory);DrawLabel(g,"数量 0",new Rectangle(r.X+r.Width/3+9,r.Y+47,r.Width*2/3-14,24),10,GuildChrome.Gold);}g.Restore(state);int max=Math.Max(1,ContentHeight-list.Height);int thumb=Math.Max(26,list.Height*list.Height/ContentHeight);using(var b=new SolidBrush(GuildChrome.Gold))g.FillRectangle(b,list.Right+5,list.Y+(list.Height-thumb)*offset/max,5,thumb);var detail=new Rectangle(list.Right+30,102,Math.Max(120,Width-list.Right-58),Height-134);Frame(g,detail,Color.FromArgb(223,203,157));var ink=Color.FromArgb(66,48,34);DrawLabel(g,names[selected],new Rectangle(detail.X+26,detail.Y+22,detail.Width-52,45),24,ink);bool compact=detail.Height<500;int imageH=compact?60:Math.Min(170,detail.Height/4);FoodCatalog.Icon(g,selected,new Rectangle(detail.X+26,detail.Y+70,detail.Width-52,imageH));int y=detail.Y+imageH+76;DrawLabel(g,"当前库存：0",new Rectangle(detail.X+26,y,detail.Width-52,30),16,ink);DrawLabel(g,"获得场所：城镇集市",new Rectangle(detail.X+26,y+(compact?30:44),detail.Width-52,30),13,ink);DrawLabel(g,FoodCatalog.Descriptions[selected],new Rectangle(detail.X+26,y+(compact?65:93),detail.Width-52,compact?52:80),13,ink);DrawRelatedRecipes(g,detail,y+(compact?126:185),ink);DrawHover(g);}
}
