using System;using System.Diagnostics;using System.Drawing;using System.Drawing.Drawing2D;using System.IO;using System.Media;using System.Windows.Forms;

public sealed class PrologueCurtain:Control {
 readonly Timer timer=new Timer{Interval=20};readonly Stopwatch clock=new Stopwatch();
 Bitmap opening,backdrop;SoundPlayer sound;MemoryStream audio;bool finished;
 public Image Morning;public bool Chinese,English;public int Volume;public Action Completed;
 public PrologueCurtain(){SetStyle(ControlStyles.UserPaint|ControlStyles.AllPaintingInWmPaint|ControlStyles.OptimizedDoubleBuffer|ControlStyles.Opaque,true);}
 public void CaptureScene(Control source){opening=new Bitmap(Math.Max(1,source.Width),Math.Max(1,source.Height));source.DrawToBitmap(opening,new Rectangle(Point.Empty,opening.Size));}
 public void Start(){PrepareBackdrop();audio=MorningAudio(Volume);sound=new SoundPlayer(audio);try{sound.Play();}catch{}timer.Tick+=(s,e)=>{if(clock.ElapsedMilliseconds>=5200){if(finished)return;finished=true;timer.Stop();var done=Completed;if(done!=null)done();}else Invalidate();};clock.Start();timer.Start();}
 void PrepareBackdrop(){if(Width<1||Height<1||Morning==null)return;if(backdrop!=null)backdrop.Dispose();backdrop=new Bitmap(Width,Height);using(var g=Graphics.FromImage(backdrop)){g.InterpolationMode=InterpolationMode.NearestNeighbor;float k=Math.Max(Width/(float)Morning.Width,Height/(float)Morning.Height);g.DrawImage(Morning,(Width-Morning.Width*k)/2,(Height-Morning.Height*k)/2,Morning.Width*k,Morning.Height*k);}}
 protected override void OnResize(EventArgs e){base.OnResize(e);PrepareBackdrop();}
 protected override void OnPaint(PaintEventArgs e){var g=e.Graphics;double t=clock.Elapsed.TotalMilliseconds;if(backdrop!=null)g.DrawImageUnscaled(backdrop,0,0);else g.Clear(Color.Black);
  if(opening!=null&&t<900){using(var attrs=new System.Drawing.Imaging.ImageAttributes()){var matrix=new System.Drawing.Imaging.ColorMatrix();matrix.Matrix33=(float)Math.Max(0,1-t/900);attrs.SetColorMatrix(matrix);g.DrawImage(opening,ClientRectangle,0,0,opening.Width,opening.Height,GraphicsUnit.Pixel,attrs);}}
  float opacity=(float)Math.Min(1,Math.Max(0,(t-2300)/600));if(opacity>0&&(Chinese||English)){float scale=Math.Min(Width/1280f,Height/720f);int y=(int)(Height*.72);using(var font=GameTheme.Body(Math.Max(15,30*scale)))using(var latin=GameTheme.Latin(Math.Max(12,20*scale)))using(var format=new StringFormat{Alignment=StringAlignment.Center,LineAlignment=StringAlignment.Center})using(var ink=new SolidBrush(Color.FromArgb((int)(255*opacity),244,215,146)))using(var shadow=new SolidBrush(Color.FromArgb((int)(180*opacity),0,0,0))){if(Chinese){var r=new RectangleF(20,y,Width-40,60*scale);g.DrawString("第一盏灯，终于亮了。",font,shadow,new RectangleF(r.X+2,r.Y+2,r.Width,r.Height),format);g.DrawString("第一盏灯，终于亮了。",font,ink,r,format);y+=(int)(60*scale);}if(English){var r=new RectangleF(20,y,Width-40,48*scale);g.DrawString("At last, the first light shines.",latin,shadow,new RectangleF(r.X+2,r.Y+2,r.Width,r.Height),format);g.DrawString("At last, the first light shines.",latin,ink,r,format);}}}
  if(t>4500)using(var black=new SolidBrush(Color.FromArgb((int)(255*Math.Min(1,(t-4500)/700)),Color.Black)))g.FillRectangle(black,ClientRectangle);
 }
 static MemoryStream MorningAudio(int volume){const int rate=22050;var stream=new MemoryStream();using(var w=new BinaryWriter(stream,System.Text.Encoding.UTF8,true)){int count=rate*6;w.Write(System.Text.Encoding.ASCII.GetBytes("RIFF"));w.Write(36+count*2);w.Write(System.Text.Encoding.ASCII.GetBytes("WAVEfmt "));w.Write(16);w.Write((short)1);w.Write((short)1);w.Write(rate);w.Write(rate*2);w.Write((short)2);w.Write((short)16);w.Write(System.Text.Encoding.ASCII.GetBytes("data"));w.Write(count*2);var random=new Random(73);for(int i=0;i<count;i++){double t=i/(double)rate,fade=Math.Min(1,t/.4)*Math.Min(1,Math.Max(0,(5.8-t)/.8));double v=.04*(Math.Sin(t*2*Math.PI*261.63)+.65*Math.Sin(t*2*Math.PI*329.63)+.5*Math.Sin(t*2*Math.PI*392));v+=(random.NextDouble()-.5)*.014;foreach(double at in new[]{1.1,1.45,2.1}){double d=t-at;if(d>=0&&d<.18)v+=.035*Math.Sin(2*Math.PI*(1900*d+1700*d*d))*Math.Sin(Math.PI*d/.18);}double ch=t-4.65;if(ch>=0)v+=.09*Math.Exp(-ch*4)*(Math.Sin(ch*2*Math.PI*784)+.4*Math.Sin(ch*2*Math.PI*1176));w.Write((short)(Math.Max(-1,Math.Min(1,v*fade))*32767*Math.Max(0,Math.Min(100,volume))/100));}}stream.Position=0;return stream;}
 protected override void Dispose(bool disposing){if(disposing){timer.Dispose();if(sound!=null){sound.Stop();sound.Dispose();}if(audio!=null)audio.Dispose();if(opening!=null)opening.Dispose();if(backdrop!=null)backdrop.Dispose();}base.Dispose(disposing);}
}
public partial class Game {
 void ShowTavernCurtain(){
  if(page=="tavern-curtain")return;
  var curtain=new PrologueCurtain{Dock=DockStyle.Fill,Morning=CachedImage(Path.Combine(root,"chapters","art","tavern","waystation-repair-morning.png")),Chinese=translating&&ChineseAllowed(),English=englishVisible&&SubtitleAllowed(),Volume=EffectSoundVolume()};
  content.PerformLayout();curtain.CaptureScene(content);PauseSectionTiming();page="tavern-curtain";content.Controls.Add(curtain);curtain.BringToFront();curtain.Completed=()=>{if(page!="tavern-curtain"||IsDisposed)return;CompleteTavern();var reveal=new WhiteSceneReveal{Dock=DockStyle.Fill,FadeColor=Color.Black,DurationMs=650};content.PerformLayout();reveal.CaptureScene(content);content.Controls.Add(reveal);reveal.BringToFront();reveal.Start();};curtain.Start();
 }
}
