using System;using System.Drawing;using System.Drawing.Drawing2D;
public static class QuestChrome {
 public static void Draw(Graphics g,Rectangle bounds,bool active,bool complete,bool ornate,bool unlocked=false){
  g.SmoothingMode=SmoothingMode.None;var r=Rectangle.Inflate(bounds,ornate?-8:-4,ornate?-8:-4);if(r.Width<24||r.Height<24)return;int cut=ornate?18:10;
  using(var fill=new SolidBrush(Color.FromArgb(6,29,29)))g.FillPolygon(fill,GameTheme.Outline(r,cut));
  if(unlocked){var state=g.Save();using(var path=new GraphicsPath()){path.AddPolygon(GameTheme.Outline(Rectangle.Inflate(r,-3,-3),cut-2));g.SetClip(path);using(var gradient=new LinearGradientBrush(r,Color.FromArgb(7,49,39),Color.FromArgb(17,84,49),LinearGradientMode.Horizontal))g.FillRectangle(gradient,r);for(int y=r.Top+4;y<r.Bottom;y+=6)for(int x=r.Left+4;x<r.Right;x+=6){int noise=((x/6)*31+(y/6)*17+((x/18)*(y/18))*7)%29;if(noise<9){int edge=Math.Min(x-r.Left,r.Right-x);int alpha=edge<r.Width/4?26:9;using(var ink=new SolidBrush(Color.FromArgb(alpha,noise<4?Color.FromArgb(57,129,70):Color.FromArgb(0,27,28))))g.FillRectangle(ink,x,y,6+(noise%3)*6,6+(noise%2)*6);}}}g.Restore(state);}
  using(var dark=new Pen(Color.FromArgb(117,75,22),5))g.DrawPolygon(dark,GameTheme.Outline(r,cut));using(var gold=new Pen(Color.FromArgb(245,188,42),2))g.DrawPolygon(gold,GameTheme.Outline(r,cut));var inner=Rectangle.Inflate(r,-5,-5);using(var light=new Pen(active||complete?Color.FromArgb(255,237,126):Color.FromArgb(187,139,39),1))g.DrawPolygon(light,GameTheme.Outline(inner,Math.Max(3,cut-4)));
  if(active)using(var light=new Pen(Color.FromArgb(255,244,159),2))g.DrawPolygon(light,GameTheme.Outline(Rectangle.Inflate(r,-2,-2),cut-1));
  foreach(bool right in new[]{false,true})foreach(bool bottom in new[]{false,true}){int x=right?r.Right:r.Left,y=bottom?r.Bottom:r.Top;int sx=right?-1:1,sy=bottom?-1:1;using(var pen=new Pen(Color.FromArgb(255,213,67),2)){if(ornate){g.DrawLines(pen,new[]{new Point(x+sx*2,y+sy*24),new Point(x+sx*2,y+sy*9),new Point(x+sx*10,y+sy*9),new Point(x+sx*10,y+sy*2),new Point(x+sx*24,y+sy*2)});g.DrawLines(pen,new[]{new Point(x+sx*18,y+sy*9),new Point(x+sx*18,y+sy*18),new Point(x+sx*9,y+sy*18),new Point(x+sx*9,y+sy*14),new Point(x+sx*14,y+sy*14)});}else{g.DrawLines(pen,new[]{new Point(x+sx*3,y+sy*16),new Point(x+sx*3,y+sy*7),new Point(x+sx*7,y+sy*7),new Point(x+sx*7,y+sy*3),new Point(x+sx*16,y+sy*3)});}}}
 }
}
