using System;using System.Drawing;using System.Drawing.Drawing2D;using System.IO;using System.Collections.Generic;using System.Windows.Forms;
public static class FoodCatalog {
 public static readonly string[] Names={"鸡蛋","小麦粉","燕麦","大麦","黑麦","鸡肉","猪肉","羊肉","兔肉","洋葱","胡萝卜","卷心菜","豌豆","蘑菇","芜菁","牛奶","黄油","奶酪","盐","蜂蜜","蒜","百里香","苹果","梨"};
 public static readonly string[] Descriptions={"农庄送来的新鲜鸡蛋。可用黄油煎熟，也可拌入面团。","磨坊磨出的细麦粉。适合烘烤面包，也能让浓汤更稠。","质朴耐储存的谷物。慢煮后柔软绵密，适合早餐粥。","旅人常吃的谷物。加入洋葱汤中，能让一碗热汤更加管饱。","颜色深、麦香浓的谷物。烤出的面包结实，适合蘸炖汤。","肉质细嫩，搭配蒜和香草在石炉中烤制。","肥瘦相间的猪肉。慢炖后为豌豆和蔬菜带来浓厚滋味。","味道浓郁的羊肉。适合与根茎蔬菜一起长时间炖煮。","猎人带来的兔肉。肉质清淡，适合搭配蘑菇炖制。","厨房常备的洋葱。炒软后甘甜，是浓汤和炖菜的底味。","略带甜味的根菜。切块加入炖锅，也可在炉边烤熟。","层层卷起的绿叶菜。切碎煮汤，适合配肉与面包。","晒干后也能储存的豌豆。炖软后可做成浓厚的热汤。","气味浓郁的食用蘑菇。搭配奶酪和牛奶制作浓汤。","农田里的朴素根菜。吸收肉汤后柔软甘甜。","农庄送来的牛奶。用于浓汤、粥和简单饮品。","由奶油制成的黄油。煎蛋、炒洋葱和烤水果都能使用。","熟成的奶酪。咸香厚实，可加入汤中，也可配面包。","珍惜使用的盐。少许便能提起汤、肉和面包的滋味。","蜂农采集的蜂蜜。用来调甜饮品，或淋在烤苹果上。","辛香的蒜。捣碎后与香草一起给烤肉调味。","带有清香的厨房香草。适合烤鸡与羊肉炖锅。","果园送来的苹果。烤软后淋上蜂蜜，是朴素的甜点。","清甜的梨。可鲜食，也可与蜂蜜一起慢煮。"};
 public static readonly string[] Recipes={"石炉黑麦面包","黄油煎蛋","洋葱大麦浓汤","豌豆熏肉炖锅","蘑菇奶酪浓汤","香草烤鸡","芜菁炖羊肉","蜂蜜烤苹果"};
 public static readonly string[] Needs={"黑麦 · 小麦粉","鸡蛋 · 黄油 · 盐","洋葱 · 大麦 · 黄油","豌豆 · 猪肉 · 洋葱","蘑菇 · 牛奶 · 奶酪","鸡肉 · 蒜 · 百里香 · 盐","羊肉 · 芜菁 · 胡萝卜","苹果 · 蜂蜜 · 黄油"};
 public static readonly string[] Notes={"石炉烤出厚实的麦香外皮，切片后适合蘸热汤。","黄油煎出金黄边缘，简单热乎，适合作为开店的第一道菜。","炒软的洋葱与大麦慢煮成浓汤，让赶路的旅人暖和起来。","豌豆与熏肉一起慢炖，咸香浓厚，是酒馆的家常招牌。","蘑菇的鲜香融进牛奶和奶酪，盛在温热的陶碗里。","用蒜和百里香调味，在石炉中烤至外皮金黄。","羊肉与根菜慢炖，汤汁浓郁，是丰盛的一餐。","苹果烤至柔软，淋上蜂蜜与少许黄油，作为饭后甜点。"};
 // Atlas objects have deliberately unequal silhouettes; use individually reviewed source bounds.
 public static List<int> RelatedRecipes(int ingredient){var result=new List<int>();if(ingredient<0||ingredient>=Names.Length)return result;for(int i=0;i<Needs.Length;i++)foreach(string part in Needs[i].Split('·'))if(part.Trim()==Names[ingredient]){result.Add(i);break;}return result;}
 static Bitmap atlas;
 static readonly Rectangle[] bounds={
 new Rectangle(20,110,158,210),new Rectangle(184,125,204,194),new Rectangle(396,160,190,147),new Rectangle(590,70,166,256),new Rectangle(784,70,178,254),new Rectangle(974,143,178,179),new Rectangle(1154,143,188,184),new Rectangle(1344,110,192,218),
 new Rectangle(0,347,204,205),new Rectangle(210,342,181,210),new Rectangle(400,326,195,230),new Rectangle(575,365,190,171),new Rectangle(783,381,174,163),new Rectangle(972,357,180,203),new Rectangle(1158,329,186,226),new Rectangle(1352,339,184,218),
 new Rectangle(0,580,211,188),new Rectangle(219,568,170,204),new Rectangle(400,594,185,183),new Rectangle(589,535,186,239),new Rectangle(780,570,176,208),new Rectangle(974,563,178,215),new Rectangle(1158,557,187,221),new Rectangle(1353,563,183,215),
 new Rectangle(0,778,213,174),new Rectangle(213,780,180,174),new Rectangle(395,778,192,178),new Rectangle(590,779,176,181),new Rectangle(782,780,172,180),new Rectangle(970,780,184,177),new Rectangle(1154,780,192,180),new Rectangle(1350,780,186,180)};
 public static void Icon(Graphics g,int index,Rectangle r){
 if(index<0||index>=bounds.Length)return;
 if(atlas==null){string p=Path.Combine(AppDomain.CurrentDomain.BaseDirectory,"assets/food/medieval-food-atlas.png");if(File.Exists(p))atlas=new Bitmap(p);}
 if(atlas==null){IngredientLedgerView.Egg(g,r);return;}
 var source=bounds[index];source=new Rectangle(source.X*atlas.Width/1536,source.Y*atlas.Height/1024,source.Width*atlas.Width/1536,source.Height*atlas.Height/1024);
 int padding=Math.Max(3,Math.Min(r.Width,r.Height)/16);float scale=Math.Min((r.Width-padding*2)/(float)source.Width,(r.Height-padding*2)/(float)source.Height);int w=Math.Max(1,(int)(source.Width*scale)),h=Math.Max(1,(int)(source.Height*scale));
 var state=g.Save();g.InterpolationMode=InterpolationMode.NearestNeighbor;g.PixelOffsetMode=PixelOffsetMode.Half;g.DrawImage(atlas,new Rectangle(r.X+(r.Width-w)/2,r.Y+(r.Height-h)/2,w,h),source,GraphicsUnit.Pixel);g.Restore(state);
 }

}
public sealed class RecipeMenuView:Control {
 readonly List<int> shelf;readonly Action changed;int selected,offset;Rectangle list,detail,right,add;int row=88;
 public RecipeMenuView(string root,List<int> shelf,Action changed){this.shelf=shelf;this.changed=changed;DoubleBuffered=true;ResizeRedraw=true;BackColor=Color.FromArgb(13,29,32);TabStop=true;}
 void LayoutBoxes(){int gap=18,pad=24,y=104,h=Math.Max(260,Height-y-24);int lw=(Width-pad*2-gap*2)*30/100,rw=(Width-pad*2-gap*2)*27/100;list=new Rectangle(pad,y,lw,h);detail=new Rectangle(list.Right+gap,y,Width-pad*2-gap*2-lw-rw,h);right=new Rectangle(detail.Right+gap,y,rw,h);offset=Math.Max(0,Math.Min(offset,Math.Max(0,8*row-h)));add=new Rectangle(detail.X+16,detail.Bottom-60,detail.Width-32,42);}
 static void Label(Graphics g,string s,Rectangle r,float size,Color c){using(var f=GameTheme.Body(size))GameTheme.DrawText(g,s,f,r,c,TextFormatFlags.WordBreak|TextFormatFlags.NoPadding|TextFormatFlags.PreserveGraphicsClipping);}
 static void Frame(Graphics g,Rectangle r,Color c){using(var b=new SolidBrush(c))g.FillRectangle(b,r);using(var p=new Pen(GuildChrome.Gold,2))g.DrawRectangle(p,r);}
 protected override void OnMouseWheel(MouseEventArgs e){base.OnMouseWheel(e);LayoutBoxes();if(list.Contains(e.Location)){offset=Math.Max(0,Math.Min(Math.Max(0,8*row-list.Height),offset-e.Delta/120*row));Invalidate();}}
 protected override void OnMouseDown(MouseEventArgs e){base.OnMouseDown(e);LayoutBoxes();if(list.Contains(e.Location)){selected=Math.Min(7,(e.Y-list.Y+offset)/row);Invalidate();}else if(add.Contains(e.Location)){if(shelf.Contains(selected))shelf.Remove(selected);else if(shelf.Count<4)shelf.Add(selected);changed();Invalidate();}else if(right.Contains(e.Location)){int i=(e.Y-right.Y-52)/96;if(e.Y>=right.Y+52&&i>=0&&i<shelf.Count){selected=shelf[i];Invalidate();}}}
 protected override void OnPaint(PaintEventArgs e){base.OnPaint(e);LayoutBoxes();var g=e.Graphics;var ink=Color.FromArgb(66,48,34);Label(g,"今日菜单 · MENU",new Rectangle(26,26,500,40),23,GuildChrome.Gold);Label(g,"选择菜谱查看介绍 · 左侧可滚动",new Rectangle(26,72,600,24),11,GuildChrome.Ivory);var state=g.Save();g.SetClip(list);for(int i=0;i<8;i++){var r=new Rectangle(list.X,list.Y+i*row-offset,list.Width,row-6);Frame(g,r,i==selected?Color.FromArgb(61,85,68):Color.FromArgb(28,52,53));FoodCatalog.Icon(g,24+i,new Rectangle(r.X+6,r.Y+8,64,64));Label(g,FoodCatalog.Recipes[i],new Rectangle(r.X+76,r.Y+13,r.Width-82,48),12,GuildChrome.Ivory);Label(g,shelf.Contains(i)?"已上架":"未上架",new Rectangle(r.X+76,r.Y+57,r.Width-82,24),10,GuildChrome.Gold);}g.Restore(state);Frame(g,detail,Color.FromArgb(223,203,157));Label(g,FoodCatalog.Recipes[selected],new Rectangle(detail.X+18,detail.Y+20,detail.Width-36,64),19,ink);int pic=Math.Min(140,detail.Height/4);FoodCatalog.Icon(g,24+selected,new Rectangle(detail.X+18,detail.Y+82,detail.Width-36,pic));int y=detail.Y+86+pic;Label(g,"所需食材",new Rectangle(detail.X+18,y,detail.Width-36,28),13,ink);Label(g,FoodCatalog.Needs[selected],new Rectangle(detail.X+18,y+32,detail.Width-36,70),12,ink);Label(g,FoodCatalog.Notes[selected],new Rectangle(detail.X+18,y+108,detail.Width-36,Math.Max(20,add.Y-y-118)),12,ink);Frame(g,add,Color.FromArgb(28,52,53));Label(g,shelf.Contains(selected)?"从今日菜单撤下":shelf.Count>=4?"已上架四道，请先撤下一道":"加入今日菜单",new Rectangle(add.X+12,add.Y+9,add.Width-24,30),12,GuildChrome.Ivory);Frame(g,right,Color.FromArgb(28,52,53));Label(g,"今日上架  "+shelf.Count+" / 4",new Rectangle(right.X+14,right.Y+16,right.Width-28,32),15,GuildChrome.Gold);for(int i=0;i<shelf.Count;i++){int n=shelf[i];var r=new Rectangle(right.X+10,right.Y+52+i*96,right.Width-20,88);Frame(g,r,Color.FromArgb(13,29,32));FoodCatalog.Icon(g,24+n,new Rectangle(r.X+4,r.Y+10,56,56));Label(g,FoodCatalog.Recipes[n],new Rectangle(r.X+66,r.Y+16,r.Width-72,60),12,GuildChrome.Ivory);}if(shelf.Count==0)Label(g,"尚未上架菜谱\n请从左侧选择",new Rectangle(right.X+16,right.Y+72,right.Width-32,90),12,GuildChrome.Ivory);}
}
