using System;using System.Drawing;using System.Drawing.Drawing2D;using System.Windows.Forms;
public class RogueIcon:Button {
 public string Kind;public bool Selected;public int Count;public bool TransparentBackground=true;
 public RogueIcon(){SetStyle(ControlStyles.SupportsTransparentBackColor|ControlStyles.UserPaint|ControlStyles.AllPaintingInWmPaint|ControlStyles.OptimizedDoubleBuffer,true);Width=44;Height=44;Margin=new Padding(3,6,3,3);FlatStyle=FlatStyle.Flat;FlatAppearance.BorderSize=0;BackColor=Color.FromArgb(25,53,55);Cursor=Cursors.Hand;DoubleBuffered=true;}
 protected override void OnMouseEnter(EventArgs e){if(Enabled)VNButton.PlayControlSound(this,false);base.OnMouseEnter(e);}
 protected override void OnClick(EventArgs e){if(Enabled)VNButton.PlayControlSound(this,true);base.OnClick(e);}
 protected override void OnPaintBackground(PaintEventArgs e){if(TransparentBackground){Control ancestor=Parent;while(ancestor!=null&&!(ancestor is RogueCard))ancestor=ancestor.Parent;var card=ancestor as RogueCard;if(card!=null){e.Graphics.Clear(Color.FromArgb(25,53,55));Control scene=card.Parent;while(scene!=null&&!(scene is CardRewardSurface))scene=scene.Parent;var surface=scene as CardRewardSurface;if(surface!=null)surface.DrawBackdrop(e.Graphics,new Rectangle(surface.PointToClient(PointToScreen(Point.Empty)),ClientSize));var offset=card.PointToClient(PointToScreen(Point.Empty));var state=e.Graphics.Save();e.Graphics.TranslateTransform(-offset.X,-offset.Y);GuildChrome.Draw(e.Graphics,card.ClientRectangle);e.Graphics.Restore(state);}else e.Graphics.Clear(Color.FromArgb(25,53,55));}else e.Graphics.Clear(Color.FromArgb(22,38,45));}
 protected override void OnPaint(PaintEventArgs e){var g=e.Graphics;if(TransparentBackground)OnPaintBackground(e);else g.Clear(Color.FromArgb(22,38,45));g.SmoothingMode=SmoothingMode.AntiAlias;float cx=Width/2f,cy=Height/2f;float scale=Math.Min(Width,Height)/44f;var saved=g.Save();g.TranslateTransform(cx,cy);g.ScaleTransform(scale,scale);Color color=!Enabled?Color.FromArgb(103,118,121):Kind=="star"?(Selected?Color.FromArgb(255,209,111):Color.FromArgb(200,181,231)):Kind=="bulb"?Color.FromArgb(247,211,135):Color.FromArgb(150,225,206);if(!TransparentBackground)using(var bg=new SolidBrush(Color.FromArgb(155,22,38,45)))g.FillEllipse(bg,-20,-20,40,40);using(var border=new Pen(Color.FromArgb(90,150,166,162),1))g.DrawEllipse(border,-20,-20,40,40);using(var pen=new Pen(color,2.2f))using(var brush=new SolidBrush(color)){
 if(Kind=="speaker"){g.TranslateTransform(-2,0);g.ScaleTransform(.9f,.9f);g.FillPolygon(brush,new[]{new PointF(-12,-4),new PointF(-7,-4),new PointF(0,-10),new PointF(0,10),new PointF(-7,4),new PointF(-12,4)});g.DrawArc(pen,-4,-8,15,16,-60,120);g.DrawArc(pen,-7,-13,25,26,-55,110);}
 else if(Kind=="star"){var points=new PointF[10];for(int i=0;i<10;i++){double angle=-Math.PI/2+i*Math.PI/5;float radius=i%2==0?12:5.3f;points[i]=new PointF((float)Math.Cos(angle)*radius,(float)Math.Sin(angle)*radius);}if(Selected)g.FillPolygon(brush,points);else g.DrawPolygon(pen,points);}
 else{g.DrawEllipse(pen,-7,-12,14,16);g.DrawLine(pen,-4,5,4,5);g.DrawLine(pen,-4,8,4,8);g.DrawLine(pen,-2,11,2,11);g.DrawLine(pen,-2,-4,0,3);g.DrawLine(pen,2,-4,0,3);}}
 g.Restore(saved);if(Kind=="bulb")using(var font=GameTheme.Body(8))GameTheme.DrawText(g,Count.ToString(),font,new Rectangle(Width-15,Height-15,14,14),color,TextFormatFlags.Right|TextFormatFlags.NoPadding);}
}

