using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;

public class RogueEntry {
 public string word {get;set;} public string meaning {get;set;} public int tier {get;set;} public string example {get;set;} public string exampleZh {get;set;}
}
public class RogueMemory {
 public int appearances {get;set;} public int mask {get;set;} public int correct {get;set;} public int wrong {get;set;} public string last {get;set;}
}
public class RogueQuestion {
 public RogueEntry entry {get;set;} public int kind {get;set;} public List<string> options {get;set;} public int answer {get;set;} public bool assisted {get;set;} public bool answered {get;set;}
}
public class RogueProfile {
 public List<string> unlockedCards {get;set;} public Dictionary<string,int> monsterKills {get;set;} public int smallKills {get;set;} public int eliteKills {get;set;}
 [System.Web.Script.Serialization.ScriptIgnore] public bool preparationActive {get;set;}
 [System.Web.Script.Serialization.ScriptIgnore] public RogueRun ActiveRun {get{return preparationActive?prepSession:run;}}
 public Dictionary<string,RogueRun> preparationRuns {get;set;}

 public Dictionary<string,SectionPreparation> preparations {get;set;} public RogueRun prepSession {get;set;} public string prepChapter {get;set;} public bool prologueDone {get;set;} public int prologuePage {get;set;} public List<string> legacyStoryAccess {get;set;}
 public List<string> storyItems {get;set;} public List<string> storyUsed {get;set;}
 public int coins {get;set;} public int clears {get;set;} public int bestDepth {get;set;} public int answers {get;set;} public int correct {get;set;}
 public List<string> upgrades {get;set;} public Dictionary<string,string> coinDates {get;set;} public Dictionary<string,RogueMemory> memory {get;set;} public RogueRun run {get;set;}
 public RogueProfile(){preparations=new Dictionary<string,SectionPreparation>();legacyStoryAccess=new List<string>();storyItems=new List<string>();storyUsed=new List<string>();upgrades=new List<string>();coinDates=new Dictionary<string,string>();memory=new Dictionary<string,RogueMemory>();}
 public void Normalize(){if(preparationRuns==null)preparationRuns=new Dictionary<string,RogueRun>();if(preparations==null)preparations=new Dictionary<string,SectionPreparation>();if(legacyStoryAccess==null)legacyStoryAccess=new List<string>();if(storyItems==null)storyItems=new List<string>();if(storyUsed==null)storyUsed=new List<string>();if(upgrades==null)upgrades=new List<string>();if(coinDates==null)coinDates=new Dictionary<string,string>();if(memory==null)memory=new Dictionary<string,RogueMemory>();coins=Math.Max(0,coins);}
}
public class RogueRun {
 public List<PartyUnit> partyRoster {get;set;} public PartyCombatState partyBattle {get;set;} public CardBattleState cardBattle {get;set;}
 public int mapVersion {get;set;} public List<TowerNode> nodes {get;set;} public string currentNode {get;set;} public string lastNode {get;set;} public int theme {get;set;} public int eventKind {get;set;} public bool eventBattle {get;set;} public int battleAssists {get;set;} public int battleCoins {get;set;} public bool battlePaid {get;set;} public int lastDamage {get;set;} public int lastReceived {get;set;} public int guard {get;set;} public bool guardUsed {get;set;} public string vocabularyChapter {get;set;} public int chestKind {get;set;}
 public string id {get;set;} public int seed {get;set;} public int serial {get;set;} public string mode {get;set;} public string state {get;set;}
 public int depth {get;set;} public int hp {get;set;} public int maxHp {get;set;} public int attack {get;set;} public int armor {get;set;} public int combo {get;set;} public int comboPower {get;set;} public int heal {get;set;} public int leech {get;set;} public int fortune {get;set;} public int hints {get;set;} public int gold {get;set;}
 public string enemy {get;set;} public int enemyHp {get;set;} public int enemyMax {get;set;} public int answered {get;set;} public int correct {get;set;} public int mistakes {get;set;} public int earnedCoins {get;set;} public bool settled {get;set;} public bool won {get;set;}
 public List<RogueEntry> pool {get;set;} public List<string> routes {get;set;} public List<string> rewards {get;set;} public List<string> relics {get;set;} public List<string> recent {get;set;} public List<string> wrongWords {get;set;} public List<string> shopBought {get;set;}
 public RogueQuestion question {get;set;} public string feedback {get;set;}
 public RogueRun(){routes=new List<string>();rewards=new List<string>();relics=new List<string>();recent=new List<string>();wrongWords=new List<string>();shopBought=new List<string>();comboPower=2;}
}
public static class RogueEngine {
 public static readonly string[] Relics={"blade","shield","heart","regen","oracle","focus","fortune","ward"};
 public static string RelicName(string id){switch(id){case "blade":return "锋刃符石";case "shield":return "守护刻印";case "heart":return "生命琥珀";case "regen":return "回春枝";case "oracle":return "智慧烛火";case "focus":return "连击纹章";case "fortune":return "寻金罗盘";case "ward":return "庇护羽毛";default:return "吸能模块";}}
 public static string RelicDescription(string id){switch(id){case "blade":return "攻击 +4";case "shield":return "护甲 +2，降低每次受伤";case "heart":return "生命上限 +20，并恢复 20";case "regen":return "每场胜利恢复 8 生命";case "oracle":return "提示次数 +1（提示题不奖励金币）";case "focus":return "每层连击额外增加 1 点伤害";case "fortune":return "每次战斗多获得 5 金币";case "ward":return "每场战斗第一次答错的伤害减半";default:return "每次无提示答对恢复 2 生命";}}
 public static List<RogueEntry> LoadBank(string file){var list=new List<RogueEntry>();foreach(var line in File.ReadAllLines(file)){if(String.IsNullOrWhiteSpace(line))continue;var parts=line.Split('|');int tier;if((parts.Length!=4&&parts.Length!=5)||!int.TryParse(parts[2],out tier)||tier<1||tier>3||String.IsNullOrWhiteSpace(parts[0])||String.IsNullOrWhiteSpace(parts[1])||!parts[3].Contains("{"+parts[0]+"}"))throw new Exception("远征词库格式错误："+line);list.Add(new RogueEntry{word=parts[0],meaning=parts[1],tier=tier,example=parts[3],exampleZh=parts.Length==5?parts[4]:null});}if(list.Select(w=>w.word).Distinct().Count()!=list.Count)throw new Exception("远征词库包含重复单词。");return list;}
 public static Random RandomFor(RogueRun r){return new Random(unchecked(r.seed+(++r.serial)*7919));}
 public static RogueRun NewRun(RogueProfile p,List<RogueEntry> pool,string mode,int seed){p.Normalize();pool=pool.GroupBy(e=>e.word,StringComparer.OrdinalIgnoreCase).Select(g=>g.First()).Where(e=>!String.IsNullOrWhiteSpace(e.meaning)).ToList();if(pool.Count<4||pool.Select(e=>e.meaning).Distinct().Count()<4)throw new Exception("至少需要四个单词和四种不同词义。");var r=new RogueRun{id=Guid.NewGuid().ToString("N"),seed=seed,mode=mode,state="map",pool=pool,hp=100,maxHp=100,attack=15,hints=1};p.run=r;TowerEngine.Initialize(r);return r;}
 public static void Routes(RogueRun r){if(TowerEngine.IsTower(r)){TowerEngine.Routes(r);return;}if(r.depth>=9){r.state="ended";return;}r.state="map";if(r.depth==8){r.routes=new List<string>{"boss"};return;}if(r.depth==2||r.depth==5){r.routes=new List<string>{"elite","rest"};return;}var rng=RandomFor(r);r.routes=new List<string>{"combat",new[]{"event","shop","rest"}[rng.Next(3)]};}
 public static string RouteName(string route){switch(route){case "combat":return "巡逻无人机";case "elite":return "精英 · 追踪猎手";case "boss":return "首领 · 词域防火墙";case "rest":return "休息站";case "shop":return "补给商店";default:return "未知信号";}}
 public static void ChooseRoute(RogueRun r,string route,RogueProfile p){if(TowerEngine.IsTower(r)){TowerEngine.Choose(r,route,p);return;}if(r.state!="map"||!r.routes.Contains(route))return;if(route=="rest"){r.state="rest";return;}if(route=="shop"){r.state="shop";r.shopBought.Clear();return;}if(route=="event"){r.state="event";return;}r.enemy=route;r.enemyMax=route=="boss"?100:route=="elite"?55+r.depth*5:32+r.depth*5;r.enemyHp=r.enemyMax;r.combo=0;r.state="combat";NextQuestion(r,p);}
 public static bool SeenWord(RogueProfile p,string word){RogueMemory m;return p.memory.TryGetValue(word,out m)&&m!=null&&(m.appearances>0||m.correct>0||m.wrong>0||m.mask!=0||!String.IsNullOrEmpty(m.last));}
 public static void RecordWordAppearance(RogueProfile p,string word){RogueMemory m;if(!p.memory.TryGetValue(word,out m)||m==null){m=new RogueMemory();p.memory[word]=m;}m.appearances++;}
 // Old saves can contain an unattempted spelling question generated before this rule.
 public static void EnsureFirstQuestion(RogueRun r,RogueProfile p){
  if(r==null||r.state!="combat"||r.question==null||r.question.answered||SeenWord(p,r.question.entry.word))return;
  var q=r.question;if(q.kind==3){var rng=RandomFor(r);var options=r.pool.Where(w=>w.word!=q.entry.word&&w.meaning!=q.entry.meaning).OrderBy(w=>rng.Next()).Select(w=>w.meaning).Distinct().Take(3).ToList();if(options.Count!=3)throw new Exception("词库无法生成唯一选项。");options.Add(q.entry.meaning);q.kind=0;q.options=options.OrderBy(w=>rng.Next()).ToList();q.answer=q.options.IndexOf(q.entry.meaning);}
  RecordWordAppearance(p,q.entry.word);
 }
 public static void NextQuestion(RogueRun r,RogueProfile p){if(TowerEngine.IsTower(r))CardBattle.Ensure(r,p);if(TowerEngine.PreparedQuestion(r,p))return;var rng=RandomFor(r);var candidates=r.pool.Where(w=>!r.recent.Contains(w.word)).ToList();if(candidates.Count<4)candidates=r.pool.ToList();var retry=candidates.Where(w=>r.wrongWords.Contains(w.word)).ToList();RogueEntry entry;if(retry.Count>0&&r.answered%3==2)entry=retry[rng.Next(retry.Count)];else{var ordered=candidates.OrderBy(w=>{RogueMemory m;return p.memory.TryGetValue(w.word,out m)?m.correct-m.wrong:0;}).Take(Math.Max(4,candidates.Count/2)).ToList();entry=ordered[rng.Next(ordered.Count)];}int kind=SeenWord(p,entry.word)?r.answered%4:0;if(r.mode=="基础训练"&&kind==3)kind=0;if(kind==2&&(String.IsNullOrWhiteSpace(entry.example)||entry.example.StartsWith("Practice the word")))kind=1;var q=new RogueQuestion{entry=entry,kind=kind,options=new List<string>()};if(kind!=3){var alternatives=r.pool.Where(w=>w.word!=entry.word&&(kind!=0||w.meaning!=entry.meaning)).OrderBy(w=>rng.Next()).Select(w=>kind==0?w.meaning:w.word).Distinct().Take(3).ToList();if(alternatives.Count!=3)throw new Exception("词库无法生成唯一选项。");alternatives.Add(kind==0?entry.meaning:entry.word);q.options=alternatives.OrderBy(w=>rng.Next()).ToList();q.answer=q.options.IndexOf(kind==0?entry.meaning:entry.word);}RecordWordAppearance(p,entry.word);r.question=q;r.recent.Add(entry.word);while(r.recent.Count>3)r.recent.RemoveAt(0);r.state="combat";}
 public static int EnemyDamage(RogueRun r){if(TowerEngine.IsTower(r))return TowerEngine.EnemyDamage(r);return Math.Max(1,(r.enemy=="boss"?14:r.enemy=="elite"?11:7)+r.depth/2-r.armor);}
 public static bool Hint(RogueRun r){if(r.state!="combat"||r.question==null||r.question.answered||r.question.assisted||r.hints<=0)return false;r.hints--;r.question.assisted=true;return true;}
 public static bool Answer(RogueProfile p,int selected,string spelling,DateTime now){var r=p.ActiveRun;if(r==null||r.state!="combat"||r.question==null||r.question.answered)return false;if(TowerEngine.IsTower(r)){CardBattle.Ensure(r,p);if(r.cardBattle.overflow.Count>0||!r.cardBattle.answering)return false;}var q=r.question;bool correct=q.kind==3?String.Equals((spelling??"").Trim(),q.entry.word,StringComparison.OrdinalIgnoreCase):selected==q.answer;q.answered=true;if(TowerEngine.IsTower(r)&&q.assisted)r.battleAssists++;r.answered++;p.answers++;RogueMemory memory;if(!p.memory.TryGetValue(q.entry.word,out memory)){memory=new RogueMemory();p.memory[q.entry.word]=memory;}memory.last=now.ToString("yyyy-MM-dd");int damage=0,received=0,coins=0;if(correct){r.correct++;p.correct++;r.combo=q.assisted?0:r.combo+1;damage=r.attack+Math.Min(5,r.combo)*r.comboPower+(q.kind==3?4:0);if(q.assisted)damage=Math.Max(5,r.attack/2);if(TowerEngine.IsTower(r))damage=CardBattle.Attack(r,damage,correct&&!q.assisted);else r.enemyHp=Math.Max(0,r.enemyHp-damage);if(!q.assisted){memory.correct++;memory.mask|=1<<q.kind;if(r.leech>0)r.hp=Math.Min(r.maxHp,r.hp+r.leech);r.wrongWords.Remove(q.entry.word);string date=now.ToString("yyyy-MM-dd"),old;if(!p.coinDates.TryGetValue(q.entry.word,out old)||old!=date){coins=3;p.coins+=coins;r.earnedCoins+=coins;p.coinDates[q.entry.word]=date;}}if(!TowerEngine.IsTower(r)&&r.enemyHp>0&&r.combo>0&&r.combo%(r.mapVersion>=3?3:2)==0){received=Math.Max(1,EnemyDamage(r)/2);r.hp=Math.Max(0,r.hp-received);}}else{memory.wrong++;r.mistakes++;r.combo=0;received=TowerEngine.IsTower(r)?0:EnemyDamage(r);if(!TowerEngine.IsTower(r)&&r.guard>0&&!r.guardUsed){received=Math.Max(1,(int)Math.Ceiling(received/Math.Pow(2,Math.Min(6,r.guard))));r.guardUsed=true;}r.hp=Math.Max(0,r.hp-received);if(!r.wrongWords.Contains(q.entry.word))r.wrongWords.Add(q.entry.word);}if(TowerEngine.IsTower(r))received=CardBattle.Enemy(r,correct,correct&&!q.assisted,damage);r.lastDamage=damage;r.lastReceived=received;r.feedback=(correct?(q.assisted?"提示命中":"回答正确")+" · 造成 "+damage+" 伤害":"回答错误 · 承受 "+received+" 伤害")+(correct&&received>0?" · 敌人反击 "+received:"")+(TowerEngine.IsTower(r)?" · 护盾抵挡 "+r.cardBattle.lastBlocked+(r.cardBattle.lastEvaded?" · 闪避敌方普通攻击":""):"")+(coins>0?" · 金币 +3":"")+"\n"+q.entry.word+" · "+q.entry.meaning+"\n"+q.entry.example.Replace("{"+q.entry.word+"}",q.entry.word);TowerEngine.Learn(p,r,q,correct);r.state="feedback";return true;}
 public static void Continue(RogueProfile p){if(TowerEngine.IsTower(p.ActiveRun)){TowerEngine.Continue(p);return;}var r=p.ActiveRun;if(r==null||r.state!="feedback")return;if(r.hp<=0){Finish(p,false);return;}if(r.enemyHp<=0){r.gold+=(r.enemy=="boss"?30:r.enemy=="elite"?22:12)+r.fortune;r.hp=Math.Min(r.maxHp,r.hp+r.heal);if(r.depth==8){r.depth=9;Finish(p,true);return;}r.rewards=Relics.OrderBy(x=>RandomFor(r).Next()).Take(3).ToList();r.state="reward";return;}NextQuestion(r,p);}
 public static void ApplyRelic(RogueRun r,string id){switch(id){case "blade":r.attack+=4;break;case "shield":r.armor+=2;break;case "heart":r.maxHp+=20;r.hp=Math.Min(r.maxHp,r.hp+20);break;case "regen":r.heal+=8;break;case "oracle":r.hints++;break;case "focus":r.comboPower++;break;case "fortune":r.fortune+=5;break;case "leech":r.leech+=2;break;case "ward":r.guard++;break;default:throw new Exception("未知强化。");}r.relics.Add(id);}
 public static void Reward(RogueProfile p,string id){var r=p.ActiveRun;if(r==null||r.state!="reward"||!r.rewards.Contains(id))return;ApplyRelic(r,id);CompleteNode(p);}
 public static void CompleteNode(RogueProfile p){if(TowerEngine.IsTower(p.ActiveRun)){TowerEngine.Complete(p);return;}var r=p.ActiveRun;r.depth++;p.bestDepth=Math.Max(p.bestDepth,r.depth);Routes(r);}
 public static void Rest(RogueProfile p,bool heal){if(TowerEngine.IsTower(p.ActiveRun)){TowerEngine.Rest(p,heal);return;}var r=p.ActiveRun;if(r==null||r.state!="rest")return;if(heal)r.hp=Math.Min(r.maxHp,r.hp+35);else r.attack+=2;CompleteNode(p);}
 public static void Event(RogueProfile p,bool risk){if(TowerEngine.IsTower(p.ActiveRun)){TowerEngine.Event(p,risk);return;}var r=p.ActiveRun;if(r==null||r.state!="event")return;if(risk){if(r.hp<=12)return;r.hp-=12;var rng=RandomFor(r);ApplyRelic(r,Relics[rng.Next(Relics.Length)]);}else{r.gold+=10;r.hints++;}CompleteNode(p);}
 public static bool BuySupply(RogueRun r,string id){if(r.state!="shop"||r.shopBought.Contains(id))return false;int price=id=="potion"?15:id=="shield"?25:20;if(r.gold<price||(id=="potion"&&r.hp==r.maxHp))return false;r.gold-=price;r.shopBought.Add(id);if(id=="potion")r.hp=Math.Min(r.maxHp,r.hp+30);else if(id=="shield")ApplyRelic(r,"shield");else r.hints++;return true;}
 public static void Finish(RogueProfile p,bool won){var r=p.ActiveRun;if(r==null||r.settled)return;r.won=won;r.settled=true;r.state="ended";p.bestDepth=Math.Max(p.bestDepth,r.depth);if(won){if(!String.IsNullOrEmpty(r.vocabularyChapter))PreparationEngine.Progress(p,r.vocabularyChapter).cleared=true;p.clears++;if(!TowerEngine.IsTower(r)){p.coins+=20;r.earnedCoins+=20;}}}
}
