using System;using System.Linq;using System.IO;using System.Drawing;using System.Windows.Forms;using System.Collections.Generic;using System.Diagnostics;using System.Security.Cryptography;using System.Text;
public class SpellPracticeProgress {
 public int level{get;set;}public Dictionary<string,int> positions{get;set;}public Dictionary<string,int> answers{get;set;}public List<string> attempted{get;set;}
 public SpellPracticeProgress(){level=4;positions=new Dictionary<string,int>();answers=new Dictionary<string,int>();attempted=new List<string>();}
}
public class RealListeningQuestion {public int number{get;set;}public string prompt{get;set;}public string[] options{get;set;}public int answer{get;set;}public string explanation{get;set;}public string group_id{get;set;}public double start{get;set;}public double end{get;set;}}
public class RealListeningGroup {public string id{get;set;}public string title{get;set;}public double start{get;set;}public double end{get;set;}public int first{get;set;}public int last{get;set;}public string material{get;set;}}
public class RealListeningExam {public string id{get;set;}public string title{get;set;}public int level{get;set;}public string audio{get;set;}public string source_url{get;set;}public string material_source{get;set;}public string caption_kind{get;set;}public List<Line> lines{get;set;}public List<RealListeningQuestion> questions{get;set;}public List<RealListeningGroup> groups{get;set;}}
public static class SpellPracticeAudio {
 public static string Prepare(string root,string relative){string source=Engine.SafePath(root,relative);var info=new FileInfo(source);string hash;using(var digest=SHA256.Create())hash=BitConverter.ToString(digest.ComputeHash(Encoding.UTF8.GetBytes(source+"|"+info.Length+"|"+info.LastWriteTimeUtc.Ticks))).Replace("-","").Substring(0,16);string folder=Path.Combine(root,".audio-cache");Directory.CreateDirectory(folder);string target=Path.Combine(folder,"spell-"+hash+".wav");if(File.Exists(target))return target;string temporary=target+".tmp.wav";var command=new ProcessStartInfo(Path.Combine(root,"tools","ffmpeg","ffmpeg.exe"),"-nostdin -hide_banner -loglevel error -y -i \""+source+"\" -vn -ar 24000 -ac 1 -c:a pcm_s16le \""+temporary+"\""){UseShellExecute=false,CreateNoWindow=true,RedirectStandardError=true};using(var process=Process.Start(command)){string error=process.StandardError.ReadToEnd();process.WaitForExit();if(process.ExitCode!=0){if(File.Exists(temporary))File.Delete(temporary);throw new IOException("真题音频准备失败："+error);}}File.Move(temporary,target);return target;}
}
public partial class Game {
 Chapter spellChapter,spellOriginalChapter;int spellOriginalIndex;RealListeningExam activeSpellExam;int spellLibraryYear,spellLibraryPage;long spellReplayEndMs;
 bool IsSpellPractice(){return spellChapter!=null&&Object.ReferenceEquals(current,spellChapter);}
 SpellPracticeProgress SpellPracticeState(){if(save.spellPractice==null)save.spellPractice=new SpellPracticeProgress();var state=save.spellPractice;if(state.positions==null)state.positions=new Dictionary<string,int>();if(state.answers==null)state.answers=new Dictionary<string,int>();if(state.attempted==null)state.attempted=new List<string>();string today=TavernBusiness.State(save).day+":";state.attempted.RemoveAll(key=>!key.StartsWith(today));return state;}
 List<RealListeningExam> RealListeningBank(int level){string dir=Path.Combine(root,"assets","tavern","listening","real-exams","cettong");var list=new List<RealListeningExam>();if(!Directory.Exists(dir))return list;foreach(string file in Directory.GetFiles(dir,"*.resources.json",SearchOption.AllDirectories)){var entry=Engine.Json.Deserialize<RealListeningExam>(File.ReadAllText(file));if(entry.level!=level)continue;string captions=file.Replace(".resources.json",".captions.json");if(File.Exists(captions)){var caption=Engine.Json.Deserialize<RealListeningExam>(File.ReadAllText(captions));entry.lines=caption.lines;entry.caption_kind=caption.caption_kind;entry.audio=caption.audio;}list.Add(entry);}return list.OrderByDescending(e=>e.id).ToList();}
 void ShowTavernListeningList(int level){SpellPracticeState().level=level;ClearPage();page="spell-library";var exams=RealListeningBank(level);var surface=new CardRewardSurface{Dock=DockStyle.Fill,Art=CachedImage(Path.Combine(root,"assets","waystation","tavern-night-clear.png")),CompositeChildren=true};content.Controls.Add(surface);var panel=new BattleGlassPanel{Dock=DockStyle.Fill,Padding=new Padding(24)};surface.Controls.Add(panel);
  var title=new OutlinedLabel{Text="咒语练习 · 四六级真题听力",Font=GameTheme.Body(22),ForeColor=GuildChrome.Gold};panel.Controls.Add(title);var detail=new OutlinedLabel{Text="整套听力 / 逐句精听 · 中英字幕自由开关 · 点击英文查看、朗读与收藏单词",Font=GameTheme.Body(11),ForeColor=GuildChrome.Ivory};panel.Controls.Add(detail);
  var levels=new List<VNButton>();foreach(int value in new[]{4,6}){int chosen=value;var b=PartyButton(value==4?"四级真题":"六级真题",()=>{spellLibraryPage=0;ShowTavernListeningList(chosen);},160,42);b.Active=value==level;levels.Add(b);panel.Controls.Add(b);}
  var years=new List<VNButton>();foreach(int value in new[]{0}.Concat(exams.Select(e=>Int32.Parse(e.id.Split('-')[1].Split('_')[0])).Distinct().OrderByDescending(v=>v))){int chosen=value;var b=PartyButton(value==0?"全部年份":value+"年",()=>{spellLibraryYear=chosen;spellLibraryPage=0;ShowTavernListeningList(level);},90,36);b.Active=value==spellLibraryYear;years.Add(b);panel.Controls.Add(b);}
  var filtered=exams.Where(e=>spellLibraryYear==0||e.id.Contains("-"+spellLibraryYear+"_")).ToList();int pages=Math.Max(1,(filtered.Count+5)/6);spellLibraryPage=Math.Max(0,Math.Min(spellLibraryPage,pages-1));var cards=new List<VNButton>();foreach(var entry in filtered.Skip(spellLibraryPage*6).Take(6)){var selected=entry;int previous;SpellPracticeState().positions.TryGetValue("spell-"+entry.id,out previous);var b=PartyButton(entry.title+"\n"+(entry.lines==null?"字幕整理中":entry.lines.Count+" 句 · "+entry.questions.Count+" 题"+(previous>0?" · 继续第 "+(previous+1)+" 句":" · 开始练习")),()=>NavigateMenu(()=>OpenSpellPractice(selected),"咒语精听",false),320,90);b.Enabled=entry.lines!=null&&entry.lines.Count>0;cards.Add(b);panel.Controls.Add(b);}
  var back=PartyButton("返回营业",ShowTavernBusiness,160,42);panel.Controls.Add(back);var prev=PartyButton("上一页",()=>{spellLibraryPage--;ShowTavernListeningList(level);},100,42);prev.Enabled=spellLibraryPage>0;panel.Controls.Add(prev);var next=PartyButton("下一页",()=>{spellLibraryPage++;ShowTavernListeningList(level);},100,42);next.Enabled=spellLibraryPage+1<pages;panel.Controls.Add(next);var counter=Lab((spellLibraryPage+1)+" / "+pages+" 页 · "+filtered.Count+" 套",11,Gold);panel.Controls.Add(counter);
  Action layout=()=>{int w=panel.ClientSize.Width,h=panel.ClientSize.Height,left=24;title.Bounds=new Rectangle(left,20,w-48,38);detail.Bounds=new Rectangle(left,62,w-48,40);for(int i=0;i<levels.Count;i++)levels[i].Bounds=new Rectangle(left+i*172,105,160,40);int yw=Math.Max(55,Math.Min(100,(w-48)/Math.Max(1,years.Count)-5));for(int i=0;i<years.Count;i++)years[i].Bounds=new Rectangle(left+i*(yw+5),154,yw,34);int cw=(w-60)/2,ch=Math.Max(55,(h-300)/3);for(int i=0;i<cards.Count;i++){cards[i].Bounds=new Rectangle(left+i%2*(cw+12),202+i/2*(ch+8),cw,ch);cards[i].Font=GameTheme.Body(h<560?11:13);}back.Bounds=new Rectangle(left,h-55,150,40);prev.Bounds=new Rectangle(w-360,h-55,95,40);counter.Bounds=new Rectangle(w-256,h-48,145,30);next.Bounds=new Rectangle(w-110,h-55,85,40);};panel.Resize+=(s,e)=>layout();layout();panel.Focus();}
 void OpenSpellPractice(RealListeningExam exam){if(exam.lines==null||exam.lines.Count==0){GameMessage.Show(this,"本套逐句字幕尚未准备完成。");return;}string wav=SpellPracticeAudio.Prepare(root,exam.audio);ClearPage();spellOriginalChapter=current;spellOriginalIndex=index;activeSpellExam=exam;spellChapter=new Chapter{id="spell-"+exam.id,title=exam.title,pixelArt=true,unlockLevel=1,audio=wav.Substring(root.TrimEnd('\\','/').Length+1).Replace('\\','/'),audioLabel="四六级真题原声",background="assets/waystation/tavern-night-clear.png",lines=exam.lines,actors=new List<Actor>(),questions=new List<QuizQuestion>(),decisions=new List<Decision>()};current=spellChapter;folders[current.id]=root;int position;SpellPracticeState().positions.TryGetValue(current.id,out position);index=Math.Max(0,Math.Min(current.lines.Count-1,position));page="story";TavernBusiness.Begin(save,"listening");BuildStoryDialogue();}
 void LeaveSpellPractice(){if(!IsSpellPractice())return;SpellPracticeState().positions[current.id]=index;folders.Remove(current.id);current=spellOriginalChapter;index=spellOriginalIndex;spellChapter=null;activeSpellExam=null;}
 void ReturnSpellPracticeLibrary(){int level=activeSpellExam==null?SpellPracticeState().level:activeSpellExam.level;ShowTavernListeningList(level);}
 void CompleteSpellPractice(){StopAudio();using(var dialog=SpellDialog("本套练习完成",600,380)){var title=new OutlinedLabel{Text="本套听力已完成\n可重听、逐组答题，或返回选择其他真题。",Dock=DockStyle.Top,Height=110,Font=GameTheme.Body(16),ForeColor=GuildChrome.Ivory};dialog.Controls.Add(title);var controls=new FlowLayoutPanel{Dock=DockStyle.Bottom,Height=120,FlowDirection=FlowDirection.TopDown};dialog.Controls.Add(controls);controls.Controls.Add(PartyButton("回到第一句",()=>{index=0;UpdateLine();dialog.Close();},420,42));controls.Controls.Add(PartyButton("返回真题目录",()=>{dialog.Close();ReturnSpellPracticeLibrary();},420,42));dialog.ShowDialog(this);}}
 GuildWordDialog SpellDialog(string title,int width,int height){return new GuildWordDialog{QuestStyle=true,Text=title,BackColor=Color.FromArgb(6,29,29),Padding=new Padding(26,64,26,26),Size=new Size(Math.Min(width,ClientSize.Width-20),Math.Min(height,ClientSize.Height-20)),StartPosition=FormStartPosition.CenterParent};}
 void BuildSpellPracticeTools(){var row=new FlowLayoutPanel{BackColor=Color.Transparent,WrapContents=false,Height=44,Width=460};stage.Controls.Add(row);row.Controls.Add(PartyButton("选择片段",ShowSpellGroups,135,38));row.Controls.Add(PartyButton("练习题 / 答案",()=>ShowSpellQuestions(null),155,38));row.Controls.Add(PartyButton("整套连续听",PlayAll,135,38));Action position=()=>{row.Location=new Point(Math.Max(18,stage.Width-row.Width-18),stage.Width<1100?114:18);if(neonHud!=null)neonHud.Width=Math.Max(240,stage.Width<1100?stage.Width-44:stage.Width-row.Width-62);};stage.Resize+=(s,e)=>position();position();row.BringToFront();}
 void ShowSpellGroups(){StopAudio();using(var dialog=SpellDialog("选择听力片段",720,690)){var body=new TableLayoutPanel{Dock=DockStyle.Fill,RowCount=activeSpellExam.groups.Count,ColumnCount=1};dialog.Controls.Add(body);foreach(var group in activeSpellExam.groups){var selected=group;var button=PartyButton(group.title+" · 第 "+group.first+"–"+group.last+" 题",()=>{int at=current.lines.FindIndex(l=>l.start>=selected.start-.2);if(at<0)at=0;index=at;UpdateLine();dialog.Close();},560,46);button.Dock=DockStyle.Fill;body.RowStyles.Add(new RowStyle(SizeType.Percent,100f/Math.Max(1,activeSpellExam.groups.Count)));body.Controls.Add(button);}dialog.ShowDialog(this);}}
 void ShowSpellTranscript(){StopAudio();using(var dialog=SpellDialog("逐句原文与翻译",860,540)){int at=index;var english=new SentenceView{Dock=DockStyle.Top,Height=175,Font=GameTheme.Latin(17),ForeColor=GuildChrome.Ivory,BackColor=dialog.BackColor};english.WordClicked=word=>AddWord(Normalize(word),current.lines[at].text);dialog.Controls.Add(english);var chinese=new OutlinedLabel{Dock=DockStyle.Fill,Font=GameTheme.Body(14),ForeColor=GuildChrome.Ivory};dialog.Controls.Add(chinese);chinese.BringToFront();var footer=new FlowLayoutPanel{Dock=DockStyle.Bottom,Height=50,WrapContents=false};dialog.Controls.Add(footer);Action refresh=()=>{english.Text=current.lines[at].text;chinese.Text=current.lines[at].translation;dialog.Text="原文与翻译 · 第 "+(at+1)+" / "+current.lines.Count+" 句";};footer.Controls.Add(PartyButton("上一句",()=>{at=Math.Max(0,at-1);refresh();},160,42));footer.Controls.Add(PartyButton("下一句",()=>{at=Math.Min(current.lines.Count-1,at+1);refresh();},160,42));footer.Controls.Add(PartyButton("跳到本句",()=>{index=at;UpdateLine();dialog.Close();},190,42));refresh();dialog.ShowDialog(this);}}
}
