using System;using System.Collections.Generic;using System.Drawing;using System.Linq;using System.Windows.Forms;
public partial class Game {
 void ShowSpellQuestions(string groupId){StopAudio();var exam=activeSpellExam;var questions=exam.questions.Where(q=>groupId==null||q.group_id==groupId).ToList();if(questions.Count==0){GameMessage.Show(this,"本片段没有可用题目。");return;}int at=0;var nearby=questions.FindIndex(q=>q.start<=current.lines[index].start&&q.end>=current.lines[index].start);if(nearby>=0)at=nearby;
  using(var dialog=SpellDialog("真题练习",880,620)){var panel=new Panel{Dock=DockStyle.Fill,BackColor=dialog.BackColor};dialog.Controls.Add(panel);var heading=new OutlinedLabel{Font=GameTheme.Body(14),ForeColor=GuildChrome.Gold};panel.Controls.Add(heading);var prompt=new OutlinedLabel{Font=GameTheme.Latin(13),ForeColor=GuildChrome.Ivory};panel.Controls.Add(prompt);var options=new VNButton[4];int selected=-1;bool submitted=false;var result=new OutlinedLabel{Font=GameTheme.Body(12),ForeColor=GuildChrome.Ivory};panel.Controls.Add(result);
   Action refresh=null;for(int i=0;i<4;i++){int answer=i;options[i]=PartyButton("",()=>{if(submitted)return;selected=answer;for(int j=0;j<4;j++)options[j].Active=j==answer;},300,65);options[i].Font=GameTheme.Latin(11);panel.Controls.Add(options[i]);}
   var submit=PartyButton("提交答案",()=>{if(submitted)return;if(selected<0){result.Text="请先选择一个答案。";return;}var q=questions[at];submitted=true;string key=exam.id+":"+q.number;SpellPracticeState().answers[key]=selected;var state=TavernBusiness.State(save);string daily=state.day+":"+key;int gain=0;if(!SpellPracticeState().attempted.Contains(daily)){SpellPracticeState().attempted.Add(daily);gain=TavernBusiness.Reward(save,"listen:"+key,selected==q.answer);}result.Text=(selected==q.answer?"回答正确":"回答错误")+" · 正确答案 "+(char)('A'+q.answer)+(gain>0?" · +"+gain+" 金币":"");foreach(var option in options)option.Enabled=false;Persist();},170,42);panel.Controls.Add(submit);
   var explanation=PartyButton("查看译文与解析",()=>{if(!submitted){result.Text="提交答案后可查看解析。";return;}ShowSpellExplanation(questions[at].explanation);},210,42);panel.Controls.Add(explanation);
   var hear=PartyButton("重听对应片段",()=>{var q=questions[at];int line=current.lines.FindIndex(l=>l.start>=q.start-.2);index=Math.Max(0,line);UpdateLine();dialog.Close();StopAudio();spellReplayEndMs=(long)(q.end*1000);allPlaying=true;StartLine(true);},190,42);panel.Controls.Add(hear);
   var prev=PartyButton("上一题",()=>{if(at==0)return;at--;refresh();},145,42);panel.Controls.Add(prev);var next=PartyButton("下一题",()=>{if(at+1==questions.Count)return;at++;refresh();},145,42);panel.Controls.Add(next);var reset=PartyButton("重新作答本题",()=>{SpellPracticeState().answers.Remove(exam.id+":"+questions[at].number);refresh();Persist();},200,42);panel.Controls.Add(reset);
   refresh=()=>{var q=questions[at];string key=exam.id+":"+q.number;int answer;submitted=SpellPracticeState().answers.TryGetValue(key,out answer);selected=submitted?answer:-1;heading.Text=exam.title+" · 第 "+q.number+" 题 / "+exam.questions.Count;prompt.Text=q.prompt;for(int i=0;i<4;i++){options[i].Text=((char)('A'+i))+". "+q.options[i];options[i].Active=i==selected;options[i].Enabled=!submitted;}result.Text=submitted?(selected==q.answer?"回答正确":"回答错误")+" · 正确答案 "+(char)('A'+q.answer):"先听材料，再选择答案。首次提交计入本日训练奖励。";prev.Enabled=at>0;next.Enabled=at+1<questions.Count;};
   Action layout=()=>{int w=panel.Width,h=panel.Height;heading.Bounds=new Rectangle(0,0,w,30);prompt.Bounds=new Rectangle(0,34,w,Math.Max(40,Math.Min(85,h/6)));int top=34+prompt.Height+8,cw=(w-14)/2,ch=Math.Max(43,(h-top-160)/2);for(int i=0;i<4;i++)options[i].Bounds=new Rectangle(i%2*(cw+14),top+i/2*(ch+10),cw,ch);result.Bounds=new Rectangle(0,top+2*(ch+10),w,32);int bw=(w-20)/3;submit.Bounds=new Rectangle(0,h-100,bw,38);explanation.Bounds=new Rectangle(bw+10,h-100,bw,38);hear.Bounds=new Rectangle(2*(bw+10),h-100,bw,38);prev.Bounds=new Rectangle(0,h-48,bw,38);reset.Bounds=new Rectangle(bw+10,h-48,bw,38);next.Bounds=new Rectangle(2*(bw+10),h-48,bw,38);};panel.Resize+=(s,e)=>layout();layout();refresh();dialog.ShowDialog(this);
  }
 }
 void ShowSpellExplanation(string text){using(var dialog=SpellDialog("答案与解析",820,600)){var body=new OutlinedLabel{Dock=DockStyle.Fill,Font=GameTheme.Body(13),ForeColor=GuildChrome.Ivory};dialog.Controls.Add(body);var footer=new FlowLayoutPanel{Dock=DockStyle.Bottom,Height=50,WrapContents=false};dialog.Controls.Add(footer);int at=0;var pages=new List<string>();Action paginate=()=>{pages.Clear();string remaining=(text??"暂无文字解析。").Replace("\\n","\n");int maxWidth=Math.Max(50,dialog.ClientSize.Width-dialog.Padding.Horizontal-12),maxHeight=Math.Max(50,dialog.ClientSize.Height-dialog.Padding.Vertical-60);while(remaining.Length>0){int low=1,high=remaining.Length;while(low<high){int mid=(low+high+1)/2;if(TextRenderer.MeasureText(remaining.Substring(0,mid),body.Font,new Size(maxWidth,Int32.MaxValue),TextFormatFlags.WordBreak|TextFormatFlags.NoPadding).Height<=maxHeight)low=mid;else high=mid-1;}int count=low;if(count<remaining.Length){int breakAt=remaining.LastIndexOf('\n',count-1,count);if(breakAt>count/2)count=breakAt+1;}pages.Add(remaining.Substring(0,count));remaining=remaining.Substring(count);}if(pages.Count==0)pages.Add("暂无文字解析。");at=Math.Min(at,pages.Count-1);body.Text=pages[at];dialog.Text="答案与解析 · "+(at+1)+" / "+pages.Count+" 页";};Action refresh=()=>{body.Text=pages[at];dialog.Text="答案与解析 · "+(at+1)+" / "+pages.Count+" 页";};footer.Controls.Add(PartyButton("上一页",()=>{at=Math.Max(0,at-1);refresh();},190,42));footer.Controls.Add(PartyButton("下一页",()=>{at=Math.Min(pages.Count-1,at+1);refresh();},190,42));footer.Controls.Add(PartyButton("关闭",()=>dialog.Close(),190,42));dialog.Resize+=(s,e)=>paginate();paginate();dialog.ShowDialog(this);}}
}
