using System;
using System.Linq;
using System.Drawing;
using System.Drawing.Drawing2D;
using System.Windows.Forms;

public class StoryMapNode {public string id,name;public float x,y;public bool planned,hidden;public StoryMapNode(string key,string title,float px,float py,bool secret=false,bool future=false){id=key;name=title;x=px;y=py;hidden=secret;planned=future;}}
public partial class Game {
 public static readonly StoryMapNode[] WorldNodes={new StoryMapNode("neon-01-01","1.1 雨夜追踪",.20f,.76f),new StoryMapNode("neon-01-A","隐藏 A · 无名诊所",.21f,.42f,true),new StoryMapNode("neon-01-02","1.2 地下末班车",.43f,.79f),new StoryMapNode("neon-01-B","隐藏 B · 零号站台",.35f,.19f,true,true),new StoryMapNode("neon-01-03","1.3 失名档案",.60f,.43f),new StoryMapNode("neon-01-04","1.4 黎明信号",.85f,.21f)};
 void ShowStoryMap(){ClearPage();page="story-map";StoryRoutes.Normalize(save);var header=new FlowLayoutPanel{Dock=DockStyle.Top,Height=62,Padding=new Padding(12,5,0,0),WrapContents=false};content.Controls.Add(header);header.Controls.Add(Btn("主界面",ShowMain));header.Controls.Add(Btn("背单词赚金币",ShowRogueHome));var mapTitle=Lab("第一卷 · 霓虹失名者",17,Gold);header.Controls.Add(mapTitle);
  var detail=new FlowLayoutPanel{Dock=DockStyle.Right,Width=320,Padding=new Padding(14),FlowDirection=FlowDirection.TopDown,WrapContents=false,AutoScroll=true,BackColor=GameTheme.Navy};content.Controls.Add(detail);var canvas=new StoryMapCanvas(CachedImage(System.IO.Path.Combine(root,"assets","story","world-map.png")),WorldNodes,save,chapters){Dock=DockStyle.Fill};content.Controls.Add(canvas);canvas.BringToFront();
  Action<StoryMapNode> select=node=>{while(detail.Controls.Count>0)detail.Controls[0].Dispose();bool revealed=!node.hidden||save.storyFlags.Contains(node.id=="neon-01-A"?"clinic-discovered":"station-discovered");detail.Controls.Add(Lab(revealed?node.name:"尚未发现的支线",18,Gold));if(node.planned){detail.Controls.Add(Lab(revealed?"坐标已记录。该隐藏关的完整剧情将在后续扩展。":"地下线路还有未知的支线，试着调查列车控制台。",12,Muted));return;}var chapter=chapters.FirstOrDefault(c=>c.id==node.id);if(chapter==null)return;int stars=save.sectionStars.ContainsKey(chapter.id)?save.sectionStars[chapter.id]:0;detail.Controls.Add(Lab(new string('★',stars)+new string('☆',3-stars),24,Gold));var words=PreparationWords(chapter);int count=PreparationEngine.Count(save.rogue,chapter.id,words);bool prepared=PreparationReady(chapter);detail.Controls.Add(Lab(prepared?"词汇准备已通过 · 已掌握 "+count+" / "+words.Count:"词汇准备  "+count+" / "+words.Count,13));detail.Controls.Add(Lab(node.id=="neon-01-A"?"恢复诊所的备用电源，或保存医生的证词。道具选择会改变本关结局。":chapter.description,12,Muted));bool unlocked=SectionRules.Unlocked(chapter,chapters,save);detail.Controls.Add(Lab(unlocked?(prepared?"路线已开放 · 词汇准备已通过":"路线已开放 · 先完成本节词汇准备"):node.hidden?"雨夜两星通关后，用回声探针定位求救信号。":"前一主线小节至少两星。",11,Accent));string route=StoryRoutes.Route(save,chapter.id);if(route!="")detail.Controls.Add(Lab("已记录行动："+RouteName(route),12,Gold));Action activate=()=>{current=chapter;index=save.positions.ContainsKey(chapter.id)?Math.Min(chapter.lines.Count-1,Math.Max(0,save.positions[chapter.id])):0;if(stars==0&&!prepared)ShowStoryIntroPreview();else ShowStory();};var enter=Btn(stars>0?"继续 / 查看结算":prepared?"进入本节剧情":"观看前置剧情",activate,true);enter.Enabled=unlocked;detail.Controls.Add(enter);var prepare=Btn("本节词汇准备",()=>{current=chapter;ShowPreparationHome();});prepare.Enabled=unlocked;detail.Controls.Add(prepare);if(stars>0){var replay=Btn("重新闯关 · 尝试另一结局",()=>{current=chapter;ResetSection();ShowStory();});replay.Enabled=unlocked;detail.Controls.Add(replay);var review=Btn("复习听力 · 可开中英",()=>{current=chapter;index=0;Attempt().review=true;ShowStory();});review.Enabled=unlocked;detail.Controls.Add(review);}
   foreach(Control item in detail.Controls){item.MaximumSize=new Size(276,0);if(item is Button)item.Width=270;}
  };Action responsive=()=>{detail.Width=content.Width<1000?260:320;mapTitle.Visible=content.Width>=1000;int available=detail.ClientSize.Width-44;foreach(Control item in detail.Controls){item.MaximumSize=new Size(available,0);if(item is Button)item.Width=available-6;}};content.Resize+=(s,e)=>responsive();canvas.Selected=n=>{select(n);responsive();};select(WorldNodes.FirstOrDefault(n=>n.id==save.lastChapter)??WorldNodes[0]);responsive();
 }
 string RouteName(string route){return route=="signal"?"求救信号已定位":route=="both"?"救援 + 证词备份":route=="rescue"?"医生安全撤离":route=="record"?"证词已备份":route=="spur"?"零号站台坐标":"沿主线撤离";}
}

public class StoryMapCanvas:Control {
 readonly Image art;readonly StoryMapNode[] nodes;readonly Save save;readonly System.Collections.Generic.List<Chapter> chapters;Rectangle scene;int hovered=-1;public Action<StoryMapNode> Selected;
 public StoryMapCanvas(Image picture,StoryMapNode[] places,Save state,System.Collections.Generic.List<Chapter> list){art=picture;nodes=places;save=state;chapters=list;DoubleBuffered=true;ResizeRedraw=true;BackColor=GameTheme.Navy;}
 Point Center(StoryMapNode n){return new Point(scene.X+(int)(scene.Width*n.x),scene.Y+(int)(scene.Height*n.y));}
 bool Revealed(StoryMapNode n){return !n.hidden||save.storyFlags.Contains(n.id=="neon-01-A"?"clinic-discovered":"station-discovered");}
 bool Open(StoryMapNode n){var c=chapters.FirstOrDefault(x=>x.id==n.id);return !n.planned&&c!=null&&SectionRules.Unlocked(c,chapters,save);}
 protected override void OnPaint(PaintEventArgs e){base.OnPaint(e);var g=e.Graphics;g.InterpolationMode=InterpolationMode.NearestNeighbor;g.PixelOffsetMode=PixelOffsetMode.Half;float scale=Math.Min((Width-20)/(float)art.Width,(Height-80)/(float)art.Height);int w=(int)(art.Width*scale),h=(int)(art.Height*scale);scene=new Rectangle((Width-w)/2,(Height-60-h)/2,w,h);g.DrawImage(art,scene);using(var shade=new SolidBrush(Color.FromArgb(50,5,10,22)))g.FillRectangle(shade,scene);int[][] paths={new[]{0,2},new[]{0,1},new[]{1,2},new[]{2,3},new[]{3,4},new[]{2,4},new[]{4,5}};foreach(var path in paths){bool secret=nodes[path[0]].hidden||nodes[path[1]].hidden;using(var pen=new Pen(secret?GameTheme.Violet:GameTheme.Cyan,2)){pen.DashStyle=secret?DashStyle.Dash:DashStyle.Solid;g.DrawLine(pen,Center(nodes[path[0]]),Center(nodes[path[1]]));}}for(int i=0;i<nodes.Length;i++){var n=nodes[i];Point center=Center(n);bool open=Open(n),revealed=Revealed(n);int radius=hovered==i?19:16;GameTheme.Frame(g,new Rectangle(center.X-radius,center.Y-radius,2*radius,2*radius),GameTheme.Navy,open?GameTheme.Gold:GameTheme.Violet,false);using(var font=GameTheme.Body(13,FontStyle.Bold))GameTheme.DrawText(g,!revealed?"?":n.hidden?"✦":(i==0?"1":i==2?"2":i==4?"3":"4"),font,new Rectangle(center.X-radius,center.Y-radius,2*radius,2*radius),open?GameTheme.Gold:GameTheme.Muted,TextFormatFlags.HorizontalCenter|TextFormatFlags.VerticalCenter);string label=revealed?n.name:"未知支线";int labelWidth=Math.Max(94,Math.Min(180,scene.Width/5));var labelRect=new Rectangle(center.X-labelWidth/2,center.Y+24,labelWidth,40);using(var b=new SolidBrush(Color.FromArgb(225,12,18,31)))g.FillRectangle(b,labelRect);using(var f=GameTheme.Body(10,FontStyle.Bold))GameTheme.DrawText(g,label,f,labelRect,open?GameTheme.Ink:GameTheme.Muted,TextFormatFlags.HorizontalCenter|TextFormatFlags.VerticalCenter|TextFormatFlags.WordBreak);int stars=save.sectionStars.ContainsKey(n.id)?save.sectionStars[n.id]:0;if(stars>0)using(var f=GameTheme.Body(10))GameTheme.DrawText(g,new string('★',stars),f,new Rectangle(center.X-45,center.Y-37,90,18),GameTheme.Gold,TextFormatFlags.HorizontalCenter);}
 using(var f=GameTheme.Body(11))GameTheme.DrawText(g,"主线：两星推进    支线：线索 + 道具    每节独立词汇准备",f,new Rectangle(8,Height-52,Width-16,22),GameTheme.Muted,TextFormatFlags.HorizontalCenter);using(var f=GameTheme.Body(10))GameTheme.DrawText(g,"卷末结局：雨夜远行 / 名字归来 / 黎明之外（后续扩展）",f,new Rectangle(8,Height-28,Width-16,22),GameTheme.Gold,TextFormatFlags.HorizontalCenter);
 }
 protected override void OnMouseMove(MouseEventArgs e){base.OnMouseMove(e);int next=Array.FindIndex(nodes,n=>{var p=Center(n);return Math.Abs(e.X-p.X)<24&&Math.Abs(e.Y-p.Y)<30;});if(next!=hovered){hovered=next;Invalidate();}Cursor=hovered>=0?Cursors.Hand:Cursors.Default;}
 protected override void OnMouseClick(MouseEventArgs e){base.OnMouseClick(e);if(e.Button==MouseButtons.Left&&Selected!=null){int hit=Array.FindIndex(nodes,n=>{var p=Center(n);int labelWidth=Math.Max(94,Math.Min(180,scene.Width/5));return Math.Abs(e.X-p.X)<24&&Math.Abs(e.Y-p.Y)<24||new Rectangle(p.X-labelWidth/2,p.Y+24,labelWidth,40).Contains(e.Location);});if(hit>=0)Selected(nodes[hit]);}}
}
