using System;using System.Drawing;using System.Text.RegularExpressions;using System.Windows.Forms;

// One compact geometry for every full-width story subtitle strip.
public sealed class SubtitleLayout {
 public float Scale;public int Inset,Speaker,English,Chinese,Height;
 public const int Footer=52;
 public static void SetFont(Control control,Font font){if(control.Font.Equals(font)){font.Dispose();return;}var old=control.Font;control.Font=font;old.Dispose();}
 public SubtitleLayout(int width,int height){Scale=Math.Max(.72f,Math.Min(1.25f,Math.Min(width/1280f,height/740f)));Inset=Math.Max(24,width/12);using(var en=GameTheme.Latin(18*Scale))using(var name=GameTheme.Body(16*Scale,FontStyle.Bold))using(var zh=GameTheme.Body(17*Scale)){Speaker=name.Height+(int)(6*Scale);English=2*(int)Math.Ceiling(en.Height*1.55)+(int)(12*Scale);Chinese=2*zh.Height+(int)(8*Scale);}Height=6+Speaker+English+Chinese;}
 public static int EnglishLines(string text,Font font,int width){int rows=1;string line="";foreach(Match token in Regex.Matches(text??"",@"\S+")){string next=line.Length==0?token.Value:line+" "+token.Value;if(line.Length>0&&TextRenderer.MeasureText(next,font,new Size(int.MaxValue,int.MaxValue),TextFormatFlags.NoPadding|TextFormatFlags.NoPrefix|TextFormatFlags.SingleLine).Width>width){rows++;line=token.Value;}else line=next;}return rows;}
 public Font Fit(string text,bool english,int width,int height){float size=(english?18:17)*Scale;while(true){Font font=english?GameTheme.Latin(size):GameTheme.Body(size);int required=english?8+EnglishLines(text,font,Math.Max(30,width-22))*(int)Math.Ceiling(font.Height*1.55):TextRenderer.MeasureText(text??"",font,new Size(Math.Max(1,width-5),int.MaxValue),TextFormatFlags.NoPadding|TextFormatFlags.WordBreak).Height+4;if(required<=height||size<=6)return font;font.Dispose();size-=.5f;}}
 public static void Draw(Graphics g,Size size,string en,string zh){var l=new SubtitleLayout(size.Width,size.Height);int top=size.Height-l.Height-Footer;using(var bg=new SolidBrush(Color.FromArgb(220,15,18,35)))g.FillRectangle(bg,0,top,size.Width,l.Height);using(var bg=new SolidBrush(Color.FromArgb(245,12,15,29)))g.FillRectangle(bg,0,size.Height-Footer,size.Width,Footer);using(var edge=new Pen(Color.FromArgb(115,160,134,235),2)){g.DrawLine(edge,0,top,size.Width,top);g.DrawLine(edge,0,size.Height-Footer,size.Width,size.Height-Footer);}int width=Math.Max(30,size.Width-l.Inset*2);using(var name=GameTheme.Body(16*l.Scale,FontStyle.Bold))GameTheme.DrawText(g,"【旁白】",name,new Rectangle(l.Inset,top+6,width,l.Speaker),Color.FromArgb(255,230,205),TextFormatFlags.NoPadding);int y=top+6+l.Speaker;using(var font=l.Fit(en,true,width,l.English))GameTheme.DrawText(g,en??"",font,new Rectangle(l.Inset,y+8,width-22,l.English-8),Color.White,TextFormatFlags.NoPadding|TextFormatFlags.WordBreak);y+=l.English;using(var font=l.Fit(zh,false,width,l.Chinese))GameTheme.DrawText(g,zh??"",font,new Rectangle(l.Inset+2,y+3,width-5,l.Chinese-4),Color.White,TextFormatFlags.NoPadding|TextFormatFlags.WordBreak);}
}
