using System;using System.Collections.Generic;using System.Linq;
public class HallEmployee {
 public string name{get;set;}public int xp{get;set;}public int workXp{get;set;}public int listeningXp{get;set;}public int level{get;set;}public double fatigue{get;set;}public bool resting{get;set;}public int job{get;set;}public List<int> batch{get;set;}public double progress{get;set;}public string action{get;set;}
 public HallEmployee(){level=1;job=-1;batch=new List<int>();action="待命";}
 public int Craft{get{return 10+level*4;}}public int Efficiency{get{return 10+level*5;}}public int Service{get{return 10+level*4;}}public int Stamina{get{return 45+level*10;}}
 public int NextXp{get{return level>=5?0:level*45;}}
 public void Gain(int amount,bool listening){xp+=amount;if(listening)listeningXp+=amount;else workXp+=amount;}
 public void Grow(){if(job>=0)return;while(level<5&&xp>=NextXp){xp-=NextXp;level++;}}
}
public class HallRecipe {public string id{get;set;}public int made{get;set;}public bool enabled{get;set;}public HallRecipe(){enabled=true;}public int Rank{get{return made>=24?2:made>=8?1:0;}}}
public class HallListeningRecord {public int interruptedAttempts{get;set;}public int interruptedBest{get;set;}public int attempts{get;set;}public int independentBest{get;set;}public int assistedBest{get;set;}public int corrections{get;set;}public int lastDay{get;set;}public int dailyRewards{get;set;}public List<int> wrong{get;set;}public HallListeningRecord(){independentBest=-1;assistedBest=-1;interruptedBest=-1;wrong=new List<int>();}}
public class HallStudy {
 public bool english{get;set;}public bool chinese{get;set;}public string exam{get;set;}public string group{get;set;}public bool intensive{get;set;}public bool assisted{get;set;}public bool interrupted{get;set;}public bool started{get;set;}public bool finished{get;set;}public bool played{get;set;}public int employee{get;set;}public int question{get;set;}public int sentence{get;set;}public long position{get;set;}public Dictionary<string,int> answers{get;set;}public HallStudy(){answers=new Dictionary<string,int>();}
}
public class HallGuest {
 public bool drinkReserved{get;set;}public double departure{get;set;}public int id{get;set;}public int table{get;set;}public int stage{get;set;}public double progress{get;set;}public double wait{get;set;}public bool boosted{get;set;}public int recipe{get;set;}public int quality{get;set;}public bool regular{get;set;}
}
public class TavernHallState {
 public bool guided{get;set;}public int day{get;set;}public double elapsed{get;set;}public double arrival{get;set;}public bool open{get;set;}public bool closing{get;set;}public bool settled{get;set;}public int served{get;set;}public int revenue{get;set;}public int cost{get;set;}public int tips{get;set;}public int stock{get;set;}public int xp{get;set;}public int boosts{get;set;}public int nextId{get;set;}public int upgrade{get;set;}public int satisfaction{get;set;}public List<HallGuest> guests{get;set;}
 public int version{get;set;}public HallEmployee chef{get;set;}public HallEmployee server{get;set;}public List<HallRecipe> recipes{get;set;}public int carrots{get;set;}public int flour{get;set;}public int purchaseLimit{get;set;}public int purchased{get;set;}public bool autoBuy{get;set;}public int regularVisits{get;set;}public int stove{get;set;}public int layout{get;set;}public double fuel{get;set;}public double assistProgress{get;set;}public bool eventAccepted{get;set;}public bool eventResolved{get;set;}public int eventServed{get;set;}public bool eventPending{get;set;}public string notice{get;set;}public int guidanceSerial{get;set;}public int guidanceCount{get;set;}public int guidanceCorrect{get;set;}public RogueQuestion wordQuestion{get;set;}public string guidanceFeedback{get;set;}public Dictionary<string,HallListeningRecord> records{get;set;}public HallStudy study{get;set;}
 public TavernHallState(){day=1;stock=16;guests=new List<HallGuest>();}
 public int Level{get{return server==null?Math.Min(5,1+xp/40):server.level;}}
}
public static class TavernHall {
 public static readonly string[] Dishes={"胡萝卜浓汤","烤胡萝卜面包","香煎胡萝卜","麦香饮"};public static readonly int[] Prices={16,22,18,9};public static readonly int[] Carrots={1,1,2,0};public static readonly int[] Flour={1,2,0,1};public static readonly double[] CookTime={6,9,5,3};
 public static TavernHallState State(Save save){if(save.tavernHall==null)save.tavernHall=new TavernHallState();var s=save.tavernHall;
  if(s.guests==null)s.guests=new List<HallGuest>();if(s.chef==null)s.chef=new HallEmployee{name="莉瑟"};if(s.server==null)s.server=new HallEmployee{name="艾莉娅",workXp=s.xp,xp=s.xp};if(s.recipes==null)s.recipes=Enumerable.Range(0,4).Select(i=>new HallRecipe{id="dish"+i}).ToList();if(s.records==null)s.records=new Dictionary<string,HallListeningRecord>();if(s.version==0){s.version=1;s.carrots=24;s.flour=24;s.purchaseLimit=80;s.autoBuy=true;s.fuel=60;foreach(var g in s.guests){g.stage=Math.Min(g.stage,7);g.progress=0;}}
  return s;}
 public static void Start(TavernHallState s){if(s.open||s.closing||s.settled)return;s.open=true;s.arrival=4;s.notice="员工自动营业；学习期间仍然工作。";}
 public static bool Next(TavernHallState s){if(!s.settled||s.study!=null&&!s.study.finished)return false;s.day++;s.elapsed=0;s.arrival=0;s.open=false;s.closing=false;s.settled=false;s.served=0;s.revenue=0;s.cost=0;s.tips=0;s.satisfaction=0;s.purchased=0;s.eventAccepted=false;s.eventResolved=false;s.eventServed=0;s.eventPending=false;return true;}
 public static bool Guide(TavernHallState s){if(s.boosts>=3){s.notice="指导储备已满，仍可继续学习。";return false;}s.boosts++;s.notice="指导完成：下一份菜品品质提高，结账额外 +4 金币。";return true;}
 public static int Listen(TavernHallState s,string key,int employee,int correct,int total,bool assisted,bool interrupted,List<int> wrong){HallListeningRecord r;if(!s.records.TryGetValue(key,out r)){r=new HallListeningRecord();s.records[key]=r;}if(r.lastDay!=s.day){r.lastDay=s.day;r.dailyRewards=0;}int previous=r.assistedBest;r.attempts++;r.wrong=wrong;if(interrupted){r.interruptedAttempts++;r.interruptedBest=Math.Max(r.interruptedBest,correct);return 0;}if(assisted){r.assistedBest=Math.Max(r.assistedBest,correct);if(previous>=0&&correct>previous)r.corrections++;}else r.independentBest=Math.Max(r.independentBest,correct);if(interrupted)return 0;int amount=r.attempts==1?18+correct*12/Math.Max(1,total):r.attempts==2?8+correct*6/Math.Max(1,total):3;if(r.dailyRewards>=2)amount=0;else r.dailyRewards++;var e=employee==0?s.chef:s.server;e.Gain(amount,true);e.Grow();s.notice=e.name+"研修经验 +"+amount+"（重复练习奖励递减，每组每日最多两次）";return amount;}
 static bool Available(TavernHallState s,int dish){return s.recipes[dish].enabled&&s.carrots>=Carrots[dish]&&s.flour>=Flour[dish];}
 static void Buy(Save save){var s=State(save);if(!s.autoBuy)return;int missing=Math.Max(0,16-s.carrots)+Math.Max(0,16-s.flour);int units=Math.Min(missing,Math.Min(Math.Max(0,s.purchaseLimit-s.purchased)/2,save.rogue.coins/2));if(units<=0)return;int c=Math.Min(units,Math.Max(0,16-s.carrots));s.carrots+=c;s.flour+=units-c;int cost=units*2;s.cost+=cost;s.purchased+=cost;save.rogue.coins-=cost;}
 static void FinishJob(HallEmployee e){e.job=-1;e.batch.Clear();e.progress=0;e.Gain(3,false);e.Grow();}
 static bool Ready(HallEmployee e,double seconds){e.Grow();if(e.fatigue>=e.Stamina)e.resting=true;if(e.resting){e.action="自动休息";e.fatigue=Math.Max(0,e.fatigue-seconds*6);if(e.fatigue<=e.Stamina*.25)e.resting=false;return false;}return true;}
 public static void Tick(Save save,double seconds){var s=State(save);if(!s.open&&!s.closing)return;if(seconds<=0)return;while(seconds>.10001){Step(save,.1);seconds-=.1;}Step(save,seconds);}
 static void Step(Save save,double dt){var s=State(save);if(!s.open&&!s.closing)return;s.elapsed+=dt;if(s.elapsed>=210){s.open=false;s.closing=true;}Buy(save);foreach(var departing in s.guests.Where(g=>g.stage==6||g.stage==7))departing.departure+=dt;
  if(s.day>=2&&!s.eventResolved&&!s.eventAccepted&&s.elapsed>=35)s.eventPending=true;
  s.fuel=Math.Max(0,s.fuel-dt*.12);
  if(s.open){s.arrival+=dt;if(s.arrival>=11&&s.guests.Count<4){var menu=Enumerable.Range(0,4).Where(i=>Available(s,i)).ToList();if(menu.Count>0){int seat=Enumerable.Range(0,4).First(i=>!s.guests.Any(g=>g.table==i));int dish=menu[s.nextId%menu.Count];s.guests.Add(new HallGuest{id=s.nextId++,table=seat,recipe=dish,regular=s.regularVisits>=3&&s.nextId%4==0});s.arrival=0;}else s.notice="菜单缺料，自动停售；可采购或调整补购额度。";}}
  foreach(var g in s.guests.ToList()){if(g.stage==0||g.stage==7){g.progress+=dt;if(g.progress>=3){g.progress=0;if(g.stage==7)s.guests.Remove(g);else g.stage=1;}}else if(g.stage==4){g.progress+=dt;if(g.progress>=10){g.progress=0;g.stage=5;}}else g.wait+=dt;}
  foreach(var stranded in s.guests.Where(g=>g.stage==2&&!g.drinkReserved&&!Available(s,g.recipe)&&s.closing&&g.wait>=45).ToList()){stranded.stage=7;stranded.progress=0;s.notice="缺料订单已取消，不收取费用；可补购后继续营业。";}Chef(s,dt);Server(save,dt);s.stock=s.carrots+s.flour;s.xp=s.server.workXp;
  if(s.closing&&s.guests.Count==0){s.closing=false;s.settled=true;s.chef.action=s.chef.resting?"自动休息":"待命";s.server.action=s.server.resting?"自动休息":"待命";s.notice="本日营业完成：收入 "+s.revenue+" − 采购 "+s.cost+" = 净收益 "+(s.revenue-s.cost)+"。题组结束后可沿用安排开店。";}
 }
 static void Chef(TavernHallState s,double dt){var e=s.chef;if(!Ready(e,dt))return;
  if(e.job<0){if(s.fuel<=5){s.assistProgress+=dt;e.action="补柴";if(s.assistProgress>=3){s.fuel=60;s.assistProgress=0;e.Gain(2,false);}return;}var jobs=s.guests.Where(g=>g.stage==2&&g.recipe!=3&&Available(s,g.recipe)).OrderByDescending(g=>g.wait).Take(e.level>=3&&s.stove>0?2:1).ToList();if(jobs.Count==0){e.action="清洗厨具";e.fatigue=Math.Max(0,e.fatigue-dt*2);return;}e.job=jobs[0].id;e.batch.Clear();foreach(var g in jobs){if(!Available(s,g.recipe))continue;s.carrots-=Carrots[g.recipe];s.flour-=Flour[g.recipe];g.stage=8;e.batch.Add(g.id);}e.progress=0;}
  var active=s.guests.Where(g=>e.batch.Contains(g.id)).ToList();if(active.Count==0){FinishJob(e);return;}e.progress+=dt*(1+e.Efficiency*.018)*(e.fatigue>e.Stamina*.75?.8:1);e.fatigue+=dt;double duration=active.Max(g=>CookTime[g.recipe])/(1+s.recipes[active[0].recipe].Rank*.12)+6+s.layout*1.3;e.action=e.progress<2?"拿取食材":e.progress<5?(e.level>=3?"双份切配":"切配"):e.progress<duration-1.5?"烹饪":"装盘";
  if(e.progress>=duration){foreach(var g in active){s.recipes[g.recipe].made++;g.quality=1+e.Craft/8+s.recipes[g.recipe].Rank+(e.level>=5?3:0);g.boosted=s.boosts>0;if(g.boosted)s.boosts--;g.stage=3;g.progress=0;}FinishJob(e);}
 }
 static void Server(Save save,double dt){var s=State(save);var e=s.server;if(!Ready(e,dt))return;
  if(e.job<0){var job=s.guests.Where(g=>g.stage==1||g.stage==3||g.stage==5||g.stage==6||g.stage==2&&g.recipe==3).OrderBy(g=>g.stage==3?0:g.stage==5?1:g.stage==6?2:3).ThenByDescending(g=>g.wait).FirstOrDefault();if(job==null){e.action="待命 / 整理杯碟";e.fatigue=Math.Max(0,e.fatigue-dt*2);return;}if(job.stage==2&&!Available(s,3)){s.notice="饮品缺料，等待自动补购。";return;}e.job=job.id;e.batch=new List<int>{job.id};if(job.stage==3&&e.level>=3)e.batch.AddRange(s.guests.Where(g=>g.stage==3&&g.id!=job.id).Take(1).Select(g=>g.id));e.progress=0;}
  var active=s.guests.Where(g=>e.batch.Contains(g.id)).ToList();if(active.Count==0){FinishJob(e);return;}int stage=active[0].stage;if(stage==2&&!active[0].drinkReserved){if(!Available(s,3)){e.job=-1;e.batch.Clear();e.progress=0;e.action="等待饮品食材";return;}s.flour--;active[0].drinkReserved=true;}e.action=stage==1?"接待点单":stage==2?"备饮":stage==3?(active.Count>1?"双盘送餐":"送餐"):stage==5?"结账":"收桌";double duration=((stage==3?6+s.layout*2:stage==6?4:3)+(stage==2?0:4))*(stage==3?active.Count:1);e.progress+=dt*(1+e.Efficiency*.018+s.upgrade*.18)*(e.fatigue>e.Stamina*.75?.8:1);e.fatigue+=dt;foreach(var g in active)g.progress=e.progress;
  if(e.progress<duration)return;foreach(var g in active){g.progress=0;if(stage==1)g.stage=2;else if(stage==2){s.recipes[3].made++;g.stage=3;g.quality=e.Craft/8;}else if(stage==3)g.stage=4;else if(stage==5){int satisfaction=Math.Max(55,100-(int)Math.Max(0,g.wait-30)/3);int tip=satisfaction>=85?2+e.Service/6+(e.level>=5?2:0):0;int amount=Prices[g.recipe]+g.quality+tip+(g.boosted?4:0)+(g.regular?2:0);s.revenue+=amount;s.tips+=tip;s.served++;s.satisfaction+=satisfaction;save.rogue.coins+=amount;if(satisfaction>=85)s.regularVisits++;if(g.boosted)s.notice=Dishes[g.recipe]+"指导出品结账：额外 +4 金币";if(s.eventAccepted&&!s.eventResolved&&++s.eventServed>=3){s.eventResolved=true;s.eventPending=false;save.rogue.coins+=18;s.revenue+=18;s.notice="团体订餐完成 · 奖励18金币";}g.stage=6;}else g.stage=7;}FinishJob(e);
 }
 public static readonly string[] Stages={"入座","等待点单","等待制作","等待送餐","用餐","结账","等待收桌","离店","厨房制作中"};
}
