using System;using System.Linq;using System.Collections.Generic;using System.Drawing;using System.Windows.Forms;
public class HallActionButton:VNButton {
 bool over;public bool LeftAligned;
 public HallActionButton(){Font=GameTheme.Body(11);Margin=new Padding(2);}
 protected override void OnMouseEnter(EventArgs e){over=true;base.OnMouseEnter(e);}
 protected override void OnMouseLeave(EventArgs e){over=false;base.OnMouseLeave(e);}
 protected override void OnPaint(PaintEventArgs e){var g=e.Graphics;var r=Rectangle.Inflate(ClientRectangle,-2,-2);if(r.Width<5||r.Height<5)return;using(var b=new SolidBrush(Active?Color.FromArgb(58,81,66):over||Focused?Color.FromArgb(43,66,58):Color.FromArgb(24,45,42)))g.FillPolygon(b,GameTheme.Outline(r,6));using(var pen=new Pen(Active?GuildChrome.Gold:Color.FromArgb(102,113,85),Active?2:1))g.DrawPolygon(pen,GameTheme.Outline(r,6));GameTheme.DrawText(g,Text,Font,Rectangle.Inflate(r,-5,0),Enabled?GuildChrome.Ivory:GuildChrome.Muted,TextFormatFlags.WordBreak|TextFormatFlags.VerticalCenter|TextFormatFlags.NoPadding|(LeftAligned?TextFormatFlags.Left:TextFormatFlags.HorizontalCenter));}
}
public class HallFramePanel:Panel {
 public HallFramePanel(){DoubleBuffered=true;BackColor=Color.FromArgb(25,53,50);Padding=new Padding(12);}
 protected override void OnPaint(PaintEventArgs e){base.OnPaint(e);using(var p=new Pen(Color.FromArgb(119,126,88)))e.Graphics.DrawPolygon(p,GameTheme.Outline(Rectangle.Inflate(ClientRectangle,-2,-2),8));}
}
// Uses the same clickable English renderer as main-story dialogue, with word-safe pagination.
public sealed class HallSentencePanel:UserControl {
 public readonly SentenceView English;public readonly HallPagedText Chinese;public Action<string> WordClicked;
 Panel pager;VNButton prev,next;Label position;string english="",chinese="";bool showEnglish,showChinese;int at;List<string> pages=new List<string>();
 public HallSentencePanel(){BackColor=Color.FromArgb(25,53,50);Padding=new Padding(12,4,12,4);English=new SentenceView{ForeColor=GuildChrome.Ivory,Font=GameTheme.Latin(18),BackColor=BackColor};Chinese=new HallPagedText{Font=GameTheme.Body(18),BackColor=BackColor};English.WordClicked=w=>{if(WordClicked!=null)WordClicked(w);};Controls.Add(English);Controls.Add(Chinese);pager=new Panel{Height=24};prev=new VNButton{Icon="prev",Width=32,Dock=DockStyle.Left,AccessibleName="上一页英文"};next=new VNButton{Icon="next",Width=32,Dock=DockStyle.Right,AccessibleName="下一页英文"};position=new Label{Dock=DockStyle.Fill,TextAlign=ContentAlignment.MiddleCenter,ForeColor=GuildChrome.Muted};pager.Controls.Add(position);pager.Controls.Add(prev);pager.Controls.Add(next);Controls.Add(pager);prev.Click+=(s,e)=>{at=Math.Max(0,at-1);RenderPage();};next.Click+=(s,e)=>{at=Math.Min(pages.Count-1,at+1);RenderPage();};Resize+=(s,e)=>LayoutSentence();}
 public void SetSentence(string en,string zh,bool enOn,bool zhOn){bool changed=english!=(en??"")||chinese!=(zh??"")||showEnglish!=enOn||showChinese!=zhOn;english=en??"";chinese=zh??"";showEnglish=enOn;showChinese=zhOn;if(!changed)return;at=0;LayoutSentence();}
 public int PageCount{get{return pages.Count;}} public int DialogueHeight(string en,string zh,bool enOn,bool zhOn){int w=Math.Max(30,Width-24);int englishHeight=enOn?8+SubtitleLayout.EnglishLines(en??"",English.Font,w-22)*(int)Math.Ceiling(English.Font.Height*1.55):0;int chineseHeight=zhOn?Math.Max(26,TextRenderer.MeasureText(zh??"",Chinese.Font,new Size(Math.Max(20,w-12),Int32.MaxValue),TextFormatFlags.WordBreak).Height+8):0;return Math.Max(250,englishHeight+chineseHeight+(enOn&&zhOn?6:0)+86);}
 void LayoutSentence(){int w=Math.Max(30,Width-24),h=Math.Max(24,Height-10);English.Visible=showEnglish;Chinese.Visible=showChinese;int zhHeight=showChinese?(showEnglish?Math.Min((int)(h*.45),Math.Max(26,TextRenderer.MeasureText(chinese,Chinese.Font,new Size(Math.Max(20,w-12),Int32.MaxValue),TextFormatFlags.WordBreak).Height+8)):h):0;int enHeight=showEnglish?h-zhHeight-(showChinese?6:0):0;int lineHeight=(int)Math.Ceiling(English.Font.Height*1.55);bool needsPager=showEnglish&&8+SubtitleLayout.EnglishLines(english,English.Font,w-22)*lineHeight>enHeight;int textHeight=Math.Max(20,enHeight-(needsPager?24:0));English.Bounds=new Rectangle(12,2,w,textHeight);Chinese.Bounds=new Rectangle(12,enHeight+(showEnglish?6:0),w,Math.Max(20,zhHeight));pager.Bounds=new Rectangle(12,Math.Max(0,enHeight-24),w,24);pages.Clear();int rows=Math.Max(1,(textHeight-8)/lineHeight);string part="";foreach(var token in english.Split(new[]{' ','\n','\r'},StringSplitOptions.RemoveEmptyEntries)){var trial=part.Length==0?token:part+" "+token;if(needsPager&&part.Length>0&&SubtitleLayout.EnglishLines(trial,English.Font,w-22)>rows){pages.Add(part);part=token;}else part=trial;}if(part.Length>0)pages.Add(part);if(pages.Count==0)pages.Add("");at=Math.Min(at,pages.Count-1);pager.Visible=showEnglish&&pages.Count>1;Chinese.Content=chinese;RenderPage();}
 void RenderPage(){English.Text=pages[at];prev.Enabled=at>0;next.Enabled=at+1<pages.Count;position.Text="英文 "+(at+1)+" / "+pages.Count;}
}
public sealed class HallDialogueOverlay:Panel {
 public HallDialogueOverlay(){SetStyle(ControlStyles.SupportsTransparentBackColor|ControlStyles.UserPaint|ControlStyles.AllPaintingInWmPaint|ControlStyles.OptimizedDoubleBuffer,true);BackColor=Color.Transparent;Padding=new Padding(18,12,18,8);}
 protected override void OnPaint(PaintEventArgs e){base.OnPaint(e);using(var b=new SolidBrush(Color.FromArgb(210,14,35,32)))e.Graphics.FillPolygon(b,GameTheme.Outline(Rectangle.Inflate(ClientRectangle,-2,-2),8));using(var p=new Pen(Color.FromArgb(170,174,147,83)))e.Graphics.DrawPolygon(p,GameTheme.Outline(Rectangle.Inflate(ClientRectangle,-2,-2),8));}
}