using System;using System.IO;using System.Linq;using System.Drawing;using System.Drawing.Drawing2D;using System.Windows.Forms;using System.Collections.Generic;
// Paged text keeps long exam options and explanations accessible without native scrollbars.
public sealed class HallPagedText:UserControl {
 Label body,counter;Panel footer;VNButton previous,next;string text="";int at;bool layingOut;List<string> pages=new List<string>();
 public HallPagedText(){BackColor=Color.FromArgb(25,53,50);body=new Label{Dock=DockStyle.Fill,ForeColor=GuildChrome.Ivory,Font=GameTheme.Body(12),Padding=new Padding(4),UseMnemonic=false};footer=new Panel{Dock=DockStyle.Bottom,Height=25,Visible=false};previous=new VNButton{Icon="prev",Dock=DockStyle.Left,Width=32,AccessibleName="上一页文本"};next=new VNButton{Icon="next",Dock=DockStyle.Right,Width=32,AccessibleName="下一页文本"};counter=new Label{Dock=DockStyle.Fill,ForeColor=GuildChrome.Muted,TextAlign=ContentAlignment.MiddleCenter};footer.Controls.Add(counter);footer.Controls.Add(previous);footer.Controls.Add(next);Controls.Add(body);Controls.Add(footer);previous.Click+=(s,e)=>{at=Math.Max(0,at-1);ShowPage();};next.Click+=(s,e)=>{at=Math.Min(pages.Count-1,at+1);ShowPage();};Resize+=(s,e)=>Paginate();}
 public string LiveContent{set{if(text==value)return;int previous=at;text=value??"";Paginate();at=Math.Min(previous,pages.Count-1);ShowPage();}}
 public string Content{get{return text;}set{if(text==value)return;text=value??"";at=0;Paginate();}}
 protected override void OnFontChanged(EventArgs e){base.OnFontChanged(e);if(body!=null){body.Font=Font;Paginate();}}
 void Paginate(){if(layingOut||Width<15||Height<15)return;layingOut=true;try{int w=Math.Max(20,Width-12);bool needs=TextRenderer.MeasureText(text,body.Font,new Size(w,Int32.MaxValue),TextFormatFlags.WordBreak).Height>Height-8;footer.Visible=needs;int h=Math.Max(8,Height-8-(needs?25:0));pages.Clear();string remaining=text;while(remaining.Length>0){int lo=1,hi=remaining.Length;while(lo<hi){int mid=(lo+hi+1)/2;if(TextRenderer.MeasureText(remaining.Substring(0,mid),body.Font,new Size(w,Int32.MaxValue),TextFormatFlags.WordBreak).Height<=h)lo=mid;else hi=mid-1;}if(lo<remaining.Length){int space=remaining.LastIndexOf(' ',lo-1,lo);if(space>lo/2)lo=space+1;}pages.Add(remaining.Substring(0,lo));remaining=remaining.Substring(lo);}if(pages.Count==0)pages.Add("");at=Math.Min(at,pages.Count-1);ShowPage();}finally{layingOut=false;}}
 void ShowPage(){if(pages.Count==0)return;body.Text=pages[at];previous.Enabled=at>0;next.Enabled=at+1<pages.Count;counter.Text=(at+1)+" / "+pages.Count;}
}
public sealed partial class TavernHallCanvas:Control {
 int hoverTable=-1;public Image Art,Server,Clerk,Guest,Owner,WorkFrames,KitchenArt;public TavernHallState State;public Action Kitchen,Inspect;public double Animation;public string Subtitle;
 protected override CreateParams CreateParams{get{var p=base.CreateParams;p.ExStyle|=0x02000000;return p;}} protected override void OnPaintBackground(PaintEventArgs e){} public TavernHallCanvas(){DoubleBuffered=true;BackColor=Color.FromArgb(9,24,22);}
 public int RightPaneWidth; RectangleF View{get{float availableWidth=Math.Max(1,Width-RightPaneWidth);float scale=Math.Min(availableWidth/1400f,Height/1132f);return new RectangleF((availableWidth-1400*scale)/2,(Height-1132*scale)/2,1400*scale,1132*scale);}}
 static PointF[] Seats=HallNavigation.Seats;
 static PointF Door=new PointF(487,462),Bar=new PointF(727,563),Aisle=new PointF(674,648),KitchenDoor=new PointF(1180,785);
 static PointF Blend(PointF a,PointF b,double t){return new PointF(a.X+(b.X-a.X)*(float)t,a.Y+(b.Y-a.Y)*(float)t);}
 static PointF Route(PointF a,PointF via,PointF b,double t){return HallWalking.Via(a,via,b,t);}
 void Sprite(Graphics g,Image art,PointF p,float height,string action){if(art==null)return;int pose=(int)(Animation*4)%4;bool working=action!="待命"&&action!="自动休息";float bob=working?(pose==1||pose==3?2:0):0;float width=height*art.Width/art.Height;if(WorkFrames!=null&&(Object.ReferenceEquals(art,Server)||Object.ReferenceEquals(art,Clerk))){int row=Object.ReferenceEquals(art,Server)?0:1;int cellWidth=WorkFrames.Width/4,cellHeight=WorkFrames.Height/2;int frame=working?pose:0;g.DrawImage(WorkFrames,new RectangleF(p.X-height/2,p.Y-height-bob,height,height),new RectangleF(frame*cellWidth,row*cellHeight,cellWidth,cellHeight),GraphicsUnit.Pixel);}else g.DrawImage(art,p.X-width/2,p.Y-height-bob,width,height);if(working){using(var b=new SolidBrush(Color.FromArgb(224,184,113))){float hand=p.X+width*.22f;g.FillRectangle(b,hand,p.Y-32-(pose%2)*4,5,5);if(action.Contains("切配"))g.FillRectangle(b,hand+4,p.Y-36-(pose%2)*6,12,3);if(action=="收桌")g.FillRectangle(b,hand+pose%2*5,p.Y-18,12,4);}}}
 void DrawTag(Graphics g,string text,PointF p){using(var font=GameTheme.Body(13)){SizeF size=g.MeasureString(text,font);var box=new RectangleF(p.X-size.Width/2-6,p.Y-104,size.Width+12,24);using(var b=new SolidBrush(Color.FromArgb(25,53,55)))g.FillRectangle(b,box);using(var pen=new Pen(GuildChrome.Gold,2))g.DrawRectangle(pen,box.X,box.Y,box.Width,box.Height);using(var b=new SolidBrush(GuildChrome.Ivory))g.DrawString(text,font,b,box.X+6,box.Y+2);}}
 protected override void OnPaint(PaintEventArgs e){base.OnPaint(e);if(State==null||Art==null)return;var v=View;var g=e.Graphics;g.Clear(BackColor);g.TranslateTransform(v.X,v.Y);g.ScaleTransform(v.Width/1400,v.Height/1132);g.InterpolationMode=InterpolationMode.NearestNeighbor;g.PixelOffsetMode=PixelOffsetMode.Half;g.DrawImage(Art,0,0,1400,1132);
  OwnerAction(g);BarFront(g);var employee=State.server;var active=State.guests.FirstOrDefault(c=>c.id==employee.job);if(active!=null&&active.stage==3&&employee.batch.Count>1){int target=Math.Min(employee.batch.Count-1,(int)(employee.progress/(10+State.layout*2)));active=State.guests.FirstOrDefault(c=>c.id==employee.batch[target])??active;}PointF server=active!=null&&active.stage!=2?HallNavigation.Approaches[active.table]:HallNavigation.CounterFor(State.layout);var serverPose=Pose("server",server,true);var actors=new List<KeyValuePair<float,Action>>();
  foreach(var guest in State.guests){var c=guest;if((c.stage==6||c.stage==7)&&c.departure>=3)continue;PointF pos=Seats[c.table];bool walking=c.stage==0||c.stage==6||c.stage==7;if(c.stage==0)pos=HallNavigation.Route(HallNavigation.Entry,HallNavigation.Approaches[c.table],Math.Min(1,c.progress/3));if(c.stage==6||c.stage==7)pos=HallNavigation.Route(HallNavigation.Approaches[c.table],HallNavigation.Entry,Math.Min(1,c.departure/3));PointF location=pos;actors.Add(new KeyValuePair<float,Action>(pos.Y,()=>{if(walking)Walker(g,"townsperson",Guest,location,94,"行走","guest"+c.id,false);else{GuestAction(g,c,location);ChairFront(g,c.table);if(c.table==hoverTable)DrawTag(g,(c.regular?"熟客":c.id%2==0?"镇民":"冒险者")+" · "+TavernHall.Stages[c.stage],location);}}));}
  actors.Add(new KeyValuePair<float,Action>(serverPose.position.Y,()=>{Walker(g,"aelia",Server,server,103,employee.action,"server",true);DrawTag(g,employee.action,serverPose.position);}));foreach(var actor in actors.OrderBy(a=>a.Key))actor.Value();
  if(KitchenArt!=null){g.DrawImage(KitchenArt,new Rectangle(955,40,405,245));using(var pen=new Pen(GuildChrome.Gold,3))g.DrawRectangle(pen,955,40,405,245);}PointF chef=new PointF(1130,235);if(State.chef.action=="拿取食材")chef=Blend(new PointF(1205,235),chef,Math.Min(1,State.chef.progress/2));Walker(g,"lyse",Clerk,chef,102,State.chef.action,"chef",true);chef=Pose("chef",chef,true).position;DrawTag(g,"厨房 · "+State.chef.action,new PointF(1155,180));g.ResetTransform();}
 protected override void OnMouseMove(MouseEventArgs e){base.OnMouseMove(e);var v=View;if(v.Width<=0)return;float x=(e.X-v.X)*1400/v.Width,y=(e.Y-v.Y)*1132/v.Height;int next=-1;foreach(var c in State.guests)if(c.stage>0&&c.stage<6&&Math.Abs(x-Seats[c.table].X)<55&&y>Seats[c.table].Y-100&&y<Seats[c.table].Y+15)next=c.table;if(next!=hoverTable){hoverTable=next;Invalidate();}}
 protected override void OnMouseLeave(EventArgs e){base.OnMouseLeave(e);hoverTable=-1;Invalidate();} protected override void OnMouseClick(MouseEventArgs e){base.OnMouseClick(e);var v=View;float x=(e.X-v.X)*1400/v.Width;if(x>1000){if(Kitchen!=null)Kitchen();}else if(Inspect!=null)Inspect();}
}
public partial class Game {
 bool hallListeningQuiet;Action hallRefreshManagement;Action hallRefreshAudio;Action hallSaveStudy;int hallManagementTab=-1;HallDialogueOverlay hallDialogue;
 void OpenHallManagement(int tab){hallManagementTab=tab;ShowTavernHall();}
 void ShowTavernHall(){ClearPage();page="tavern-hall";var state=TavernHall.State(save);bool paused=false;int speed=1;double autosave=0,animation=0;
  var screen=new TableLayoutPanel{Dock=DockStyle.Fill,ColumnCount=1,RowCount=3,BackColor=Color.FromArgb(14,31,29),Padding=new Padding(8)};screen.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,100));screen.RowStyles.Add(new RowStyle(SizeType.Absolute,58));screen.RowStyles.Add(new RowStyle(SizeType.Percent,100));screen.RowStyles.Add(new RowStyle(SizeType.Absolute,28));content.Controls.Add(screen);
  var header=new TableLayoutPanel{Dock=DockStyle.Fill,ColumnCount=6,BackColor=Color.FromArgb(25,48,43)};header.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,100));foreach(int w in new[]{108,74,74,94,90})header.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute,w));screen.Controls.Add(header,0,0);var hud=new Label{Dock=DockStyle.Fill,Font=GameTheme.Body(12),ForeColor=Gold,Padding=new Padding(8,4,0,0)};header.Controls.Add(hud,0,0);
  var start=HallAction("开门营业",()=>{if(state.open){state.open=false;state.closing=true;}else{if(state.settled&&!TavernHall.Next(state)){state.notice="题组保留中，请完成或结束本组后开始次日。";return;}TavernHall.Start(state);}Persist();});var pause=HallAction("暂停",()=>paused=!paused);var fast=HallAction("速度 ×1",()=>speed=speed==1?2:speed==2?4:1);var back=HallAction("返回",()=>{if(hallSaveStudy!=null)hallSaveStudy();CloseHallListening(true);Persist();ShowTavernPreparation();});header.Controls.Add(start,1,0);Action management=null;header.Controls.Add(HallAction("经营",()=>management()),2,0);header.Controls.Add(pause,3,0);header.Controls.Add(fast,4,0);header.Controls.Add(back,5,0);
  var shell=new Panel{Dock=DockStyle.Fill,BackColor=screen.BackColor};screen.Controls.Add(shell,0,1);
  string folder=Path.Combine(root,"assets","tavern","management");string art=Path.Combine(folder,"hall-empty.png");if(!File.Exists(art))art=Path.Combine(folder,"hall-approved-original.png");var scene=new TavernHallCanvas{Dock=DockStyle.Fill,Art=CachedImage(art),Server=CachedImage(Path.Combine(folder,"aelia-work.png")),Clerk=CachedImage(Path.Combine(folder,"lyse-work.png")),Guest=CachedImage(Path.Combine(folder,"customer-townsperson-v2.png")),Owner=CachedImage(Path.Combine(folder,"luchuan-counter.png")),WorkFrames=CachedImage(Path.Combine(folder,"work-actions-4frames.png")),KitchenArt=CachedImage(Path.Combine(root,"chapters","art","tavern","chapter-one-kitchen.png")),State=state};scene.LoadWalking(folder);shell.Controls.Add(scene);hallDialogue=new HallDialogueOverlay{Dock=DockStyle.None,Height=250,Visible=false};scene.Controls.Add(hallDialogue);
  var panel=new HallFramePanel{Dock=DockStyle.Fill,Padding=new Padding(12,8,12,8)};panel.Dock=DockStyle.Right;scene.Controls.Add(panel);hallDialogue.BringToFront();var right=new TableLayoutPanel{Dock=DockStyle.Fill,ColumnCount=1,RowCount=2,BackColor=panel.BackColor};right.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,100));right.RowStyles.Add(new RowStyle(SizeType.Absolute,42));right.RowStyles.Add(new RowStyle(SizeType.Percent,100));panel.Controls.Add(right);var tabs=new TableLayoutPanel{Dock=DockStyle.Fill,ColumnCount=2};foreach(float w in new[]{50f,50f})tabs.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,w));right.Controls.Add(tabs,0,0);var body=new Panel{Dock=DockStyle.Fill,BackColor=panel.BackColor,Padding=new Padding(0,8,0,0)};right.Controls.Add(body,0,1);var tabButtons=new List<VNButton>();
  Action<string> show=kind=>{hallRefreshManagement=null;scene.Guiding=kind=="指导";hallDialogue.Visible=false;while(hallDialogue.Controls.Count>0)hallDialogue.Controls[0].Dispose();if(hallSaveStudy!=null)hallSaveStudy();if(kind!="听力")CloseHallListening(false);while(body.Controls.Count>0)body.Controls[0].Dispose();foreach(var b in tabButtons)b.Active=b.AccessibleName==kind;if(kind=="指导")BuildHallGuidance(body,state);else if(kind=="听力")BuildHallListening(body,state);else BuildHallManagement(body,state,()=>paused,b=>paused=b);};foreach(string label in new[]{"指导","听力"}){string chosen=label;var b=HallAction(label=="指导"?"英语指导":label=="听力"?"听力研修":"经营",()=>show(chosen));b.AccessibleName=label;tabButtons.Add(b);tabs.Controls.Add(b);}  var notice=new Label{Dock=DockStyle.Fill,ForeColor=GuildChrome.Muted,Font=GameTheme.Body(10),TextAlign=ContentAlignment.MiddleLeft};screen.Controls.Add(notice,0,2);tips.SetToolTip(notice,state.notice);scene.Kitchen=()=>show("经营");scene.Inspect=()=>show("经营");Action refresh=()=>{hud.Text="六级物语 · 酒馆  /  第 "+state.day+" 日\n金币 "+save.rogue.coins+"   接待 "+state.served+" / 6   "+(state.settled?"已打烊":state.closing?"处理余单":state.open?"营业中":"准备中")+"   指导 "+state.boosts+" / 3";start.Text=state.settled?"沿用安排 · 次日":state.open?"停止迎客":state.closing?"处理余单":"开门营业";start.Enabled=!state.closing;pause.Text=paused?"继续":"暂停";fast.Text="速度 ×"+speed;notice.Text=state.notice;tips.SetToolTip(notice,state.notice);scene.Animation=animation;if(hallRefreshAudio!=null)hallRefreshAudio();if(hallRefreshManagement!=null)hallRefreshManagement();scene.Invalidate();};Action resizeHall=()=>{panel.Width=(int)Math.Max(380,Math.Min(510,shell.Width*.40f));scene.RightPaneWidth=panel.Width;hallDialogue.Bounds=new Rectangle(0,scene.Height-hallDialogue.Height,scene.Width,hallDialogue.Height);scene.Invalidate();};hallDialogue.SizeChanged+=(o,e)=>{hallDialogue.Bounds=new Rectangle(0,scene.Height-hallDialogue.Height,scene.Width,hallDialogue.Height);};shell.Resize+=(o,e)=>resizeHall();resizeHall();management=()=>{var previousRefresh=hallRefreshManagement;var previousAudio=hallRefreshAudio;var previousSave=hallSaveStudy;using(var dialog=new PixelFrame{Text="酒馆经营",Size=new Size(620,650),MinimumSize=new Size(500,520),StartPosition=FormStartPosition.CenterParent}){var managementBody=new Panel{Dock=DockStyle.Fill,BackColor=Color.FromArgb(25,53,55),Padding=new Padding(12)};dialog.Controls.Add(managementBody);BuildHallManagement(managementBody,state,()=>paused,value=>paused=value);dialog.ShowDialog(this);}hallRefreshManagement=previousRefresh;hallRefreshAudio=previousAudio;hallSaveStudy=previousSave;};scene.Kitchen=management;scene.Inspect=management;show(state.study!=null&&!state.study.finished?"听力":"指导");hallManagementTab=-1;
  var timer=new Timer{Interval=80};timer.Tick+=(o,e)=>{if(!paused){TavernHall.Tick(save,.08*speed);animation+=.08*speed;}autosave+=.08;if(autosave>=5){autosave=0;if(hallSaveStudy!=null)hallSaveStudy();Persist();}refresh();};scene.Disposed+=(o,e)=>{timer.Stop();timer.Dispose();if(hallSaveStudy!=null)hallSaveStudy();CloseHallListening(true);Persist();};refresh();timer.Start();}
 HallActionButton HallAction(string text,Action action){var b=new HallActionButton{Text=text,Dock=DockStyle.Fill};b.Click+=(s,e)=>action();return b;}
 TableLayoutPanel HallRows(Control parent,int count){var table=new TableLayoutPanel{Dock=DockStyle.Fill,ColumnCount=1,RowCount=count,BackColor=Color.FromArgb(25,53,55)};table.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,100));for(int i=0;i<count;i++)table.RowStyles.Add(new RowStyle(SizeType.Percent,100f/count));parent.Controls.Add(table);return table;}
 void HallButton(TableLayoutPanel rows,int row,string text,Action action){var b=HallAction(text,action);b.Font=GameTheme.Body(11);rows.Controls.Add(b,0,row);}
 void BuildHallGuidance(Panel parent,TavernHallState s){hallRefreshAudio=null;hallSaveStudy=null;var heading=new OutlinedLabel{Text="英语指导 · 选择词库",Font=GameTheme.Body(15),ForeColor=GameTheme.Gold};var progress=new HallPagedText{Font=GameTheme.Body(11)};parent.Controls.Add(heading);parent.Controls.Add(progress);var choices=new List<VNButton>();Action refresh=()=>{string mode=ExpeditionVocabulary.Profile(save.rogue).mode;progress.Content=VocabularyProgressText(mode)+"\n与支线远征共享学习进度";foreach(var button in choices){button.Active=button.AccessibleName==mode;button.Text=(button.Active?"●  ":"○  ")+button.AccessibleName;button.Invalidate();}};foreach(string name in new[]{"四级词汇","六级词汇","四六级混合"}){string selected=name;var button=HallAction(name,()=>{var profile=ExpeditionVocabulary.Profile(save.rogue);if(profile.mode!=selected){profile.mode=selected;s.wordQuestion=null;s.guidanceFeedback=null;}refresh();Persist();});button.Dock=DockStyle.None;button.AccessibleName=name;choices.Add(button);parent.Controls.Add(button);}var start=PartyButton("开始背单词",()=>{while(parent.Controls.Count>0)parent.Controls[0].Dispose();BuildHallGuidancePractice(parent,s);},200,42);parent.Controls.Add(start);Action layout=()=>{int width=Math.Max(80,parent.ClientSize.Width-16);heading.Bounds=new Rectangle(8,8,width,32);progress.Bounds=new Rectangle(8,48,width,68);for(int i=0;i<choices.Count;i++)choices[i].Bounds=new Rectangle(8,128+i*50,width,42);start.Bounds=new Rectangle(8,290,width,42);};parent.Resize+=(o,e)=>{if(!heading.IsDisposed)layout();};refresh();layout();}
 void BuildHallGuidancePractice(Panel parent,TavernHallState s){hallRefreshAudio=null;hallSaveStudy=null;string mode=ExpeditionVocabulary.Profile(save.rogue).mode;Action refresh=null,layout=null;Action<int> answer=null;
  var progress=new HallPagedText{Font=GameTheme.Body(11)};var title=new OutlinedLabel{Font=GameTheme.Body(14),ForeColor=GameTheme.Gold};var status=new OutlinedLabel{Font=GameTheme.Body(12),ForeColor=GuildChrome.Ivory};var word=new OutlinedLabel{Font=GameTheme.Latin(21),ForeColor=GuildChrome.Ivory};var meaning=new HallPagedText{Font=GameTheme.Body(12)};var input=new TextBox{BackColor=Color.FromArgb(34,68,65),ForeColor=TextColor,Font=GameTheme.Latin(15),AccessibleName="输入英文拼写"};var hear=new RogueIcon{Kind="speaker",AccessibleName="朗读单词",Size=new Size(32,32)};var star=new RogueIcon{Kind="star",AccessibleName="收藏单词",Size=new Size(32,32)};foreach(Control c in new Control[]{progress,title,status,word,meaning,input,hear,star})parent.Controls.Add(c);tips.SetToolTip(hear,"朗读单词");tips.SetToolTip(star,"收藏到生词本");hear.Click+=(o,e)=>{if(s.wordQuestion!=null)SpeakWord(s.wordQuestion.entry.word);};star.Click+=(o,e)=>{if(s.wordQuestion!=null)ToggleRogueFavorite(s.wordQuestion.entry,star);};
  var buttons=new VNButton[4];answer=choice=>{if(s.guidanceFeedback!=null)return;var q=s.wordQuestion;if(q==null||q.kind<0)return;bool ok=ExpeditionVocabulary.Correct(q,choice,input.Text);q.answered=true;q.spellingDraft=input.Text;s.guidanceCount++;if(ok)s.guidanceCorrect++;s.guidanceFeedback=(ok?"回答正确":"回答错误")+"\n"+ExpeditionVocabulary.Answer(save.rogue,q,ok,DateTime.Today);if(s.guidanceCount%3==0){bool granted=TavernHall.Guide(s);s.guidanceFeedback+="\n三题反馈：正确 "+s.guidanceCorrect+" / 3\n"+(granted?"下一份菜品收益 +4 · 待用 "+s.boosts+" / 3":"待用奖励已满，可继续学习");s.guidanceCorrect=0;}Persist();refresh();};
  for(int i=0;i<4;i++){int choice=i;buttons[i]=PartyButton("",()=>answer(choice),200,44);buttons[i].Font=GameTheme.Body(11);parent.Controls.Add(buttons[i]);}
  var next=PartyButton("下一题",()=>{if(s.guidanceFeedback==null&&s.wordQuestion!=null&&s.wordQuestion.kind==3){answer(-1);return;}if(s.guidanceFeedback==null&&s.wordQuestion!=null&&s.wordQuestion.kind>=0)return;s.guidanceSerial++;s.wordQuestion=null;s.guidanceFeedback=null;input.Text="";refresh();Persist();},180,40);parent.Controls.Add(next);next.KeyDown+=(o,e)=>{if(e.KeyCode==Keys.Enter){e.Handled=e.SuppressKeyPress=true;next.PerformClick();}};
  layout=()=>{int w=Math.Max(100,parent.ClientSize.Width-16),y=8;progress.Bounds=new Rectangle(8,y,w,36);y+=42;title.Bounds=new Rectangle(8,y,w,28);y+=32;int sh=TextRenderer.MeasureText(status.Text,status.Font,new Size(w-8,10000),TextFormatFlags.WordBreak|TextFormatFlags.NoPadding).Height+8;status.Bounds=new Rectangle(8,y,w,Math.Max(28,sh));y+=Math.Max(28,sh)+14;int wordWidth=Math.Min(w-84,TextRenderer.MeasureText(word.Text,word.Font,Size.Empty,TextFormatFlags.NoPadding|TextFormatFlags.SingleLine).Width+12);int wh=Math.Max(38,TextRenderer.MeasureText(word.Text,word.Font,new Size(Math.Max(20,wordWidth-5),10000),TextFormatFlags.WordBreak|TextFormatFlags.NoPadding).Height+8);word.Bounds=new Rectangle(8,y,Math.Max(20,wordWidth),wh);hear.Location=new Point(word.Right+4,y+2);star.Location=new Point(hear.Visible?hear.Right+4:word.Right+4,y+2);y+=wh+12;
   if(meaning.Visible){int mh=TextRenderer.MeasureText(meaning.Content,meaning.Font,new Size(w-20,10000),TextFormatFlags.WordBreak).Height+18;meaning.Bounds=new Rectangle(8,y,w,Math.Max(40,mh));y+=Math.Max(40,mh)+12;}
   if(input.Visible){input.Bounds=new Rectangle(8,y,w,34);y+=42;}
   if(buttons[0].Visible){int bw=(w-8)/2,bh=44;foreach(var option in buttons)bh=Math.Max(bh,TextRenderer.MeasureText(option.Text,option.Font,new Size(bw-20,10000),TextFormatFlags.WordBreak|TextFormatFlags.NoPadding).Height+16);for(int i=0;i<4;i++)buttons[i].Bounds=new Rectangle(8+(i%2)*(bw+8),y+(i/2)*(bh+8),bw,bh);y+=2*(bh+8);}
   if(next.Visible){next.Bounds=new Rectangle(8+Math.Max(0,w-180),y,Math.Min(w,180),40);y+=48;}
  };
  refresh=()=>{if(s.wordQuestion==null)s.wordQuestion=ExpeditionVocabulary.Next(save.rogue,VocabularyBank(mode),DateTime.Today);var q=s.wordQuestion;bool feedback=s.guidanceFeedback!=null,available=q.kind>=0,spelling=q.kind==3;progress.Content=VocabularyProgressText(mode);title.Text=feedback?"指导结算":"英语指导 · "+(s.guidanceCount%3+1)+" / 3";status.Text=feedback?s.guidanceFeedback:available?ExpeditionVocabulary.Status(save.rogue,q,DateTime.Today):"今日暂无待学词汇，可返回英语指导选择词库或继续营业。";status.ForeColor=feedback?(s.guidanceFeedback.StartsWith("回答正确")?Color.FromArgb(112,225,155):Color.FromArgb(249,151,126)):GuildChrome.Ivory;word.Text=!available?"":feedback||q.kind==0?q.entry.word:ExpeditionVocabulary.Meaning(q.entry);word.Font=feedback||q.kind==0?GameTheme.Latin(feedback?16:21):GameTheme.Body(15);word.Visible=available;hear.Visible=available&&(feedback||q.kind==0);star.Visible=available;star.Selected=available&&save.words.Any(v=>v.text.Equals(q.entry.word,StringComparison.OrdinalIgnoreCase));meaning.Visible=feedback&&available;meaning.Content=meaning.Visible?ExpeditionVocabulary.Meaning(q.entry):"";input.Visible=spelling&&!feedback;for(int i=0;i<4;i++){buttons[i].Visible=available&&!spelling&&!feedback;buttons[i].Text=i<q.options.Count?((char)('A'+i))+". "+q.options[i]:"";}next.Visible=feedback||spelling||!available;next.Text=feedback?"继续 · Enter":spelling?"提交拼写":"刷新到期复习";if(!feedback&&spelling)input.Text=q.spellingDraft??"";layout();if(feedback)next.Focus();};input.TextChanged+=(o,e)=>{if(s.wordQuestion!=null)s.wordQuestion.spellingDraft=input.Text;};input.KeyDown+=(o,e)=>{if(e.KeyCode==Keys.Enter){e.Handled=e.SuppressKeyPress=true;next.PerformClick();}};parent.Resize+=(o,e)=>{if(!word.IsDisposed)layout();};hallSaveStudy=()=>{};refresh();}
 void BuildHallManagement(Panel parent,TavernHallState s,Func<bool> paused,Action<bool> pause){hallRefreshAudio=null;hallSaveStudy=null;int tab=Math.Max(0,hallManagementTab);Action render=null;render=()=>{while(parent.Controls.Count>0)parent.Controls[0].Dispose();var rows=HallRows(parent,7);rows.RowStyles[0].Height=40;for(int i=1;i<7;i++)rows.RowStyles[i].Height=10;var text=new HallPagedText{Dock=DockStyle.Fill};rows.Controls.Add(text,0,0);HallButton(rows,6,"切换：员工 → 菜单 → 设施 / 事件",()=>{tab=(tab+1)%3;render();});if(tab==0){var c=s.chef;var w=s.server;text.Content=EmployeeText(c,true)+"\n\n"+EmployeeText(w,false)+"\n熟客满意接待 "+s.regularVisits+" 次 · "+(s.regularVisits>=3?"熟客开始回访":"3次满意接待后回访");HallButton(rows,1,"查看实时能力与成长",render);HallButton(rows,2,"库存补购："+(s.autoBuy?"开启":"关闭"),()=>{s.autoBuy=!s.autoBuy;render();});HallButton(rows,3,"每日补购上限 "+s.purchaseLimit+" 金币",()=>{s.purchaseLimit=s.purchaseLimit==80?120:s.purchaseLimit==120?0:80;render();});HallButton(rows,4,"休息：疲劳达到体力上限自动休息",()=>{s.notice="厨师和服务员会自行休息，空闲时也恢复体力。";});HallButton(rows,5,"分工：莉瑟厨房 · 艾莉娅大厅 / 饮品",()=>s.notice="陆川负责安排与指导；三级解锁双份切配 / 双盘送餐，五级解锁拿手料理 / 熟练服务。" );}
 else if(tab==1){text.Content="今日菜单 · 制作成长：初学 → 熟练（8份）→ 招牌（24份）\n胡萝卜 "+s.carrots+" · 面粉 "+s.flour+"\n收入 "+s.revenue+" − 采购 "+s.cost+" = 净收益 "+(s.revenue-s.cost)+"\n两种原料每单位2金币；不同菜品耗料、价格与耗时不同。";for(int i=0;i<4;i++){int dish=i;HallButton(rows,i+1,TavernHall.Dishes[i]+" · "+TavernHall.Prices[i]+"金币 · "+new[]{"初学","熟练","招牌"}[s.recipes[i].Rank]+" "+s.recipes[i].made+"份 · "+(s.recipes[i].enabled?"上架":"停售"),()=>{if(s.recipes.Count(r=>r.enabled)==1&&s.recipes[dish].enabled){s.notice="至少保留一道菜单。";return;}s.recipes[dish].enabled=!s.recipes[dish].enabled;render();});}HallButton(rows,5,"采购各8份食材 · 32金币",()=>{if(save.rogue.coins<32){s.notice="金币不足，开启自动补购可少量补充。";return;}save.rogue.coins-=32;s.cost+=32;s.carrots+=8;s.flour+=8;Persist();render();});}
 else{text.Content="出餐台改善交接速度；双锅炉灶让三级厨师同时制作两份。\n布局编辑时暂停营业，固定入口与通路保留。\n当前布局："+(s.layout==0?"吧台左侧交接":"吧台右侧交接，搬运路线较长")+"\n"+(s.eventPending?"团体订餐：接下来接待3人，额外奖励18金币；没有限时，题组结束后处理。":"第2日起开放团体订餐。")+"\n"+s.notice;HallButton(rows,1,"改善出餐台 · 30金币（"+s.upgrade+" / 2）",()=>{if(s.upgrade>=2){s.notice="出餐台已升至满级。";return;}if(save.rogue.coins<30){s.notice="改善出餐台需要30金币。";return;}if(s.upgrade<2&&save.rogue.coins>=30){save.rogue.coins-=30;s.upgrade++;Persist();render();}});HallButton(rows,2,"双锅炉灶 · 45金币"+(s.stove>0?" · 已安装":""),()=>{if(s.stove>0){s.notice="双锅炉灶已经安装。";return;}if(save.rogue.coins<45){s.notice="安装双锅炉灶需要45金币。";return;}if(s.stove==0&&save.rogue.coins>=45){save.rogue.coins-=45;s.stove=1;Persist();render();}});HallButton(rows,3,"布局：暂停并调整出餐路线",()=>{pause(true);s.layout=1-s.layout;s.notice="已切换合法交接位置，入口与通路畅通；点击继续恢复营业。";render();});HallButton(rows,4,"接受团体订餐",()=>{if(s.study!=null&&!s.study.finished){s.notice="事件保留，完整题组结束后再决定。";return;}if(s.eventPending){s.eventPending=false;s.eventAccepted=true;s.notice="已接受：完成接下来3次接待，无额外限时。";render();}});HallButton(rows,5,"暂不接单 / 查看结算",()=>{if(s.eventPending&&s.study!=null&&!s.study.finished){s.notice="事件保留，完整题组结束后再决定。";return;}if(s.eventPending){s.eventPending=false;s.eventResolved=true;}s.notice="营业收入 "+s.revenue+"，采购成本 "+s.cost+"，净收益 "+(s.revenue-s.cost)+"；目标6人："+(s.served>=6?"已达成":"继续努力");render();});} DateTime refreshed=DateTime.MinValue;hallRefreshManagement=()=>{if(text.IsDisposed||(DateTime.UtcNow-refreshed).TotalSeconds<1)return;refreshed=DateTime.UtcNow;if(tab==0)text.LiveContent=EmployeeText(s.chef,true)+"\n\n"+EmployeeText(s.server,false)+"\n熟客满意接待 "+s.regularVisits+" 次 · "+(s.regularVisits>=3?"熟客开始回访":"3次满意接待后回访");else if(tab==1){text.LiveContent="今日菜单 · 制作成长：初学 → 熟练（8份）→ 招牌（24份）\n胡萝卜 "+s.carrots+" · 面粉 "+s.flour+"\n收入 "+s.revenue+" − 采购 "+s.cost+" = 净收益 "+(s.revenue-s.cost)+"\n两种原料每单位2金币；不同菜品耗料、价格与耗时不同。";for(int dish=0;dish<4;dish++){var button=rows.GetControlFromPosition(0,dish+1) as VNButton;if(button!=null)button.Text=TavernHall.Dishes[dish]+" · "+TavernHall.Prices[dish]+"金币 · "+new[]{"初学","熟练","招牌"}[s.recipes[dish].Rank]+" "+s.recipes[dish].made+"份 · "+(s.recipes[dish].enabled?"上架":"停售");}}}; };render();}
 string EmployeeText(HallEmployee e,bool chef){return e.name+" · "+(chef?"厨师 · 特长：细心":"服务员 · 特长：健谈")+" Lv."+e.level+"\n手艺 "+e.Craft+" · 效率 "+e.Efficiency+" · 服务 "+e.Service+" · 体力 "+e.Stamina+"\n成长 "+e.xp+" / "+(e.level==5?"满级":e.NextXp.ToString())+" · 工作贡献 "+e.workXp+" / 研修贡献 "+e.listeningXp+"\n疲劳 "+(int)e.fatigue+" · "+e.action+"\n三级："+(chef?"双份切配（需双锅）":"双盘送餐")+" · 五级："+(chef?"拿手料理（品质+3）":"熟练服务（小费提升）");}
}


