using System;using System.Linq;using System.Collections.Generic;
public class WoodlandNode {public string id{get;set;}public int row{get;set;}public int lane{get;set;}public string kind{get;set;}public bool visited{get;set;}}
public class WoodlandRoad {public string from{get;set;}public string to{get;set;}public string hazard{get;set;}}
public class ToxicWoodlandRun {
 public int version{get;set;}public int seed{get;set;}public int level{get;set;}public int steps{get;set;}public int spores{get;set;}public int supplies{get;set;}public int loot{get;set;}public int scoutRow{get;set;}public string current{get;set;}public string pending{get;set;}public string mode{get;set;}public string message{get;set;}public bool roadDone{get;set;}public bool campUsed{get;set;}public bool rewarded{get;set;}public bool bossReward{get;set;}public bool victory{get;set;}
 public List<WoodlandNode> nodes{get;set;}public List<WoodlandRoad> roads{get;set;}public List<string> path{get;set;}public List<PartyUnit> party{get;set;}public RogueRun combat{get;set;}
 public ToxicWoodlandRun(){nodes=new List<WoodlandNode>();roads=new List<WoodlandRoad>();path=new List<string>();party=new List<PartyUnit>();}
}
public static class ToxicWoodland {
 public const string Id="toxic-woodland";
 public static ToxicWoodlandRun Create(int seed,Save save){seed&=0x7fffffff;var r=new ToxicWoodlandRun{version=1,seed=seed,level=Engine.Level(save.xp),supplies=4,mode="map",scoutRow=2};var rng=new Random(seed);string[][] kinds={new[]{"entrance"},new[]{"battle","event","cache"},new[]{"cache","scout","event"},new[]{"battle","battle","battle"},new[]{"camp"},new[]{"merchant","altar","cache"},new[]{"battle","elite","battle"},new[]{"spring","scout","event"},new[]{"guard","guard","guard"},new[]{"boss"}};
  for(int row=0;row<10;row++){var shuffled=kinds[row].OrderBy(x=>rng.Next()).ToArray();for(int i=0;i<shuffled.Length;i++)r.nodes.Add(new WoodlandNode{id=row+"-"+i,row=row,lane=shuffled.Length==1?1:i,kind=shuffled[i]});}
  for(int row=0;row<9;row++)foreach(var a in r.nodes.Where(n=>n.row==row))foreach(var b in r.nodes.Where(n=>n.row==row+1))if(a.row==0||b.row==4||a.row==4||b.row==9||Math.Abs(a.lane-b.lane)<=1){int roll=rng.Next(100);r.roads.Add(new WoodlandRoad{from=a.id,to=b.id,hazard=row==0||row==8?"clear":roll<55?"clear":roll<75?"fog":roll<90?"roots":"ambush"});}
  r.current="0-0";r.steps=1;r.path.Add(r.current);r.nodes[0].visited=true;r.message="剧毒林地 · 取得巢心净化样本。每条路线经过十个节点；危险道路与地点分别显示。";var temp=PartyCombat.Create(new RogueRun{id="tavern-tutorial",seed=seed},save);r.party=temp.heroes;foreach(var h in r.party){h.hp=h.maxHp;Reset(h);}return r;
 }
 public static string Name(string kind){switch(kind){case "entrance":return "林地入口";case "battle":return "菌群巢穴";case "elite":return "精英菌群";case "guard":return "巢心守卫";case "camp":return "采菌人营地";case "cache":return "失落货车";case "scout":return "林间望台";case "event":return "采菌人求援";case "merchant":return "游商补给";case "altar":return "孢子祭坛";case "spring":return "净化泉眼";case "boss":return "腐冠母株";default:return kind;}}
 public static string RoadName(string kind){return kind=="fog"?"毒雾":kind=="roots"?"根须阻碍":kind=="ambush"?"道路伏击":"平安道路";}
 public static List<WoodlandNode> Available(ToxicWoodlandRun r){if(r.mode!="map")return new List<WoodlandNode>();return r.roads.Where(e=>e.from==r.current).Select(e=>r.nodes.First(n=>n.id==e.to)).ToList();}
 public static bool Choose(ToxicWoodlandRun r,string id){if(!Available(r).Any(n=>n.id==id))return false;r.pending=id;r.roadDone=false;r.mode="road";r.message=RoadName(r.roads.First(e=>e.from==r.current&&e.to==id).hazard);return true;}
 public static bool ResolveRoad(ToxicWoodlandRun r,bool useSupply){if(r.mode!="road"||r.roadDone)return false;var road=r.roads.First(e=>e.from==r.current&&e.to==r.pending);if(useSupply&&r.supplies<=0)return false;r.roadDone=true;if(road.hazard=="ambush"){r.mode="road-combat";return true;}if(road.hazard=="fog"||road.hazard=="roots"){if(useSupply)r.supplies--;else if(road.hazard=="fog")r.spores=Math.Min(5,r.spores+1);else foreach(var h in r.party.Where(h=>h.hp>0))h.hp=Math.Max(1,h.hp-5);}Arrive(r);return true;}
 public static void Arrive(ToxicWoodlandRun r){var n=r.nodes.First(x=>x.id==r.pending);r.current=n.id;r.steps=n.row+1;r.pending=null;if(!r.path.Contains(n.id))r.path.Add(n.id);n.visited=true;r.scoutRow=Math.Max(r.scoutRow,Math.Min(9,n.row+1));r.mode=n.kind=="battle"||n.kind=="elite"||n.kind=="guard"||n.kind=="boss"?"node-combat":"event";r.campUsed=false;r.message=Name(n.kind);}
 public static void FinishNode(ToxicWoodlandRun r){r.mode="map";r.message="选择下一条道路；已完成 "+r.steps+" / 10 节点。";}
 public static void Reset(PartyUnit h){h.dots.Clear();h.bleed=h.burn=h.block=h.dodge=h.strength=h.weak=h.vulnerable=h.silence=h.slow=h.shield=h.marks=h.resolve=h.riposte=h.anchored=0;h.guard=null;h.cooldowns.Clear();h.used.Clear();h.expires.Clear();h.actions=0;h.acted=false;}
 public static void Rest(ToxicWoodlandRun r,int percent){foreach(var h in r.party){if(h.hp<=0)h.hp=Math.Max(1,h.maxHp*30/100);else h.hp=Math.Min(h.maxHp,h.hp+h.maxHp*percent/100);Reset(h);}r.spores=Math.Max(0,r.spores-1);}
 public static bool Event(ToxicWoodlandRun r,string choice){if(r.mode!="event")return false;var n=r.nodes.First(x=>x.id==r.current);switch(n.kind){case "camp":if(choice=="leave"){FinishNode(r);return true;}if(r.campUsed)return false;Rest(r,40);r.supplies++;r.campUsed=true;r.message="营地休整完成：恢复40%生命、清除状态并补给1份。可调整技能或撤退。";return true;
 case "spring":Rest(r,25);break;case "scout":r.scoutRow=Math.Min(9,n.row+3);r.loot+=8;break;case "merchant":if(choice=="buy"){if(r.loot<12)return false;r.loot-=12;r.supplies+=2;}break;case "altar":if(choice=="purify"){if(r.supplies<1)return false;r.supplies--;r.spores=Math.Max(0,r.spores-2);}else if(choice=="power"){r.spores=Math.Min(5,r.spores+1);foreach(var h in r.party)h.attack+=2;}break;case "event":if(choice=="help"){if(r.supplies<1)return false;r.supplies--;Rest(r,15);r.scoutRow=Math.Min(9,n.row+2);r.loot+=15;}break;case "cache":r.loot+=choice=="search"?25:12;if(choice=="search")r.spores=Math.Min(5,r.spores+1);break;default:return false;}FinishNode(r);return true;}
 public static string[] Encounter(ToxicWoodlandRun r,bool road){var n=r.nodes.First(x=>x.id==r.current);var rng=new Random(r.seed+n.row*97+n.lane*13+(road?911:0));if(!road&&n.kind=="boss")return new[]{"boss"};if(!road&&(n.kind=="elite"||n.kind=="guard")){string[][] sets={new[]{"crab","bard","cannon"},new[]{"beast","beast","moth"},new[]{"crab","moth","moth"},new[]{"beast","bard","cannon"}};return sets[rng.Next(sets.Length)];}if(n.row<=1&&!road)return new[]{"beast"};string[][] normal={new[]{"beast","moth"},new[]{"beast","beast"},new[]{"beast","bard"},new[]{"crab","moth"},new[]{"beast","cannon"},new[]{"moth","moth"}};return normal[rng.Next(normal.Length)];}
 public static RogueRun StartBattle(ToxicWoodlandRun r,Save save,List<RogueEntry> bank){if(r.mode!="node-combat"&&r.mode!="road-combat")return r.combat;if(r.combat!=null)return r.combat;bool road=r.mode=="road-combat";var run=new RogueRun{id=Id,seed=r.seed,state="combat",depth=r.steps,pool=bank,hp=r.party.Sum(h=>h.hp),partyRoster=r.party};run.partyBattle=PartyCombat.CreateEncounter(run,save,Encounter(r,road),r.level,r.spores);for(int i=0;i<run.partyBattle.heroes.Count;i++){var h=run.partyBattle.heroes[i];var previous=r.party.First(p=>p.id==h.id);h.attack=previous.attack;}r.combat=run;return run;}
 public static bool FinishBattle(ToxicWoodlandRun r){if(r.combat==null||String.IsNullOrEmpty(r.combat.partyBattle.outcome))return false;var b=r.combat.partyBattle;r.party=b.heroes;r.combat=null;if(b.outcome=="lost"){r.mode="failed";r.message="远征队伍倒下，剧情与永久进度不受影响。";return true;}r.loot+=r.mode=="road-combat"?8:r.nodes.First(n=>n.id==r.current).kind=="elite"?30:18;if(r.mode=="road-combat"){Arrive(r);return true;}if(r.steps==10){r.mode="won";r.victory=true;r.bossReward=true;r.message="腐冠母株倒下。已取得净化样本，完成十节点远征。";}else FinishNode(r);return true;}
 public static bool Provision(ToxicWoodlandRun r){if(r.mode!="map"||r.supplies<1||!r.party.Any(h=>h.hp>0&&(h.hp<h.maxHp||h.dots.Count>0)))return false;r.supplies--;foreach(var h in r.party.Where(h=>h.hp>0)){h.hp=Math.Min(h.maxHp,h.hp+Math.Max(1,h.maxHp*15/100));h.dots.Clear();h.bleed=h.burn=0;}r.message="消耗1补给：存活队员恢复15%生命，并清除持续伤害。";return true;}
 public static bool Retreat(ToxicWoodlandRun r){if(r.mode!="event"||r.nodes.First(n=>n.id==r.current).kind!="camp")return false;r.mode="retreated";r.message="从营地撤回驿站，带回现有普通战利品。";return true;}
 public static bool Claim(ToxicWoodlandRun r,Save save){if(r.rewarded||!(r.mode=="won"||r.mode=="retreated"||r.mode=="failed"))return false;r.rewarded=true;if(r.mode!="failed"){save.rogue.coins+=r.loot+(r.victory?80:0);save.xp+=r.victory?100:20;if(r.victory&&!save.storyFlags.Contains("toxic-woodland-cleared")){save.storyFlags.Add("toxic-woodland-cleared");save.storyFlags.Add("toxic-woodland-purification-sample");save.xp+=50;}}return true;}
}
