using System;using System.Linq;using System.Drawing;using System.Drawing.Drawing2D;using System.Windows.Forms;using System.Collections.Generic;using System.Diagnostics;
public sealed class WoodlandRouteMap:Panel {
 public ToxicWoodlandRun Run;public Image Art;public Action<string> Selected;readonly Dictionary<string,Rectangle> hits=new Dictionary<string,Rectangle>();public int SidebarWidth=310;public Action InterfaceCleanup;
 protected override void Dispose(bool disposing){if(disposing&&InterfaceCleanup!=null){InterfaceCleanup();InterfaceCleanup=null;}base.Dispose(disposing);}
 public WoodlandRouteMap(){DoubleBuffered=true;ResizeRedraw=true;BackColor=Color.FromArgb(14,32,35);SetStyle(ControlStyles.AllPaintingInWmPaint|ControlStyles.UserPaint|ControlStyles.OptimizedDoubleBuffer,true);}
 public Point Position(WoodlandNode n){int area=Width-SidebarWidth;int gap=Math.Max(24,(Height-145)/9);return new Point((int)(area*(.24+n.lane*.26)),Height-62-n.row*gap);}
 static void Label(Graphics g,string s,Rectangle box,int size,Color color,bool center=true){using(var f=GameTheme.Body(size))GameTheme.DrawText(g,s,f,box,color,(center?TextFormatFlags.HorizontalCenter:TextFormatFlags.Left)|TextFormatFlags.VerticalCenter|TextFormatFlags.NoPadding|TextFormatFlags.EndEllipsis);}
 protected override void OnPaintBackground(PaintEventArgs e){}
 protected override void OnPaint(PaintEventArgs e){var g=e.Graphics;g.InterpolationMode=InterpolationMode.NearestNeighbor;g.PixelOffsetMode=PixelOffsetMode.Half;g.SmoothingMode=SmoothingMode.None;g.Clear(BackColor);if(Art!=null){float scale=Math.Max(Width/(float)Art.Width,Height/(float)Art.Height);g.DrawImage(Art,(Width-Art.Width*scale)/2,(Height-Art.Height*scale)/2,Art.Width*scale,Art.Height*scale);}if(Run==null)return;int area=Width-SidebarWidth;
  using(var shade=new SolidBrush(Color.FromArgb(85,5,18,23)))g.FillRectangle(shade,0,0,area,Height);int fogY=Run.scoutRow>=9?0:Position(Run.nodes.First(n=>n.row==Run.scoutRow)).Y-22;using(var fog=new SolidBrush(Color.FromArgb(155,8,22,35)))if(fogY>0)g.FillRectangle(fog,0,0,area,fogY);for(int x=0;x<area;x+=24)if(fogY>0)using(var ink=new SolidBrush(Color.FromArgb(110+(x/24%3)*15,14,38,48)))g.FillRectangle(ink,x,fogY-10-(x/24%3)*8,24,26);
  var available=ToxicWoodland.Available(Run);foreach(var road in Run.roads){var a=Run.nodes.First(n=>n.id==road.from);var b=Run.nodes.First(n=>n.id==road.to);var from=Position(a);var to=Position(b);bool taken=Run.path.Contains(a.id)&&Run.path.Contains(b.id);bool next=road.from==Run.current;var color=taken?GuildChrome.Gold:next?Color.FromArgb(176,207,177):Color.FromArgb(80,99,114);using(var under=new Pen(Color.FromArgb(150,6,18,22),6))g.DrawLine(under,from,to);using(var pen=new Pen(color,taken?3:2)){if(!taken)pen.DashStyle=DashStyle.Dash;g.DrawLine(pen,from,to);}if(next&&road.hazard!="clear"){var mid=new Point((from.X+to.X)/2,(from.Y+to.Y)/2);using(var ink=new SolidBrush(road.hazard=="ambush"?Color.FromArgb(204,115,102):Color.FromArgb(157,188,129)))g.FillRectangle(ink,mid.X-9,mid.Y-9,18,18);Label(g,road.hazard=="ambush"?"战":road.hazard=="fog"?"毒":"阻",new Rectangle(mid.X-9,mid.Y-9,18,18),8,Color.FromArgb(14,32,35));}}
  hits.Clear();foreach(var n in Run.nodes){var point=Position(n);bool known=n.row<=Run.scoutRow||n.visited||n.kind=="boss";bool selectable=available.Any(a=>a.id==n.id);int radius=Height<600?12:20;var rect=new Rectangle(point.X-radius,point.Y-radius,radius*2,radius*2);hits[n.id]=rect;var diamond=new[]{new Point(point.X,point.Y-radius),new Point(point.X+radius,point.Y),new Point(point.X,point.Y+radius),new Point(point.X-radius,point.Y)};Color color=n.visited?GuildChrome.Gold:selectable?Color.FromArgb(178,220,186):Color.FromArgb(105,126,142);using(var ink=new SolidBrush(Color.FromArgb(235,13,39,40)))g.FillPolygon(ink,diamond);using(var pen=new Pen(color,n.id==Run.current?3:2))g.DrawPolygon(pen,diamond);string icon=!known?"?":n.kind=="battle"||n.kind=="guard"?"战":n.kind=="elite"?"险":n.kind=="boss"?"王":n.kind=="camp"?"营":n.kind=="merchant"?"商":n.kind=="scout"?"望":n.kind=="spring"?"泉":n.kind=="altar"?"祭":n.kind=="entrance"?"始":"遇";Label(g,icon,rect,Height<600?9:12,color);if(n.id==Run.current)Label(g,"▼",new Rectangle(point.X-14,point.Y-radius-22,28,22),13,GuildChrome.Gold);if(Height>=600||n.id==Run.current)Label(g,known?ToxicWoodland.Name(n.kind):"迷雾",new Rectangle(point.X-68,point.Y+radius+2,136,19),Height<600?7:9,color);}
  using(var ink=new SolidBrush(Color.FromArgb(240,12,35,38)))g.FillRectangle(ink,area,0,SidebarWidth,Height);using(var pen=new Pen(GuildChrome.Gold,2))g.DrawLine(pen,area,0,area,Height);Label(g,"剧毒林地",new Rectangle(20,14,area-40,30),19,GuildChrome.Ivory);Label(g,"岔路前进 · 十节点远征",new Rectangle(20,47,area-40,24),10,GuildChrome.Muted);base.OnPaint(e);
 }
 protected override void OnMouseUp(MouseEventArgs e){base.OnMouseUp(e);if(Run==null||Run.mode!="map"||Selected==null)return;foreach(var pair in hits)if(pair.Value.Contains(e.Location)&&ToxicWoodland.Available(Run).Any(n=>n.id==pair.Key)){Selected(pair.Key);return;}}
}
public sealed class WoodlandCrossfade:Control {
 readonly Timer timer=new Timer{Interval=16};readonly Stopwatch time=new Stopwatch();public Bitmap Before,After;public Action Completed;public WoodlandCrossfade(){DoubleBuffered=true;SetStyle(ControlStyles.Opaque|ControlStyles.UserPaint|ControlStyles.AllPaintingInWmPaint,true);timer.Tick+=(s,e)=>{Invalidate();if(time.ElapsedMilliseconds>=280){timer.Stop();if(Completed!=null)Completed();}};}
 public void Start(){time.Restart();timer.Start();}protected override void OnPaint(PaintEventArgs e){if(After!=null)e.Graphics.DrawImage(After,ClientRectangle);else e.Graphics.Clear(Color.FromArgb(14,32,35));if(Before!=null){float alpha=After==null?1:Math.Max(0,1-time.ElapsedMilliseconds/280f);using(var attr=new System.Drawing.Imaging.ImageAttributes()){var matrix=new System.Drawing.Imaging.ColorMatrix();matrix.Matrix33=alpha;attr.SetColorMatrix(matrix);e.Graphics.DrawImage(Before,ClientRectangle,0,0,Before.Width,Before.Height,GraphicsUnit.Pixel,attr);}}}protected override void Dispose(bool d){if(d){timer.Dispose();if(Before!=null)Before.Dispose();if(After!=null)After.Dispose();}base.Dispose(d);}
}
public partial class Game {
 WoodlandRouteMap woodlandMap;bool woodlandChanging;
 Image ToxicBattleBackground(){return CachedImage(System.IO.Path.Combine(root,"assets","dungeons","toxic-woodland","battle-glade-muted.png"));}
 void ToxicTransition(Action action){if(woodlandChanging)return;woodlandChanging=true;var overlay=new WoodlandCrossfade{Bounds=content.Bounds,Anchor=AnchorStyles.Left|AnchorStyles.Right|AnchorStyles.Top|AnchorStyles.Bottom};if(content.Width>0&&content.Height>0){overlay.Before=new Bitmap(content.Width,content.Height);content.DrawToBitmap(overlay.Before,new Rectangle(Point.Empty,overlay.Before.Size));}Controls.Add(overlay);overlay.BringToFront();overlay.Refresh();try{using(var redraw=new BattleRedrawScope(content)){action();content.PerformLayout();overlay.After=new Bitmap(Math.Max(1,content.Width),Math.Max(1,content.Height));content.DrawToBitmap(overlay.After,new Rectangle(Point.Empty,overlay.After.Size));}}catch{Controls.Remove(overlay);overlay.Dispose();woodlandChanging=false;throw;}overlay.Completed=()=>{Controls.Remove(overlay);overlay.Dispose();woodlandChanging=false;content.Focus();UpdateRogueAudio();};overlay.Start();}
 void ShowToxicWoodlandEntry(){ToxicTransition(()=>{ClearPage();page="toxic-entry";var surface=new CardRewardSurface{Dock=DockStyle.Fill,Art=CachedImage(System.IO.Path.Combine(root,"assets","dungeons","toxic-woodland","route-map.png")),CompositeChildren=true};content.Controls.Add(surface);var panel=new BattleGlassPanel{Size=new Size(620,400),Padding=new Padding(25)};surface.Controls.Add(panel);var title=new OutlinedLabel{Text="支线远征 · 剧毒林地",ForeColor=GuildChrome.Gold,Font=GameTheme.Body(22),Bounds=new Rectangle(28,28,565,45)};panel.Controls.Add(title);bool active=save.toxicWoodland!=null&&!save.toxicWoodland.rewarded;var text=new OutlinedLabel{Text=active?"发现上次未结束的远征：剧毒林地。\n进度：第"+save.toxicWoodland.steps+" / 10 节点。\n路线、生命、状态与当前战斗均已保存。\n点击下方按钮继续上次远征。":"探索十个地点，在岔路间选择路线。\n普通遭遇1—3只怪物，可出现重复种类。\n第5节点可休整与调整技能，第10节点挑战腐冠母株。\n毒雾、阻碍与伏击显示在道路上；退出后可继续。",ForeColor=GuildChrome.Ivory,Font=GameTheme.Body(12),Bounds=new Rectangle(28,88,565,150)};panel.Controls.Add(text);var enter=PartyButton(active?"继续上次未完成的远征":"整备完毕 · 出发",()=>{Action enterRun=()=>{if(!active){save.toxicWoodland=ToxicWoodland.Create(unchecked((int)DateTime.UtcNow.Ticks),save);save.hasGame=true;}Persist();ShowToxicWoodland();};if(active)NavigateMenu(enterRun,"继续剧毒林地远征",false,true);else ToxicTransition(enterRun);},260,48);enter.Location=new Point(active?(panel.Width-enter.Width)/2:28,active?250:260);panel.Controls.Add(enter);if(!active){var skills=PartyButton("配置男女主技能",()=>ShowHeroSkillBook(true),260,44);skills.Location=new Point(318,260);panel.Controls.Add(skills);}var back=PartyButton("返回驿站",()=>ToxicTransition(ShowTavernHub),260,44);back.Location=new Point(active?(panel.Width-back.Width)/2:28,active?310:323);panel.Controls.Add(back);Action layout=()=>panel.Location=new Point((surface.Width-panel.Width)/2,(surface.Height-panel.Height)/2);surface.Resize+=(s,e)=>layout();layout();});}
 void ShowToxicWoodland(){var r=save.toxicWoodland;if(r==null){ShowToxicWoodlandEntry();return;}if(r.mode=="node-combat"||r.mode=="road-combat"){var battle=ToxicWoodland.StartBattle(r,save,RogueBank());Persist();RenderPartyBattle(battle);return;}bool reuse=woodlandMap!=null&&!woodlandMap.IsDisposed&&woodlandMap.Parent==content&&woodlandMap.Run==r;using(var redraw=new BattleRedrawScope(content)){if(!reuse){ClearPage();woodlandMap=new WoodlandRouteMap{Dock=DockStyle.Fill,Run=r,Art=CachedImage(System.IO.Path.Combine(root,"assets","dungeons","toxic-woodland","route-map.png"))};content.Controls.Add(woodlandMap);}else {if(woodlandMap.InterfaceCleanup!=null){woodlandMap.InterfaceCleanup();woodlandMap.InterfaceCleanup=null;}while(woodlandMap.Controls.Count>0)woodlandMap.Controls[0].Dispose();}page="toxic-map";var map=woodlandMap;map.Selected=id=>{if(woodlandChanging||!ToxicWoodland.Choose(r,id))return;Persist();ShowToxicWoodland();};int side=Math.Min(340,Math.Max(270,map.Width/4));map.SidebarWidth=side;var body=new FlowLayoutPanel{Width=side-30,AutoScroll=true,FlowDirection=FlowDirection.TopDown,WrapContents=false,BackColor=Color.Transparent};map.Controls.Add(body);Action layout=()=>{int width=Math.Min(340,Math.Max(270,map.Width/4));map.SidebarWidth=width;body.Bounds=new Rectangle(map.Width-width+14,18,width-28,map.Height-35);foreach(Control c in body.Controls){c.Width=body.Width-30;var l=c as OutlinedLabel;if(l!=null)l.Height=TextRenderer.MeasureText(l.Text,l.Font,new Size(Math.Max(1,l.Width-5),1000),TextFormatFlags.WordBreak|TextFormatFlags.NoPadding).Height+12;}map.Invalidate();};EventHandler resized=(s,e)=>layout();map.Resize+=resized;map.InterfaceCleanup=()=>map.Resize-=resized;
 Action<string,int,Color> label=(txt,size,color)=>{var l=new OutlinedLabel{Text=txt,ForeColor=color,Font=GameTheme.Body(size),Width=side-55,Height=txt.Split('\n').Length*(size+10)+8,BackColor=Color.Transparent,Margin=new Padding(3,5,3,8)};body.Controls.Add(l);};Action<string,Action,bool> button=(txt,click,enabled)=>{var b=PartyButton(txt,click,side-55,42);b.Enabled=enabled;b.Margin=new Padding(3,4,3,4);body.Controls.Add(b);};
 label("远征进度 "+r.steps+" / 10",16,GuildChrome.Gold);label("孢雾 "+r.spores+" / 5 · 补给 "+r.supplies+"\n战利品 "+r.loot+" · 未返回前暂存",11,GuildChrome.Ivory);foreach(var h in r.party)label(h.name+"  "+h.hp+" / "+h.maxHp+" · 站位"+h.rank,11,GuildChrome.Ivory);label(r.message??"",11,GuildChrome.Muted);
 Action refresh=()=>{Persist();ShowToxicWoodland();};Action proceed=()=>ToxicTransition(()=>{Persist();ShowToxicWoodland();});
 if(r.mode=="map"){button("1补给野外疗伤：恢复15%",()=>{if(ToxicWoodland.Provision(r))refresh();},r.supplies>0&&r.party.Any(h=>h.hp>0&&(h.hp<h.maxHp||h.dots.Count>0)));label("只能选择相连的下一站。\n战：遭遇  遇：机遇  营：休整\n道路：毒雾 / 阻碍 / 伏击\n未知地点可通过望台侦察。",10,GuildChrome.Muted);foreach(var n in ToxicWoodland.Available(r)){var node=n;var road=r.roads.First(e=>e.from==r.current&&e.to==n.id);button(ToxicWoodland.Name(n.kind)+" · "+ToxicWoodland.RoadName(road.hazard),()=>{if(ToxicWoodland.Choose(r,node.id))refresh();},true);}}
 else if(r.mode=="road"){var road=r.roads.First(e=>e.from==r.current&&e.to==r.pending);label(road.hazard=="fog"?"使用1补给安全穿过，或孢雾+1。\n孢雾每级提升怪物生命3%。":road.hazard=="roots"?"使用1补给清路，或每名存活角色损失5生命（不致死）。":road.hazard=="ambush"?"道路伏击：两只怪物；胜利后抵达选定地点。":"道路平安，抵达选定地点。",10,GuildChrome.Ivory);if(road.hazard=="fog"||road.hazard=="roots")button("消耗1补给安全通过",()=>{if(ToxicWoodland.ResolveRoad(r,true))proceed();},r.supplies>0);button(road.hazard=="ambush"?"迎战伏击":"继续前进",()=>{if(ToxicWoodland.ResolveRoad(r,false))proceed();},true);}
 else if(r.mode=="event"){string kind=r.nodes.First(n=>n.id==r.current).kind;Action<string> choose=c=>{if(ToxicWoodland.Event(r,c))refresh();};if(kind=="camp"){button("休整：回血40%并补给1份",()=>choose("rest"),!r.campUsed);button("调整五个携带技能",()=>ShowHeroSkillBook(true),true);button("离开营地，继续远征",()=>choose("leave"),true);button("撤退并结算战利品",()=>{if(ToxicWoodland.Retreat(r))refresh();},true);}else if(kind=="cache"){button("谨慎拾取：战利品+12",()=>choose("take"),true);button("深入搜查：+25，孢雾+1",()=>choose("search"),true);}else if(kind=="merchant"){button("12战利品购买2补给",()=>choose("buy"),r.loot>=12);button("离开游商",()=>choose("leave"),true);}else if(kind=="altar"){button("1补给净化：孢雾-2",()=>choose("purify"),r.supplies>0);button("接受强化：攻击+2，孢雾+1",()=>choose("power"),true);button("绕过祭坛",()=>choose("leave"),true);}else if(kind=="event"){button("1补给救援：回血15%与侦察",()=>choose("help"),r.supplies>0);button("不冒险，继续前进",()=>choose("leave"),true);}else button(kind=="spring"?"泉水疗养：回血25%与净化":"登高侦察：揭示后续三层",()=>choose("resolve"),true);}
 else {label(r.mode=="won"?"通关奖励：80金币、100经验\n首次通关额外50经验与净化样本。":r.mode=="retreated"?"带回已有战利品，获得20经验。":"失败不扣永久进度，本次战利品遗失。",11,GuildChrome.Ivory);button(r.rewarded?"返回驿站":"领取结果并返回驿站",()=>ToxicTransition(()=>{ToxicWoodland.Claim(r,save);Persist();ShowTavernHub();}),true);}
 button("保存并返回主界面",()=>ToxicTransition(()=>{Persist();ShowMain();}),true);layout();Persist();map.Invalidate();}UpdateRogueAudio();}
 void FinishToxicBattle(){var r=save.toxicWoodland;if(r==null||!ToxicWoodland.FinishBattle(r))return;Persist();ToxicTransition(ShowToxicWoodland);}
}
